### PR TITLE
Fix link emit for xref containing #

### LINKED ISSUE #1840: [api-documenter] markdown-style xref links in yaml output should be url encoded.
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

In the yaml output, markdown links generated from `{@link}` tags should be properly encoded as the `#` character is treated as a the hash part of a URL:

**index.d.ts**
```ts
export declare class C {
  x: number;
  /** {@link C.x} */
  bar(): void;
}
```

**index.yml**
```yml
- uid: 'mypackage!C#bar:method'
  summary: >-
    [C.x](xref:mypackage!C#x:member)
```

**DocFX output**
```
Build succeeded with warning.
[20-04-22 01:14:24.231]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](path/to/index.yml)1 invalid cross reference(s) "[C.x](xref:mypackage!C#x:member)".
        1 Warning(s)
        0 Error(s)
```

**What is the expected behavior?**

The link in *index.yml* should be passed through `encodeURIComponent`:

**index.yml**
```yml
- uid: 'mypackage!C#bar:method'
  summary: >-
    [C.x](xref:mypackage!C%23x:member)
```

* **Tool:** api-documenter
* **Tool Version:** 7.7.18
* **Node Version:** 10.17.0
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Windows 10

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #1840

### CODE REVIEW

File: apps/api-documenter/src/documenters/YamlDocumenter.ts [hunk 1]
```diff
@@ -666,7 +666,7 @@ export class YamlDocumenter {
       onGetFilenameForApiItem: (apiItem: ApiItem) => {
         // NOTE: GitHub's markdown renderer does not resolve relative hyperlinks correctly
         // unless they start with "./" or "../".
-        return `xref:${this._getUid(apiItem)}`;
+        return `xref:${this._getUid(apiItem).replace(/[#?]/g, s => encodeURIComponent(s))}`;
```
Comment (octogonz) [inline apps/api-documenter/src/documenters/YamlDocumenter.ts:669]: @rbuckton Why are you encoding ONLY the `#` character?  If the xref target is a URL, shouldn't the entire string be URL encoded?

For example, suppose my declaration reference is `Statistics#"total%"`.  Seems like maybe that should get encoded as `Statistics%23%22total%25%22`.

Comment (rbuckton) [reply apps/api-documenter/src/documenters/YamlDocumenter.ts:669]: That's a fair point. I'll update the commit.

Comment (octogonz) [reply apps/api-documenter/src/documenters/YamlDocumenter.ts:669]: Might be useful to consult the DocFX specs to see if they provide any guidance about this.  Or at least try some weird strings to confirm that they are decoding how we expect.  (Encoding/decoding is something that developers almost never get right.)
