### PR TITLE
[api-documenter/-extractor/-model] Support 'abstract' Modifier

### LINKED ISSUE #3661: [api-documenter] 'abstract' missing in "Methods" overview table's "Modifiers" column
## Summary

The "Methods" overview table of a class has a "Modifiers" column, but the `abstract` modifier does not appear in that column (other modifiers like `public` do).
A similar issue occurs with the "Classes" overview table of a package or namespace. This does not even have a "Modifiers" column (probably because the assumption is that all documented classes are `public`?), so you cannot see whether a class is abstract in the overview at all.
On the detail page of both method and class, the "Signature" section _does_ show the `abstract` modifier.

## Repro steps

As an example, use the most simple abstract class with an abstract method:

```typescript
/**
 * The Foo class.
 * @public
 */
export public abstract class Foo {
  /** The bar method. */
  abstract bar(): void;
}
```

  **Expected result:**

On the package or namespace overview page, you can see that `Foo` is an abstract class.
On `Foo`'s details page, in the "Methods" overview table, you can see that `bar()` is an abstract method.

  **Actual result:**

The `abstract` modifier of both the class and the method is only mentioned on their details page, in the "Signature" section.

## Details

The basic infrastructure to extract and generate Markdown for modifiers is there, but it is only used for other modifiers like `public` and `readonly`. It can easily be complemented for `abstract`.

I already have a local change working that adds `abstract` to the "Modifiers" column of the "Methods" overview table. For the "Classes" overview, I'd need advice whether to add a "Modifiers" column there, too, or (my preferred solution) to add a dedicated "Abstract Classes" overview table, because in an API, abstract classes are quite something different from a concrete class, sometimes closer to an interface.

I am aware that there are other output targets than Markdown, but did not yet have a look at these in the api-documenter code. They are probably affected and should be updated, too.

To access the `abstract` modifier of classes and methods, a minor change in _api-extractor_ / _api-extractor-model_ is needed, too.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | 7.19.14 |
| Operating system? | any |
| Documentation target? | Markdown |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.8.2 |
| Node.js version (`node -v`)? | 16.15.1 |

### PR DESCRIPTION
**Pull request by fwienber**
## Summary

Fixes #3661

Proposal implementation of issue #3661.

Fully supporting the `abstract` modifier in _api-documenter_ involves extending the model (_api-extractor-model_) and letting _api-extractor_ extract the information into the model.

Then, _api-documenter_ can check whether API items have the new ApiAbstractMixin and if the new `isAbstract` property is true, add the modifier to the output. On the fly, the order of modifiers has been slightly adjusted to match the required order in TypeScript syntax.

For abstract classes, instead of adding a "Modifier" column for just this one modifier, a dedicated table has been added, because as an API designer, I think of abstract classes as a third category in between interfaces and (non-abstract) classes. Like interfaces, they cannot be instantiated, but like classes, you can subclass them.

|                | use as type | subclass | instantiate |
-----------------|-------------|----------|-------------|
| interface      | ✅          | ❌       | ❌         |
| abstract class | ✅          | ✅       | ❌         |
| class          | ✅          | ✅       | ✅         |

## Details

There are separate commits for the changes in _api-extractor(-model)_ and _api-documenter_.
Adding a property to the model affects many generated `*.api.json` model files.

The last commit implements the second alternative mentioned in #3661: Instead of adding a "Modifiers" column to the "Classes" overview table, a separate table for "Abstract Classes" is added to the Markdown output.

Note that other output targets beyond Markdown are not yet handled explicitly. Please advise if there is anything left to do.

## How it was tested

Tests for the changes have been complemented in an existing test scenario (_api-extractor_) or added as a new one (_api-documenter_). A new API schema version has been added. (This also updates several `*.api.json` model files.)

A change log entry has been added.

### CODE REVIEW

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts [hunk 1]
```diff
@@ -502,6 +503,11 @@ export class MarkdownDocumenter {
   private _writePackageOrNamespaceTables(output: DocSection, apiContainer: ApiPackage | ApiNamespace): void {
     const configuration: TSDocConfiguration = this._tsdocConfiguration;
 
+    const abstractClassesTable: DocTable = new DocTable({
+      configuration,
+      headerTitles: ['Abstract Class', 'Description']
+    });
```
Comment (zelliott) [inline apps/api-documenter/src/documenters/MarkdownDocumenter.ts:509]: I'd probably prefer having a "Modifiers" column instead of a separate section for alignment with other API items that have modifiers. What do you think?

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts [hunk 2]
```diff
@@ -1057,6 +1072,14 @@ export class MarkdownDocumenter {
       }
     }
 
+    if (ApiAbstractMixin.isBaseClassOf(apiItem)) {
+      if (apiItem.isAbstract) {
+        section.appendNode(
+          new DocParagraph({ configuration }, [new DocCodeSpan({ configuration, code: 'abstract' })])
+        );
+      }
+    }
```
Comment (zelliott) [inline apps/api-documenter/src/documenters/MarkdownDocumenter.ts:1081]: I'm not sure whether it was intentional or not, but the order of listed modifiers was previously in alphabetical order. This breaks that - maybe we can show `abstract` first above the other modifiers to keep with alphabetical ordering?

**Review by zelliott — COMMENTED** [review]
Looks great! Two final comments;

* You'll want to bump the `.api.json` version in `DeserializerContext.ts`. See previous edits to that file for examples.
* It'd be great to have at least one test in `build-tests/` where `isAbstract` is `true`. If we already have one  - great - if not, let's add one.

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts (hunk 2 above)
Comment (fwienber) [reply apps/api-documenter/src/documenters/MarkdownDocumenter.ts:1081]: I didn't realize they were in alphabetical order, and I'm too not sure whether this was coincidence or intentional. If we keep the additional table at all (see above), of course we can keep the alphabetical order. But what would really be nice here would be a way to _configure_ the desired order in api-documenter.

File: libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+/**
+ * Mixin function for {@link (ApiAbstractMixin:interface)}.
+ *
+ * @param baseClass - The base class to be extended
+ * @returns A child class that extends baseClass, adding the {@link (ApiAbstractMixin:interface)}
+ * functionality.
+ *
+ * @public
+ */
+export function ApiAbstractMixin<TBaseClass extends IApiItemConstructor>(
```
[the remark this answers is not in the document]
Comment (fwienber) [reply libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts:55]: Good point, got to check this!

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts (hunk 1 above)
Comment (fwienber) [reply apps/api-documenter/src/documenters/MarkdownDocumenter.ts:509]: I wrote that as a side note in the issue:
> ...(my preferred solution) add a dedicated "Abstract Classes" overview table, because in an API, abstract classes are quite something different from a concrete class, sometimes closer to an interface.

As an API designer, I think of abstract classes as a third category in between interfaces and classes. Like interfaces, they cannot be instantiated, but like (non-abstract) classes, you can subclass them.

|                | defines type | subclass | instantiate |
-----------------|--------------|----------|-------------|
| interface      | ✅          | ❌       | ❌         |
| abstract class | ✅          | ✅       | ❌         |
| class          | ✅          | ✅       | ✅         |

File: libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (fwienber) [reply libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts:55]: This is somewhat hidden in the grammar, but very clear in this error message:

> TS1242: 'abstract' modifier can only appear on a class, method, or property declaration.

So only the mixin to `ApiProperty` is missing. I'm on it.

**Comment by fwienber** [comment]
Just FYI, I did not forget about this PR, but I'm busy with another project for a couple of days.

File: libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (fwienber) [reply libraries/api-extractor-model/src/mixins/ApiAbstractMixin.ts:55]: Please re-review! ;-)

**Comment by fwienber** [comment]
> * It'd be great to have at least one test in `build-tests/` where `isAbstract` is `true`. If we already have one  - great - if not, let's add one.

There already was an abstract class with an abstract method, now resulting in an `"isAbstract": true` entry in the [expected API JSON](https://github.com/fwienber/rushstack/blob/c4c0d53c79d1e4e90f15756facb3deb8a254d765/build-tests/api-extractor-scenarios/etc/apiItemKinds/api-extractor-scenarios.api.json#L175-L223).
Do you think we need to complement test data for an abstract property?

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts (hunk 2 above)
Comment (fwienber) [reply apps/api-documenter/src/documenters/MarkdownDocumenter.ts:1081]: I thought about that and have the following suggestion: Wouldn't it make sense to use the modifier order that would be correct in TypeScript code? Unlike other languages like Java, in TypeScript, the order of modifiers is defined strictly, and unfortunately, it is not alphabetical order. In that sense, the current order is already wrong. It seems the correct order is

> (`public` | `protected` | `private`)? (`static`? | `abstract`?) `override`? `readonly`?

(No member can be `static` and `abstract` at the same time, so the order of these two does not matter.)
_api-documenter_ currently only uses `protected`, `static`, `abstract` (new in this PR) and `readonly`, so `public` (default!), `private` (no API!) and `override` (maybe interesting for navigation, but not as a modifier) do not apply.

I'll add a commit changing that and then we can see whether we keep it that way.

Comment (fwienber) [reply apps/api-documenter/src/documenters/MarkdownDocumenter.ts:1081]: Btw., in my first comment, I misunderstood you were referring to the order of _member tables_, not to the order of modifiers. So now that I realized what you meant, we still need to discuss whether to add an "Abstact Classes" table at all and if so, where / in what order.

**Comment by fwienber** [comment]
I guess I now addressed all review issues and thus resolved the conversations above. @zelliott, please re-review and of course feel free to re-open the resolved conversation to comment!

**Comment by fwienber** [comment]
If you don't like the merge commit that resolves the conflict with "main", I can also rebase my branch, but didn't want to do so while there are comments on the commits that would be lost when force-pushing the rebased branch.

**Comment by fwienber** [comment]
I had a bit more time and added more tests:
- added an abstract property to api-extractor-scenarios
- added an abstract class with an abstract method & property to api-documentor-scenarios

Diff in regenerated report files looks good.

**Comment by fwienber** [comment]
ping

**Comment by zelliott** [comment]
Hoping to take a look this weekend!

File: apps/api-documenter/src/documenters/MarkdownDocumenter.ts (hunk 2 above)
Comment (zelliott) [reply apps/api-documenter/src/documenters/MarkdownDocumenter.ts]: > I thought about that and have the following suggestion: Wouldn't it make sense to use the modifier order that would be correct in TypeScript code?

Interesting idea - I think either this or alphabetical both make sense!

**Comment by zelliott** [comment]
> There already was an abstract class with an abstract method, now resulting in an "isAbstract": true entry in the [expected API JSON](https://github.com/fwienber/rushstack/blob/c4c0d53c79d1e4e90f15756facb3deb8a254d765/build-tests/api-extractor-scenarios/etc/apiItemKinds/api-extractor-scenarios.api.json#L175-L223).
Do you think we need to complement test data for an abstract property?

No, I think that's good enough then. Thanks for checking!

**Review by zelliott — APPROVED** [review]
Sorry for the very long delay, have been busy with other work (as we all are!). LGTM!

File: build-tests/api-documenter-scenarios/src/inheritedMembers/index.ts [hunk 4]
```diff
@@ -124,3 +124,14 @@ export interface IExtendsInterfaceLikeTypeAlias extends IInterfaceLikeTypeAlias,
...
+/**
+ * Some abstract class with abstract members.
+ * @public
+ */
+export abstract class AbstractClass {
+  /** Some abstract method. */
+  public abstract method(): void;
+  /** Some abstract property. */
+  protected abstract property: number;
+}
```
[the remark this answers is not in the document]
Comment (fwienber) [reply build-tests/api-documenter-scenarios/src/inheritedMembers/index.ts]: Okay, I moved the test to api-documenter-test and force-pushed the branch.

**Comment by fwienber** [comment]
@zelliott Sorry, this time I missed the notification, then was out of office last week.
I moved the test (last unresolved conversation) as you recommended.
Next step is to find a code owner for review?

**Comment by zelliott** [comment]
> @zelliott Sorry, this time I missed the notification, then was out of office last week. I moved the test (last unresolved conversation) as you recommended. Next step is to find a code owner for review?

Yep! LGTM

**Comment by fwienber** [comment]
So how is the process here? Are the four mentioned code owners supposed to notice that this PR is ready for review, or do I have to ping (any of) them?

**Comment by zelliott** [comment]
I don't think there's any well defined process unfortunately, @octogonz to correct me otherwise. I typically ping @octogonz over Zulip chat or on the PR itself.

**Comment by fwienber** [comment]
Okay, magic spell "ping @octogonz" 🧞

**Comment by octogonz** [comment]
Sorry I overlooked this PR! 😅 (In the future, you can ping me personally on Zulip if needed.)

**Review by octogonz — APPROVED** [review]
