### PR TITLE
[rush] Copy over package binaries during deploy

### LINKED ISSUE #1982: [rush] rush deploy does not copy over package binaries
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

When executing `package.json` `scripts`, the underlying binary cannot be found because the `.bin` folder has not been copied (which I think is where `npm` looks for binaries)

example stack trace trying to call `knex`

```
/opt/deploy/apps/api $ npm run db:migrate:prod

> api@0.0.1 db:migrate:prod /opt/deploy/apps/api
> knex migrate:latest --verbose

sh: knex: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! api@0.0.1 db:migrate:prod: `knex migrate:latest --verbose`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the api@0.0.1 db:migrate:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

1. Install any package that also installs a binary (eslint or prettier are both good choices). 
2. Create a `package.json` `script` that calls the binary. For example, create a script called `prettier` with the following content: `prettier src/**/* --write`
3. Confirm that `npm run prettier` and/or `rushx prettier` works while inside the app directly.
4. `rush build` && `rush deploy`
5. `cd common/deploy/apps/api` and run `npm run prettier` or `rushx prettier` 

From gitter, [this is how `rush install` does it](https://github.com/microsoft/rushstack/blob/040dc7ae65fb0102345570a967e5d490b4c166c3/apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts#L284)

**What is the expected behavior?**

Packages that install binaries should be included / symlinked / copied during the deploy process.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** pnpm
* **Tool Version:** 5.2.6
* **Node Version:** 12.16.3
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** MacOS and Alpine linux

### PR DESCRIPTION
**Pull request by willsoto**
I’ve implemented most of what was recommended in the issue, but I’m not sure where to write the tests. 

I also haven’t implemented this for the `script` linking. I want to make sure I’m headed in the right direction.

Closes #1982

### CODE REVIEW

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 1]
```diff
@@ -461,9 +473,16 @@ export class DeployManager {
     const deployMetadataJson: IDeployMetadataJson = {
       scenarioName: path.basename(deployState.scenarioFilePath),
       mainProjectName: deployState.mainProjectName,
+      projects: [],
       links: []
     };
 
+    deployState.folderInfosByPath.forEach((folderInfo) => {
```
Comment (octogonz) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:480]: This is including too many projects. It should include only the ones where [IDeployState.folderInfosByPath](https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/logic/deploy/DeployManager.ts#L99) has `isRushProject=true`.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 2]
```diff
@@ -479,7 +498,19 @@ export class DeployManager {
     });
   }
 
-  private _prepareDeployment(deployState: IDeployState): void {
+  private async _makeBinLinks(deployState: IDeployState) {
+    for (const [, folderInfo] of deployState.folderInfosByPath) {
+      const deployedPath = this._remapPathForDeployMetadata(folderInfo.folderPath, deployState);
+      const projectFolder: string = path.join(deployedPath, 'node_modules');
+      const projectBinFolder: string = path.join(deployedPath, 'node_modules', '.bin');
```
Comment (octogonz) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:505]: These need to be absolute paths, like this:

```ts
      const projectFolder: string = path.join(deployState.targetRootFolder, deployedPath, 'node_modules');
      const projectBinFolder: string = path.join(deployState.targetRootFolder, deployedPath, 'node_modules', '.bin');
```

Otherwise `pnpmLinkBins()` (frustratingly) silently does nothing at all.

BTW there's some tips for debugging Rush [on this page](https://rushjs.io/pages/contributing/).

**Comment by octogonz** [comment]
I added a couple comments, but otherwise this is on the right track. 👍

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 2 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts]: With the above fix, the binaries are created and work correctly.

**Comment by willsoto** [comment]
Awesome. I’ll wrap this up tomorrow then. Thanks for the feedback.

**Comment by willsoto** [comment]
@octogonz one question I do have is how to link the bins in `create-links.js`. I noticed this comment at the top: 

https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/scripts/create-links.ts#L11-L12

In the `default` mode I am using `@pnpm/link-bins`, so is the expectation I do the same here? Do I inline the work with credit to the package? Other suggestions?

**Comment by octogonz** [comment]
> @octogonz one question I do have is how to link the bins in `create-links.js`. I noticed this comment at the top:
> 
> https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/scripts/create-links.ts#L11-L12
> 
> In the `default` mode I am using `@pnpm/link-bins`, so is the expectation I do the same here? Do I inline the work with credit to the package? Other suggestions?

Hmm.. That is a hitch that I had not considered. Inlining probably won't work because that package has numerous dependencies. Maybe we need to copy+transform the PNPM output here.

Did you investigate step 5 from https://github.com/microsoft/rushstack/issues/1982#issuecomment-653223979 yet? That seems related.

**Comment by willsoto** [comment]
> 
> 
> > @octogonz one question I do have is how to link the bins in `create-links.js`. I noticed this comment at the top:
> > https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/scripts/create-links.ts#L11-L12
> > 
> > In the `default` mode I am using `@pnpm/link-bins`, so is the expectation I do the same here? Do I inline the work with credit to the package? Other suggestions?
> 
> Hmm.. That is a hitch that I had not considered. Inlining probably won't work because that package has numerous dependencies. Maybe we need to copy+transform the PNPM output here.
> 
> Did you investigate step 5 from [#1982 (comment)](https://github.com/microsoft/rushstack/issues/1982#issuecomment-653223979) yet? That seems related.

I haven't investigated step 5 yet, I was about to when I noticed that comment. I'll test it out

**Comment by octogonz** [comment]
BTW if it turns out we need to change our approach, and that the PR so far is sufficient to solve your own case, I would be okay with merging+publishing a partial solution in the interim.

**Comment by willsoto** [comment]
@octogonz this works for my use case. Only `default` strategy is supported for the reason above. 

I also created a changelog [here](https://github.com/microsoft/rushstack/pull/2010/commits/54e73d9eb4840d6bdb153adb61215e962b7a6ea8). I did it cause CI was failing on that task. If you prefer to create the entry yourself, please feel free.

**Comment by octogonz** [comment]
> this works for my use case in docker. Only `default` strategy is supported for the reason above.

@willsoto To clarify, you're done working on this PR for now, and it is ready for final merging/reviewing. The cases we didn't handle should occur in a later PR.  Is that right?

**Comment by willsoto** [comment]
@octogonz that is correct. I am not sure how to resolve the "no external dependencies" problem for the script at the moment

**Comment by octogonz** [comment]
> I am not sure how to resolve the "no external dependencies" problem for the script at the moment

I'm thinking it will maybe require a fundamentally different approach. Either:
1. Make our own lightweight reimplementation of the `@pnpm/link-bins` algorithm; OR
2. Read the files that PNPM installed in `apps\api-extractor\node_modules\.bin\*`, apply some RegExp's to transform their contents, and write the result into `deploy\apps\api-extractor\node_modules\.bin\*`.

I don't want to block this PR behind that, however.

**Comment by willsoto** [comment]
> 
> 
> > I am not sure how to resolve the "no external dependencies" problem for the script at the moment
> 
> I'm thinking it will maybe require a fundamentally different approach. Either:
> 
>     1. Make our own lightweight reimplementation of the `@pnpm/link-bins` algorithm; OR
> 
>     2. Read the files that PNPM installed in `apps\api-extractor\node_modules\.bin\*`, apply some RegExp's to transform their contents, and write the result into `deploy\apps\api-extractor\node_modules\.bin\*`.
> 
> 
> I don't want to block this PR behind that, however.

Agreed. This PR is done from my perspective then unless I forgot something.

**Comment by octogonz** [comment]
This fix was released with Rush 5.29.0

**Comment by ujwal-setlur** [comment]
@willsoto @octogonz, this does not work when ```linkCreation: "script"```. It works when ```linkCreation: "default"```. Is that expected? Do I need to edit ```deploy-metadata.json``` manually before creating links?

**Comment by octogonz** [comment]
> this does not work when `linkCreation: "script"`. It works when `linkCreation: "default"`. Is that expected? Do I need to edit `deploy-metadata.json` manually before creating links?

@ujwal-setlur looks like this problem is now tracked by https://github.com/microsoft/rushstack/issues/2846

**Comment by ujwal-setlur** [comment]
@octogonz thank you!
