### PR TITLE
[node-core-library] Remove the copyFileToManyAsync API

### LINKED ISSUE #2724: [heft] CopyFilesPlugin sometimes writes 0-length files
## Summary

I can't repro it consistently, but today I encountered some intermittent failures in a project where the `CopyFilesPlugin` is supposed to copy exactly one `.json` file into the `lib-commonjs` folder.  What happens is that sometimes we end up with a 0-length file, which causes downstream Jest tests to fail when they import the JSON file.

## Details

I suspect that the problem is in this API:

https://github.com/microsoft/rushstack/blob/a13865bef9a20dab28c044be3504c7326bfe94b1/libraries/node-core-library/src/FileSystem.ts#L946-L1006

It has a special case when the target folder does not exist, where it intercepts the folder-not-found error and then calls `FileSystem.ensureFolder()` before retrying the operation.

@dmichon-msft pointed out that it is probably incorrect to pipe a Node.js stream to multiple destinations.

[Stack Overflow: Node.js Piping the same readable stream](https://stackoverflow.com/questions/19553837/node-js-piping-the-same-readable-stream-into-multiple-writable-targets) seems to agree.  That discussion has conflicting opinions, but someone recommends the [readable-stream-clone](https://www.npmjs.com/package/readable-stream-clone) NPM package which at least suggests that the problem is nontrivial.

CC @iclanton 

CC @elliot-nelson @hbo-iecheruo (FYI the failure was in `@hbo/hbomax-localization-policy-config`)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.31.1 |
| Operating system? |  Windows|
| Node.js version (`node -v`)? | 12.20.1 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Fixes #2724

An investigation performed by @octogonz in #2724 has led to the likely conclusion that reading/writing to multiple streams is likely the culprit causing 0-length files. Additionally, the API itself likely provided little real-world benefit given that it relies on the Node Stream APIs, while the actual file copy APIs use libuv. Given these, it seemed best to just remove the broken `copyFileToManyAsync` API and replace it with parallelized calls to `copyFileAsync` in the `CopyFilesPlugin`.

## Details

- Removed the `copyFileToManyAsync` API completely due to the broken state
- Replaced usage with a combination of `Async.forEachAsync` and `FileSystem.copyFileAsync` in `CopyFilesPlugin`.

## How it was tested

Ran rebuild in projects using the plugin to confirm that the copy files plugin was continuing to copy static assets as expected.

### CODE REVIEW

File: apps/heft/src/plugins/CopyFilesPlugin.ts [hunk 1]
```diff
@@ -160,35 +160,19 @@ export class CopyFilesPlugin implements IHeftPlugin {
...
-                linkTargetPath: copyDescriptor.sourceFilePath,
-                newLinkPath: destinationFilePath,
-                alreadyExistsBehavior: AlreadyExistsBehavior.Overwrite
-              });
-            }
-          );
-          await Promise.all(hardlinkPromises);
-
           linkedFileCount++;
+          return FileSystem.createHardLinkAsync({
```
Comment (iclanton) [inline apps/heft/src/plugins/CopyFilesPlugin.ts:164]:
```suggestion
          await FileSystem.createHardLinkAsync({
```

Otherwise, the stacktrace on an error won't show this line.

File: apps/heft/src/plugins/CopyFilesPlugin.ts [hunk 2]
```diff
@@ -160,35 +160,19 @@ export class CopyFilesPlugin implements IHeftPlugin {
...
-          } else {
-            await FileSystem.copyFileToManyAsync({
-              sourcePath: copyDescriptor.sourceFilePath,
-              destinationPaths: copyDescriptor.destinationFilePaths,
-              alreadyExistsBehavior: AlreadyExistsBehavior.Overwrite
-            });
-          }
-
           copiedFileCount++;
+          return FileSystem.copyFileAsync({
```
Comment (iclanton) [inline apps/heft/src/plugins/CopyFilesPlugin.ts:171]:
```suggestion
          await FileSystem.copyFileAsync({
```

File: common/changes/@rushstack/node-core-library/user-danade-DeprecateCopyFilesToMany_2021-06-04-18-11.json [hunk 3]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/node-core-library",
+      "comment": "Deprecate copyFileToManyAsync API. It was determined that this API was a likely source of 0-length file copies. Recommended replacement is to call copyFileAsync.",
```
Comment (iclanton) [inline common/changes/@rushstack/node-core-library/user-danade-DeprecateCopyFilesToMany_2021-06-04-18-11.json:5]:
```suggestion
      "comment": "(BREAKING CHANGE) Remove FileSystem.copyFileToManyAsync API. It was determined that this API was a likely source of 0-length file copies. Recommended replacement is to call copyFileAsync.",
```

**Review by iclanton — APPROVED** [review]

**Comment by octogonz** [comment]
Thank you for fixing this!

**Comment by octogonz** [comment]
Published with `@rushstack/node-core-library` 3.39.0 and `@rushstack/heft` 0.31.4
