### PR TITLE
[Heft] Reorganize lifecycle operation runner and support watch-mode cleaning

### LINKED ISSUE #4228: [heft] No `--clean` in watch mode?
Seems like the 0.51 release removed `--clean` from watch mode? I think there would still be value in starting from clean slate?

```
$ pnpm heft build --clean
 ---- lifecycle started ---- 
 ---- build started ---- 
[build:clean] Deleted 0 files and 2 folders
[build:typescript] Using TypeScript version 5.0.4
[build:lint] Using ESLint version 8.40.0
 ---- build finished (19.620s) ---- 
 ---- lifecycle finished (19.622s) ---- 
-------------------- Finished (19.623s) --------------------
```

```
$ pnpm heft build-watch --clean
usage: heft build-watch [-h] [-v] [--production] [--locales LOCALE] [--serve]
heft build-watch: error: Unrecognized arguments: --clean.
```

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.56.1 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

This PR does two things:
- Moves lifecycle cleaning to it's own operation, instead of piggybacking on the existing `start` lifecycle operation
- Adds support for the `--clean` flag in `heft *-watch` commands

Fixes #4228

## Details

Cleaning in watch mode is now performed only during the first-pass of the watch-mode operations. Once the clean has been completed, the clean will be ignored until the command is restarted. This allows starting from a fresh state during watch mode

## How it was tested

Tested locally using `heft build`, `heft build --clean`, `heft build-watch` and `heft build-watch --clean`

## Impacted documentation

Docs may need to be updated to indicate that `--clean` is now possible in watch mode.

### CODE REVIEW

File: apps/heft/src/plugins/CopyFilesPlugin.ts [hunk 1]
```diff
@@ -92,6 +95,7 @@ async function _getCopyDescriptorsAsync(
     async (copyConfiguration: ICopyOperation) => {
       // "sourcePath" is required to be a folder. To copy a single file, put the parent folder in "sourcePath"
       // and the filename in "includeGlobs"
+      copyConfiguration.sourcePath = path.resolve(rootFolderPath, copyConfiguration.sourcePath);
```
Comment (dmichon-msft) [inline apps/heft/src/plugins/CopyFilesPlugin.ts:98]: How was this working before? Some implicit resolution of paths, or because the sourcePath got resolved somewhere else?

**Review by dmichon-msft — APPROVED** [review]

File: apps/heft/src/plugins/CopyFilesPlugin.ts (hunk 1 above)
Comment (D4N14L) [reply apps/heft/src/plugins/CopyFilesPlugin.ts:98]: Yeah, I think it must have been implicitly resolving CWD to the `process.cwd` which is always the `buildFolderPath`
