### PR TITLE
[heft] Update file copy layer to support incremental disk cache

### LINKED ISSUE #4942: [heft] CopyFilesPlugin should only write files if the contents are different
## Summary
When running an incremental build (i.e. without `--clean`, not `-watch`), Heft's builtin file copy logic writes the output files 100% of the time. This causes performance issues for tools that watch the output files.

## Repro steps
In `heft.json` add a task that copies files:
```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/heft/v0/heft.schema.json",

  "phasesByName": {
    "build": {
      "cleanFiles": [{ "includeGlobs": ["dist"] }],

      "tasksByName": {
        "copy-files": {
          "taskPlugin": {
            "pluginPackage": "@rushstack/heft",
            "pluginName": "copy-files-plugin",
            "options": {
              "copyOperations": [
                {
                  "sourcePath": "src",
                  "destinationFolders": ["dist"],
                  "includeGlobs": [
                    "*.txt"
                  ]
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

Run `heft build`, then, with a file watcher in place on the files in `dist`, run `heft build` again. 

  **Expected result:** 
No file write events should fire.

  **Actual result:**  Observe that the output files are modified despite the inputs not changing.

## Details

Recommendation is to either read the destination file and only write if changed, or to do as TypeScript (and other tools) do and write a cache file to the current task's temp folder that lists the last emitted versions of the input files.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.67.2 |
| Operating system? | All |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.19.1 |

### PR DESCRIPTION
**Pull request by dmichon-msft**
## Summary
Fixes #4942

Updates the underlying logic in Heft's `copy-files-plugin` to write an incremental cache file, that will be used to only copy files where the inputs have changed. This also impacts the file copy in `heft-typescript-plugin`.

Adds a new API to read and write incremental cache files, for use by other plugins.

## Details
Incremental cache files store a config hash, a list of input files with SHA-256 hashes, and optionally a mapping from output file names to indices of input files.

Each task will get its own unique `file-copy.json` cache file in the task's temp folder if there are a non-zero number of copy operations configured for the task.

## How it was tested
Using `build-tests/heft-copy-files-plugin`.

## Impacted documentation
Copy files.

### CODE REVIEW

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+  configHash: string;
+
+  /**
+   * A map of input files to their version strings.
+   * File paths are specified relative to the folder containing the build info file.
+   */
+  inputFileVersions: Record<string, string>;
+
+  /**
+   * Map of output file names to the input file indices used to compute them.
```
Comment (iclanton) [inline apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:49]: What is this indexed into?

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+      const indices: number[] = [];
+      for (const dependency of dependencies) {
+        const index: number | undefined = fileIndices.get(dependency);
+        if (index === undefined) {
+          throw new Error(`Dependency not found: ${dependency}`);
+        }
+        indices.push(index);
+      }
+
+      fileDependencies[relativePath] = indices.length === 1 ? indices[0] : indices;
```
Comment (iclanton) [inline apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:90]: Why not just always have this be an array? Easier to parse and serialize, and probably a trivial file size increase.

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+}
+
+/**
+ * Reads a build info object from disk.
+ * @param filePath - The file path to read the build info from
+ * @returns The build info object, or undefined if the file does not exist or cannot be parsed
+ * @beta
+ */
+export async function tryReadBuildInfoAsync(filePath: string): Promise<IIncrementalBuildInfo | undefined> {
+  let serializedBuildInfo: ISerializedIncrementalBuildInfo | undefined;
```
Comment (iclanton) [inline apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:177]:
```suggestion
  let serializedBuildInfo: ISerializedIncrementalBuildInfo;
```

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+ * @beta
+ */
+export async function writeBuildInfoAsync(state: IIncrementalBuildInfo, filePath: string): Promise<void> {
+  const basePath: string = path.dirname(filePath);
+
+  const serializedBuildInfo: ISerializedIncrementalBuildInfo = serializeBuildInfo(
+    state,
+    (absolutePath: string) => {
+      return Path.convertToSlashes(path.relative(basePath, absolutePath));
+    }
```
Comment (iclanton) [inline apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:161]: When would this ever be anything else?

**Review by iclanton — APPROVED** [review]

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts (hunk 4 above)
Comment (dmichon-msft) [reply apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:161]: On Win32 the absolute path will have backslashes, but I can optimize to skip that call when not on Win32.

Comment (dmichon-msft) [reply apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:161]: The reason this is separated out is so that I can do cross-platform unit testing.

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts (hunk 3 above)
Comment (dmichon-msft) [reply apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:177]: Strict null checks says this is the correct type.

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts (hunk 1 above)
Comment (dmichon-msft) [reply apps/heft/src/pluginFramework/IncrementalBuildInfo.ts:49]: Updated comment.

File: apps/heft/src/pluginFramework/IncrementalBuildInfo.ts (hunk 2 above)
Comment (dmichon-msft) [reply apps/heft/src/pluginFramework/IncrementalBuildInfo.ts]: TypeScript had done it this way, I assume they had their reasons, likely related to memory usage, but we can use a simpler model, sure.
