### PR TITLE
Normalize chmod field in Tar header

### LINKED ISSUE #1804: [rush] tgz files in common/temp/projects different based on platform
[RUSH]
**Is this a feature or a bug?**

- [ ] Feature
- [ x] Bug

On MacOS the tgz files produced are different than the tgz files produced on Linux. This leads to PNPM throwing an error because the sha512 is different when you push a commit from MacOS and then the project starts in a Linux based CI system. 

https://github.com/microsoft/rushstack/blob/82476f4983b7bbd0ed56c7acce4ebbf450a9bad9/apps/rush-lib/src/logic/InstallManager.ts#L743

The portable option is used, but in a later release in the tar package, it is updated to ensure that when gzip is used it also is safe across platforms. 

https://github.com/npm/node-tar/blob/master/CHANGELOG.md#50

Gzip needs to have this option set in order to create portable tgz files. 

**Reproduction:**
If using pnpm 4.12.1 as I am
To reproduce you need a rush repo and two platforms. MacOS and Linux. 

If using pnpm 4.12.1 as I am
1) Run `rush update --full` on one platform and make sure all files are committed. 
2) Run `rush update --full` on the other platform on the same commit SHA as Step 1. 
3) Run `git diff` and you will see that only the sha512 of the files in common/temp/projects has changed in `config/rush/pnpm-lock.yaml`, even though no package.json has changed. 

If not using pnpm... 
1) Run `rush update --full` on one platform
2) Get the MD5 or SHA hash of a tgz file in common/temp/projects
3) Run `rush update -full` on the same commit SHA on the other platform
4) Get the MD5 or SHA hash of a tgz file in common/temp/projects from the second platform. 

The MD5 or SHA hash of the tgz files should be the same... but will be different. 

**Expected Behavior: **
If I am on any platform and run `rush update --full` and I have not changed a package.json, then the sha512 sum for the local package should not change. 

* **Tool: RUSH** 
* **Tool Version: 5.22.0** 
* **Node Version: 12.16.1** 
* **OS: MacOS Catalina / Linux Ubuntu 18.04**

### PR DESCRIPTION
**Pull request by sachinjoseph**
FIxes #1804

### CODE REVIEW

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 1]
```diff
@@ -811,6 +815,41 @@ export class InstallManager {
     return shrinkwrapIsUpToDate;
   }
 
+  private _normalizeChmodFieldInTarHeader(tarballFile: string): void {
+    const buffer: Buffer = FileSystem.readFileToBuffer(tarballFile);
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/InstallManager.ts:819]: Can we use a mechanism that doesn't read the entire file into memory? It may have utility in other places, even if we know that all the files we will be manipulating here are small.

File: apps/rush-lib/src/schemas/rush.schema.json [hunk 2]
```diff
@@ -68,6 +68,10 @@
       "description": "If true, consistent version specifiers for dependencies will be enforced (i.e. \"rush check\" is run before some commands).",
       "type": "boolean"
     },
+    "normalizeChmodFieldInTarHeader": {
```
Comment (octogonz) [inline apps/rush-lib/src/schemas/rush.schema.json:71]: @sachinjoseph  Why is this optional?  It feels like a bug fix.

If we want to introduce it conservatively (e.g. "opt-in" or "opt-out") in case it causes problems, you can put the setting in `experiments.json` instead.

It seems like a relatively safe change, though.

Comment (sachinjoseph) [reply apps/rush-lib/src/schemas/rush.schema.json:71]: @octogonz  - that was my intention - to make this an opt-in until we are more confident. I will add it to experiments.json

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 3]
```diff
@@ -1286,14 +1325,22 @@ export class InstallManager {
       // last install flag, which encapsulates the entire installation
       args.push('--no-lock');
 
-      // Ensure that Rush's tarball dependencies get synchronized properly with the pnpm-lock.yaml file.
-      // See this GitHub issue: https://github.com/pnpm/pnpm/issues/1342
-      if (semver.gte(this._rushConfiguration.packageManagerToolVersion, '3.0.0')) {
-        args.push('--no-prefer-frozen-lockfile');
+      if (!this._options.allowShrinkwrapUpdates) {
```
Comment (sachinjoseph) [inline apps/rush-lib/src/logic/InstallManager.ts:1328]: I will take the '--frozen-lockfile' into a separate PR.

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 4]
```diff
@@ -737,7 +737,7 @@ export class InstallManager {
 
           // create the new tarball
           tar.create({
-            gzip: true,
+            gzip: false,
             file: tarballFile,
             cwd: tempProjectFolder,
             portable: true,
```
Comment (octogonz) [inline apps/rush-lib/src/logic/InstallManager.ts:743]: Isn't `portable: true` already supposed to ensure the file is portable between OS's?  If it's not working, that seems like a bug in the `tar` library that we could fix directly.

It seems brittle to approach the problem by:  reading a file from disk, and monkeying with its bits, recalculating the checksum, and then overwriting the original input file (which is not an idempotent operation).

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: The tarball is portable across platforms when `portable: true` is set, but the chmod flags aren't exactly the same. PNPM treats this as a hash mismatch - now maybe the fix could be in node-tar or maybe PNPM could ignore chmod-bits in the tar header while it calculates the hash?

Comment (octogonz) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: This is how `tar` reads the file permissions:

[node-tar/lib/pack.js](https://github.com/npm/node-tar/blob/114efef625f3fe82f7afec838b50982867619130/lib/pack.js#L178)
```ts
  [ONSTAT] (job, stat) {
    this.statCache.set(job.absolute, stat)
    job.stat = stat

    // now we have the stat, we can filter it.
    if (!this.filter(job.path, stat))
      job.ignore = true

    this[PROCESS]()
  }
```

The `filter` callback is an option for `tar.create()`, and its unrigorous API design enables the caller to tamper directly with the `stat` object from the cache.  We could exploit that to directly modify the `stat.mode` field.  (It feels a little sloppy, but arguably that is the API contract that they designed heheh.)

Or if you want to be slightly more paranoid, the `statCache` [is also exposed](https://github.com/npm/node-tar/blob/114efef625f3fe82f7afec838b50982867619130/README.md#tarcoptions-filelist-callback-alias-tarcreate) as an API option:

> The following options are mostly internal, but can be modified in some
> advanced use cases, such as re-using caches between runs.
>
> - `linkCache` A Map object containing the device and inode value for
>  any file whose nlink is > 1, to identify hard links.
> - `statCache` A Map object that caches calls `lstat`.

So another idea would be to create a `statCache` with an entry for the `package.json` file before invoking `tar.create()`.

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: Hmm - I like that. If that works then I can avoid having to manually modify the header bytes.

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: Filter in tar.create isn't working for mode. I have pushed the code here if you want to take a look: https://github.com/microsoft/rushstack/tree/sachinjoseph/normalizeChmodInTarHeaderUsingFilter

Comment (octogonz) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: @sachinjoseph `755` is the octal representation.  Whereas this code is specifying a decimal integer.

Comment (octogonz) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: Use `PosixModeBits` to specify the correct number.

Comment (octogonz) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: The actual value that I saw in the debugger is `33206` decimal which is `100666` octal.  This corresponds to:

`100000` = [S_IFREG](https://github.com/nodejs/node/blob/master/doc/api/fs.md#file-type-constants)  regular file
`666` = read+write for user+group+other

If the file type bits are incorrect, then the `tar` library malfunctions.  So you might want to leave the extra bits alone, something like this:
```ts
stat.mode = (stat.mode & ~0x1FF) | PosixModeBits.AllRead;
```

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: Ah, my bad. Let me quickly see if changing it to octal works.

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: @octogonz I have updated the PR

File: apps/rush-lib/src/logic/InstallManager.ts (hunk 1 above)
Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts]: Resolving this as we now no longer read the file

File: apps/rush-lib/src/logic/InstallManager.ts (hunk 4 above)
Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:743]: And, good point about the file type bit. I did run into when using the filter function but not when I was manually modifying raw the header bytes.

File: common/changes/@microsoft/rush/sachinjoseph-normalizeChmodInTarHeader_2020-04-07-18-34.json [hunk 5]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Normalize chmod field in Tar header",
```
Comment (octogonz) [inline common/changes/@microsoft/rush/sachinjoseph-normalizeChmodInTarHeader_2020-04-07-18-34.json:5]:
```suggestion
      "comment": "Fix an issue where the common/temp/*.tgz files resulted in different shrinkwrap files on different operating systems",
```

File: apps/rush-lib/src/api/ExperimentsConfiguration.ts [hunk 6]
```diff
@@ -19,6 +19,12 @@ export interface IExperimentsJson {
    * instead of project-specific tracking.
    */
   legacyIncrementalBuildDependencyDetection?: boolean;
+
+  /**
+   * If true, the chmod field in temporary project tarballs will be set to 755.
+   * This can help ensure consistent tarball integrity across platforms..
+   */
+  normalizeChmodFieldInTarHeader?: boolean;
```
Comment (octogonz) [inline apps/rush-lib/src/api/ExperimentsConfiguration.ts:27]: Also add it to `rush-lib\assets\rush-init\common\config\rush\experiments.json` and the corresponding `experiments.schema.json`.

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 7]
```diff
@@ -737,18 +737,29 @@ export class InstallManager {
...
             noMtime: true,
             noPax: true,
             sync: true,
-            prefix: npmPackageFolder
+            prefix: npmPackageFolder,
+            filter: (path: string, stat: tar.FileStat): boolean => {
+              if (this._rushConfiguration.experimentsConfiguration.configuration
+                .normalizeChmodFieldInTarHeader) {
```
Comment (octogonz) [inline apps/rush-lib/src/logic/InstallManager.ts:750]: Should `normalizeChmodFieldInTarHeader` default to `true` instead of `false`?  It seems like an important fix with minimal fix.

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 8]
```diff
@@ -737,18 +737,29 @@ export class InstallManager {
 
           // create the new tarball
           tar.create({
-            gzip: true,
+            gzip: false,
```
Comment (octogonz) [inline apps/rush-lib/src/logic/InstallManager.ts:740]: I feel like we need `gzip: true` because the file extension is `.tgz`.

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 9]
```diff
@@ -744,11 +744,22 @@ export class InstallManager {
...
+              if (!this._rushConfiguration.experimentsConfiguration.configuration
+                .noChmodFieldInTarHeaderNormalization) {
+
+                stat.mode = (stat.mode & ~0x1FF) | PosixModeBits.AllRead | PosixModeBits.UserWrite
+                  | PosixModeBits.AllExecute;
+              }
+
+              return true;
+            }
           } as CreateOptions, [FileConstants.PackageJson]);
```
Comment (iclanton) [inline apps/rush-lib/src/logic/InstallManager.ts:758]: Can we remove this cast?

Comment (sachinjoseph) [reply apps/rush-lib/src/logic/InstallManager.ts:758]: I don't think we can.

```
/**
 * The "noMtime" flag is new in tar@4.4.1 and not available yet for \@types/tar.
 * As a temporary workaround, augment the type.
 */
import { CreateOptions } from 'tar';

```

Comment (octogonz) [reply apps/rush-lib/src/logic/InstallManager.ts:758]: Or just open a PR against `@types/tar`. Often such PRs get merged+published pretty fast.
