### PR TITLE
[rush] Add `--from` to `rush install`

### LINKED ISSUE #2434: [rush] Add `--from` to `rush install`
## Summary
It would be nice that now that we have `rush install --to myproject` is a thing, that we could also have `rush install --from myproject` support.

Specifically we realized we have a need for this as we approach similar solutions as described here: https://github.com/microsoft/rushstack/issues/2401

## Repro steps
`rush install --from myproject` is not a valid command.

`rush build --from myproject` is a valid command.

### PR DESCRIPTION
**Pull request by wbern**
My first real PR to rush, finally. ❤️ 

## Summary
I added support for `--from`-based installs using `rush install`, currently there is only support for `--to`, and the change was trivial to make, following pnpm workspaces documentation here: https://pnpm.js.org/en/filtering#filter-lt-package_name-

Fixes #2434

## Details

In my org, we want to install/build/test only the changed projects in our CI, which we are accomplishing with the `--to` flag. However, we see that if we change a widely used package, we want to build and test all the dependents of that package when it gets changed, and publish those packages as well. Hence we have a need for the `--from` flag for `rush install`, a flag already present in the other rush commands we use around building things.

## How it was tested

I created an alias called `testrush` locally on my machine and used in our biggest repo, I then did

`testrush install --to @org/my-lib`

I inspected the output being `Scope: 4 out of 124 workspace projects`,

then I ran `testrush install --to @org/my-lib --from @org/my-lib`

Which gave me the output of `Scope: 115 of 124 workspace projects`.

I also tested `testrush install --from @org/my-lib` which returned `Scope: 112 of 124 workspace projects`, so it adds up.

The output from the filtered install in this case is `pnpm install --filter ...@org/my-lib --filter @org/my-lib...`.

## Final notes

I know we're changing names of --from/--to to other things later, so open for suggestions how to merge this.

### CODE REVIEW

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts [hunk 1]
```diff
@@ -587,9 +587,14 @@ export class WorkspaceInstallManager extends BaseInstallManager {
       args.push('--recursive');
       args.push('--link-workspace-packages', 'false');
 
-      // "<package>..." selects the specified package and all direct and indirect dependencies
-      for (const toProject of this.options.toProjects) {
-        args.push('--filter', `${toProject.packageName}...`);
+      const filteredProjects: string[] = this.options.toProjects
```
Comment (D4N14L) [inline apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:590]: For ease of reading I would suggest just doing this as a separate for loop

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts [hunk 2]
```diff
@@ -587,9 +587,14 @@ export class WorkspaceInstallManager extends BaseInstallManager {
...
+        // "<package>..." selects the specified package and all direct and indirect dependencies
+        .map((p) => p.packageName + '...')
+        // ..."<package>" selects the specified package and all direct and indirect dependents of that package
+        .concat(this.options.fromProjects.map((p) => '...' + p.packageName));
```
Comment (D4N14L) [inline apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:594]: So, the original PR that brought this functionality in actually had this. I was talked out of it by @octogonz (though I think it may have been a Gitter discussion since I can't find it now...). Main reason it was removed was that I couldn't think of a great justification for how this would be used. So he's likely going to need some convincing :)

**Review by D4N14L — COMMENTED** [review]
Looks good functionally, small comment on syntax of filter creation logic, but leaving to someone else to approve.

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 1 above)
Comment (wbern) [reply apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: See changes, is this what you meant?

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 2 above)
Comment (wbern) [reply apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: Our justification is that in order to use the `rush build --from` flag, we need to also install the deps of those dependents coming up from the `--from` flag. If package A relies on B, we can't build A when B changes, if we don't install the dependencies for A via the `--from` flag.

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 1 above)
Comment (wbern) [reply apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: Done!

**Review by D4N14L — APPROVED** [review]
Signing off, but merge will likely be gated on @octogonz 

Thanks for your changes @wbern!

**Comment by iclanton** [comment]
@octogonz - do you have any concerns about this PR? Looks good to @D4N14L and me.

**Comment by octogonz** [comment]
The code looks fine.  There is a slightly interesting nuance in the design.  From the discussion about PR #2422, we said that:

- `rush build --to x` builds a transitive closure; whereas
- `rush build --from x` does NOT build a transitive closure, so we proposed that:  👈
- `rush build --from x --with-dependencies` will build the transitive closure

Whereas if I understand correctly:
- `rush install --to x` installs a transitive closure
- `rush install --from x` installs a transitive closure  👈

Would this inconsistency be confusing to anyone?  (And if so, would we rename `--from` for `rush install`?  Or would we redefine `--from` for `rush build`?)

CC @dmichon-msft

File: apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 2 above)
Comment (dmichon-msft) [reply apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: Regardless of whether or not upstream projects need to be built, there are plenty of instances where merely referencing the upstream project results in references to the `node_modules` of the upstream project, so it would not surprise me if, unlike in the `rush build` case (where the developer may be running it after an earlier `rush build`), `rush install --from` is completely unusable if it skips the dependencies of upstream local projects.

**Comment by wbern** [comment]
Honestly I think --from should include everything that's needed. As a colleague of mine said, to and from makes an hourglass, or at least so we thought at first. 🙂

**Comment by octogonz** [comment]
In https://github.com/microsoft/rushstack/pull/2422#issuecomment-769617366 we're proposing to use `--without-dependencies` rather than `--with-dependencies` for `rush build`.  So I think I'm good with this PR. 👍

**Comment by octogonz** [comment]
@wbern This was released with Rush 5.37.0
