### PR TITLE
fixed usage of deprecated webpack-dev-server api

### LINKED ISSUE #3421: [heft] webpack-5-rig throwing deprecation warnings via setting `https` and `onBeforeSetupMiddleware` properties for webpack-dev-server
Using the webpack-5-rig, it appears that some webpack-dev-server settings are being set using deprecated calls:

```
(node:6488) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
(node:6488) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option
```

This is coming from the usages here: 

https://github.com/microsoft/rushstack/blob/0e2502ea1e4aec2d0cbf912ed5712b8f05b0a551/heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts#L91-L97

and 

https://github.com/microsoft/rushstack/blob/0e2502ea1e4aec2d0cbf912ed5712b8f05b0a551/heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts#L199-L208

## Details

This can be fixed by updating `options.https` to: 

```
  server: {
    type: 'https',
    options: {
      cert: ...,
      key: ...,
    },
  },
```

and changing `onBeforeSetupMiddlwares` to `setupMiddlewares`
## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | latest |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14 |

### PR DESCRIPTION
**Pull request by TheLarkInn**
## Summary
Fixes #3421 
(one part of it)

## Details
This PR removes deprecation warnings thrown by webpack-dev-server when using the webpack-5-rig. This PR provides support for the DevCertPlugin to allow it to use both webpack-dev-server v3 and v4 API's.  

## How it was tested
I ran both the heft-webpack5-everything-test and heft-webpack4-everything-test and ensured that both dev servers launched successfully without any errors or deprecation warnings. (They both leverage the DevCertPlugin)

### CODE REVIEW

File: heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts [hunk 1]
```diff
@@ -71,30 +71,55 @@ export class DevCertPlugin implements IHeftPlugin {
...
+              logger,
+              this._determineMajorVersion(bundleSubstage.properties.webpackDevServerVersion)
             );
           });
         }
       });
     });
   }
 
+  private _determineMajorVersion(version?: string): number | undefined {
```
Comment (TheLarkInn) [inline heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts:83]: I'm not crazy about these means to simplify major version detection, so I'm open for improvements/suggestions here.

Comment (dmichon-msft) [reply heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts:83]: You could literally just do `parseInt(version)`, since `parseInt` allows for trailing non-digit values (and ignores them).

**Review by dmichon-msft — APPROVED** [review]

File: heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts (hunk 1 above)
Comment (TheLarkInn) [reply heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts:83]: Awesome, updated it to use parseInt instead.

**Review by dmichon-msft — APPROVED** [review]
