### PR TITLE
[rush-lib] Run post-install step on every call to `rush install` or `rush update`

### LINKED ISSUE #2288: [rush] "rush install" no longer recovers from "rush unlink"
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Repro steps:**  

In a Rush repo with `"useWorkspaces": false`, try these commands:

1. `rush install`
2. `rush unlink`
3. `rush install`

**What is the expected behavior?**

Step 3 should bring us back to a good state.

**What is the actual behavior?**

After Step 3, nothing is installed.  Running `rush build` prints:
```
ERROR: Link flag invalid.
Did you run "rush link"?
```

* **Tool:** Rush
* **Tool Version:** 5.34.2

### PR DESCRIPTION
**Pull request by D4N14L**
Fixes #2288 by moving the post-install `rush link` outside of the scope of the check for `last-install.flag`. We were skipping running linking if the install was still valid, causing `rush unlink` to break installs with no hope of recovery by calling `rush install` or `rush update`. Another option was to delete the `last-install.flag` when `rush unlink` is run, but this would unnecessarily force the package manager to be called. One more option would be to run post-install regardless of `last-install.flag` (as this change does) but conditionally run `rush link` only if the `last-link.flag` file is older than `last-install.flag`. However, linking is a lightweight operation so I decided against over-complicating the check.

Additionally, this PR fixes a bug introduced by #2286 wherein a dependency field in `pnpm-lock.yaml` is accessed when undefined.

### CODE REVIEW

**Comment by octogonz** [comment]
(FYI when I first read this, I assumed that "post-install step" meant the `"postInstall"` script in package.json.  Just to clarify, instead it is referring to `BaseInstallManager.postInstallAsync()` which is an internal Rush event that creates `rush link` symlinks under project folders.  Or, when `useWorkspaces=true` it instead writes the `shrinkwrap-deps.json` file.)

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 1]
```diff
@@ -243,16 +243,16 @@ export abstract class BaseInstallManager {
...
       // Create the marker file to indicate a successful install if it's not a filtered install
       if (!isFilteredInstall) {
         this._commonTempInstallFlag.create();
       }
-
-      console.log('');
     }
+
+    // Perform any post-install work the install manager requires
+    await this.postInstallAsync();
```
Comment (octogonz) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:253]: What happens if we run `rush link` twice in a row?

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
Thanks for fixing this!
