### PR TITLE
[API Extractor] Add missing required parameter for getResolvedModule to ensure that modules can resolve accurately with Node16/nodenext support

### LINKED ISSUE #3433: [api-extractor] crash when used with TS 4.7.2 moduleResolution Node16
## Summary

It seems that adding `moduleResolution` with a setting of `Node16` to the `tsconfig.json` file causes `@microsoft/api-extractor` to fail every time. The error is as follows:

```
ERROR: Internal Error: getResolvedModule() could not resolve module name "./foo/bar.js"
/Users/johndoe/Documents/code/myrepo/my-package/dist/dts/index.d.ts:1:1
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
error Command failed with exit code 1.
```

**This is blocking us from shipping our major new library versions.**

## Repro steps

I've got a branch that demonstrates the issue here: 

https://github.com/microsoft/fast/tree/users/eisenbergeffect/fast-element-utilities

Simply pull that down and run `yarn` in the root. You will see an error similar to the above.

## Details

I've tried many combinations of settings, but the only thing that seems to make the error go away is not using the `Node16` setting. Unfortunately, this is required for some of our packages since they leverage `package.json` `exports`. You can switch the `fast-element` package to `Node` to get it working but then you will observe the problem in `fast-foundation` (which requires `Node16` because it leverages package exports from `fast-element`).

I have discussed this briefly with a member of the TS team and they suspect that api-extractor may be using some undocumented APIs, specifically `getResolvedModule`.

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 7.24.1 |
| Operating system? | Mac |
| API Extractor scenario? | rollups (.d.ts)  |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.7.2 |
| Node.js version (`node -v`)? | 16.14.0 |

### PR DESCRIPTION
**Pull request by chrisdholt**
…ypescript can resolve accurately

## Summary
With the addition of `Node16` and `nodenext`, Typescript now requires the mode to be passed in order to accurately resolve modules. This PR adds support for `mode` thanks to the help of @DanielRosenwasser and does so in a way that returns undefined gracefully in case the fn isn't supported in older versions.

This resolves #3433.

## Details
1. Add a third param to getResolvedModule for `mode`
2. Create a new function `getModeForUsageLocation` which maps to the TS equivalent
3. Update all callers to gracefully look for the right mode and return undefined if necessary

## How it was tested
Tested locally with Typescript 4.7.2 and the error is gone, API Extractor succeeds.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
Woohoo! Let's get this in 😄 This is a critical fix needed for us to ship our FAST vNext packages.

File: apps/api-extractor/src/analyzer/TypeScriptInternals.ts [hunk 1]
```diff
@@ -83,12 +83,26 @@ export class TypeScriptInternals {
...
+   * Gets the mode required for module resolution required with the addition of Node16/nodenext
+   */
+  public static getModeForUsageLocation(
+    file: { impliedNodeFormat?: ts.SourceFile['impliedNodeFormat'] },
+    usage: ts.StringLiteralLike | undefined
+  ) {
+    // Compiler internal:
+    // https://github.com/microsoft/TypeScript/blob/v4.7.2/src/compiler/program.ts#L568
+
+    return (ts as any).getModeForUsageLocation(file, usage);
```
Comment (DanielRosenwasser) [inline apps/api-extractor/src/analyzer/TypeScriptInternals.ts:105]: This function might not exist in older versions. It should just return `undefined` if it doesn't have a value.

```suggestion
    return (ts as any).getModeForUsageLocation?.(file, usage);
```

File: apps/api-extractor/src/analyzer/TypeScriptInternals.ts [hunk 2]
```diff
@@ -83,12 +83,26 @@ export class TypeScriptInternals {
    */
   public static getResolvedModule(
     sourceFile: ts.SourceFile,
-    moduleNameText: string
+    moduleNameText: string,
+    mode: ts.StringLiteralLike | undefined
   ): ts.ResolvedModuleFull | undefined {
     // Compiler internal:
     // https://github.com/microsoft/TypeScript/blob/v3.2.2/src/compiler/utilities.ts#L218
```
Comment (DanielRosenwasser) [inline apps/api-extractor/src/analyzer/TypeScriptInternals.ts:90]:
```suggestion
    // https://github.com/microsoft/TypeScript/blob/v4.7.2/src/compiler/utilities.ts#L161
```

File: apps/api-extractor/src/analyzer/TypeScriptInternals.ts [hunk 3]
```diff
@@ -83,12 +83,26 @@ export class TypeScriptInternals {
    */
   public static getResolvedModule(
     sourceFile: ts.SourceFile,
-    moduleNameText: string
+    moduleNameText: string,
+    mode: ts.StringLiteralLike | undefined
```
Comment (DanielRosenwasser) [inline apps/api-extractor/src/analyzer/TypeScriptInternals.ts:87]:
```suggestion
    mode: ts.ModuleKind.CommonJS | ts.ModuleKind.ESNext | undefined
```

File: apps/api-extractor/src/analyzer/TypeScriptInternals.ts [hunk 4]
```diff
@@ -83,12 +83,26 @@ export class TypeScriptInternals {
...
+    return (ts as any).getResolvedModule(sourceFile, moduleNameText, mode);
+  }
+
+  /**
+   * Gets the mode required for module resolution required with the addition of Node16/nodenext
+   */
+  public static getModeForUsageLocation(
+    file: { impliedNodeFormat?: ts.SourceFile['impliedNodeFormat'] },
+    usage: ts.StringLiteralLike | undefined
+  ) {
```
Comment (DanielRosenwasser) [inline apps/api-extractor/src/analyzer/TypeScriptInternals.ts:101]:
```suggestion
  ): ts.ModuleKind.CommonJS | ts.ModuleKind.ESNext | undefined {
```

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: apps/api-extractor/src/analyzer/ExportAnalyzer.ts [hunk 5]
```diff
@@ -863,9 +872,18 @@ export class ExportAnalyzer {
...
   ): AstModule {
     const moduleSpecifier: string = this._getModuleSpecifier(importOrExportDeclaration);
+    const mode =
+      importOrExportDeclaration.moduleSpecifier &&
+      ts.isStringLiteralLike(importOrExportDeclaration.moduleSpecifier)
+        ? TypeScriptInternals.getModeForUsageLocation(
+            importOrExportDeclaration.getSourceFile(),
+            importOrExportDeclaration.moduleSpecifier
+          )
+        : undefined;
```
Comment (DanielRosenwasser) [inline apps/api-extractor/src/analyzer/ExportAnalyzer.ts:882]: Ideally, you could leverage `_getModuleSpecifier` to return the *node* and get the string out of that. It's not critical, I wouldn't block this PR on it.

**Comment by chrisdholt** [comment]
Thanks for the review @DanielRosenwasser - build is passing with updated types! @iclanton, @octogonz, @D4N14L, @apostolisms - Apologies for the ping, but curious if anyone is available to work with us on getting this out the door to unblock our release? Thank you!

File: apps/api-extractor/src/analyzer/ExportAnalyzer.ts (hunk 5 above)
Comment (chrisdholt) [reply apps/api-extractor/src/analyzer/ExportAnalyzer.ts]: Leaving this open to get feedback from maintainers here as well.

**Review by DanielRosenwasser — APPROVED** [review]

File: common/changes/@microsoft/api-extractor/users-chhol-fix-getResolvedModule-params_2022-05-25-17-20.json [hunk 6]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/api-extractor",
+      "comment": "add missing required parameter for getResolvedModule to ensure typescript can accurately resolve module kind",
```
Comment (iclanton) [inline common/changes/@microsoft/api-extractor/users-chhol-fix-getResolvedModule-params_2022-05-25-17-20.json:5]:
```suggestion
      "comment": "Fix an issue where API Extractor would fail to run on a project where `\"moduleResolution\"` is set to `\"Node16\"` in `tsconfig.json`",
```

File: common/changes/@microsoft/api-extractor/users-chhol-fix-getResolvedModule-params_2022-05-25-17-20.json [hunk 7]
```diff
@@ -0,0 +1,10 @@
...
+      "type": "minor"
```
Comment (iclanton) [inline common/changes/@microsoft/api-extractor/users-chhol-fix-getResolvedModule-params_2022-05-25-17-20.json:6]:
```suggestion
      "type": "patch"
```

**Review by iclanton — APPROVED** [review]

**Review by DanielRosenwasser — APPROVED** [review]
