### PR TITLE
fix(api-extractor): preserve export keyword for namespace re-exports

### LINKED ISSUE #5516: [api-extractor] Missing 'export' keyword for namespace re-exports produces invalid TypeScript
# [api-extractor] Missing `export` keyword for namespace re-exports produces invalid TypeScript

## Summary

When a TypeScript source file contains a namespace with re-export declarations using `export { }` syntax, api-extractor strips the `export` keyword from the rollup output, producing syntactically invalid TypeScript.

## Repro steps

1. Create a TypeScript file with a namespace that re-exports types:

```typescript
export type Color = { r: number; g: number; b: number };
export type Vector3 = { x: number; y: number; z: number };

export declare namespace SDK {
  export { Color, Vector3 };
}
```

2. Run `tsc` to generate `.d.ts` files (output is correct)
3. Run `api-extractor run --local` to generate rollup
4. Check the output `.d.ts` rollup

## Expected behavior

The rollup should contain:

```typescript
export declare namespace SDK {
        export { Color, Vector3, };
}
```

## Actual behavior

The rollup contains:

```typescript
export declare namespace SDK {
        { Color, Vector3, };
}
```

The `export` keyword is missing, which produces invalid TypeScript:

```
error TS1109: Expression expected.
```

## Root cause

In `DtsRollupGenerator.ts` (and `ApiReportGenerator.ts`), lines ~272-276 unconditionally skip all `ExportKeyword` tokens:

```typescript
case ts.SyntaxKind.ExportKeyword:
case ts.SyntaxKind.DefaultKeyword:
case ts.SyntaxKind.DeclareKeyword:
  span.modification.skipAll();
  break;
```

The `export` keyword is then re-added for declaration types (interface, class, enum, namespace, function, type) at lines ~279-306. However, `ExportDeclaration` nodes (like `export { Foo }`) are not handled, so the `export` keyword is stripped but never restored.

## Proposed fix

Check if the `ExportKeyword` is part of an `ExportDeclaration` inside a `ModuleBlock` (namespace body), and if so, preserve it:

```typescript
case ts.SyntaxKind.ExportKeyword:
  // Preserve export keyword for ExportDeclarations inside namespaces
  if (span.node.parent && ts.isExportDeclaration(span.node.parent)) {
    const moduleBlock = TypeScriptHelpers.findFirstParent(
      span.node,
      ts.SyntaxKind.ModuleBlock
    );
    if (moduleBlock) {
      break; // Preserve the export keyword
    }
  }
  span.modification.skipAll();
  break;
```

## Environment

- api-extractor version: 7.55.2
- TypeScript version: 5.x
- Node.js version: 20.x

### PR DESCRIPTION
**Pull request by ItsChrisHickman**
## Summary

Fixes #5516

When a namespace contains `export { Foo, Bar };` re-export declarations, api-extractor was incorrectly stripping the `export` keyword, producing `{ Foo, Bar, };` which is syntactically invalid TypeScript.

**Input:**
```typescript
export declare namespace SDK {
  export { Color, Vector3 };
}
```

**Before (invalid):**
```typescript
export declare namespace SDK {
        { Color, Vector3, };
}
```

**After (valid):**
```typescript
export declare namespace SDK {
        export { Color, Vector3, };
}
```

## Details

The issue is in `DtsRollupGenerator.ts` and `ApiReportGenerator.ts`. Both files unconditionally skip all `ExportKeyword` tokens (lines ~272-276), then re-add them for declaration types (interface, class, enum, namespace, function, type). However, `ExportDeclaration` nodes (like `export { Foo }`) were not handled, so the `export` keyword was stripped but never restored.

The fix checks if an `ExportKeyword` is part of an `ExportDeclaration` that is inside a `ModuleBlock` (namespace body), and if so, preserves it.

## How it was tested

1. Created a minimal reproduction case with a namespace containing `export { }` declarations
2. Verified that tsc produces valid output
3. Verified that api-extractor (before fix) produces invalid output (TS1109)
4. Applied fix and verified api-extractor now produces valid output

### CODE REVIEW

**Comment by ItsChrisHickman** [comment]
@microsoft-github-policy-service agree

File: apps/api-extractor/src/generators/DtsRollupGenerator.ts [hunk 1]
```diff
@@ -270,6 +270,23 @@ export class DtsRollupGenerator {
         break;
 
       case ts.SyntaxKind.ExportKeyword:
+        // Check if this export keyword is part of an ExportDeclaration inside a namespace
```
Comment (iclanton) [inline apps/api-extractor/src/generators/DtsRollupGenerator.ts]: Can you deduplicate this and the other instance of this same code in the API report generator?

**Review by iclanton — APPROVED** [review]

File: apps/api-extractor/src/generators/ApiReportGenerator.ts [hunk 2]
```diff
@@ -302,6 +302,23 @@ export class ApiReportGenerator {
...
+          if (moduleBlock) {
+            // This is an export declaration inside a namespace - preserve the export keyword
+            break;
+          }
+        }
+        // Otherwise, delete the export keyword -- we will re-add it below
+        span.modification.skipAll();
+        break;
+
       case ts.SyntaxKind.DefaultKeyword:
```
Comment (iclanton) [inline apps/api-extractor/src/generators/ApiReportGenerator.ts:313]: Does the `default` need to be retained in these cases as well?

**Comment by iclanton** [comment]
This looks good overall to me. @octogonz should take a look as well, though.

File: apps/api-extractor/src/generators/DtsRollupGenerator.ts (hunk 1 above)
Comment (ItsChrisHickman) [reply apps/api-extractor/src/generators/DtsRollupGenerator.ts]: Sure!  I'll move it to DTSEmitHelpers.ts and import from there!

File: apps/api-extractor/src/generators/ApiReportGenerator.ts (hunk 2 above)
Comment (ItsChrisHickman) [reply apps/api-extractor/src/generators/ApiReportGenerator.ts:313]: No, DefaultKeyword does not need the same treatment because export default cannot appear inside a namespace.
