### PR TITLE
[heft-typescript] Fix updateShapeSignature break

### LINKED ISSUE #4224: [heft] Dev server broken by "File extension for signature expected to be dts"
## Summary

After upgrading to the latest Heft+TypeScript, I now occasionally get this error in the `heft start` dev server:

```
[build:typescript] File change detected. Starting incremental compilation...
[build:typescript] Error: Debug Failure. False expression: File extension for signature expected to be dts: Got:: C:/Git/my-repo/my-app/lib/ui/misc/App.d.ts.map
```

After this error is reported, the dev server will continue serving the old build. So you can spend several minutes debugging a "problem" that ultimately turns out be that you're debugging an outdated build.

Killing and restarting `heft start` fixes the problem.

## Repro steps

I haven't been able to determiner repro steps yet.  

@iclanton said he encountered the same issue recently.

## Details

This error message is an assertion failure in the `typescript` package:

[typescript/src/compiler/builderState.ts](https://github.com/microsoft/TypeScript/blob/88cb76d314a93937ce8d9543114ccbad993be6d1/src/compiler/builderState.ts#L414)
```ts
    export function computeDtsSignature(
        programOfThisState: Program,
        sourceFile: SourceFile,
        cancellationToken: CancellationToken | undefined,
        host: HostForComputeHash,
        onNewSignature: (signature: string, sourceFiles: readonly SourceFile[]) => void,
    ) {
        programOfThisState.emit(
            sourceFile,
            (fileName, text, _writeByteOrderMark, _onError, sourceFiles, data) => {
                Debug.assert(isDeclarationFileName(fileName), `File extension for signature expected to be dts: Got:: ${fileName}`);
                onNewSignature(computeSignatureWithDiagnostics(
```

So it seems that `heft-typescript-plugin` is sometimes passing an incorrect file extension to the compiler. (?)

Why does the Heft dev server never recover however? In addition to fixing the root cause, maybe we could also make Heft's dev server more robust.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.55.2 |
| `typescript` version? | 5.0.4 |
| Operating system? |Windows  |
| Node.js version (`node -v`)? | v16.15.1 |

### LINKED ISSUE #4470: [heft] Certain errors cause the watcher to stop updating, instead serving an outdated build
## Summary

1. Invoke `heft start` to work on a web app
2. Save a change to a TypeScript file that produces an error
3. Fix the error

**Expected result:**  Pressing F5 in the web browser reloads the latest build

**Actual result:** Pressing F5 reloads the old build from step 1.  Modifications of source files are entirely ignored.

This situation is extremely frustrating, because you can spend 10 minutes trying to understand why a bug persists no matter how you try to fix it, only to eventually realize that you're debugging an outdated build.

## Repro steps

I haven't had time to prepare a step-by-step repro.  But usually it is a simple syntax error such as renaming `class TheThing {` to `class The  Thing {` in a `*.tsx` file.  And the log output will look like this:

```
---- build started ----
[build:typescript] File change detected. Starting incremental compilation...
[build:typescript] Error: Debug Failure. False expression: File extension for signature expected to be dts: Got:: C:/Git/my-repo/apps/webapp/lib/ExamplePane.d.ts.map
-------------------- Failed (0.219s) --------------------
Encountered 1 error
  [build:typescript] Debug Failure. False expression: File extension for signature expected to be dts: Got:: C:/Git/my-repo/apps/webapp/lib/ExamplePane.d.ts.map
Waiting for changes. Press CTRL + C to exit...
```

In the above test, I was using a newer compiler:
```
[build:typescript] The TypeScript compiler version 5.2.2 is newer than the latest version that was tested with Heft (5.0); it may not work correctly.
[build:typescript] Using TypeScript version 5.2.2
[build:typescript] Starting compilation in watch mode...
```

However I seem to remember this problem occurring with TypeScript 4.x as well. (?)  It's not a new phenomenon.

## Details

@dmichon-msft believes it is actually a TypeScript compiler bug.

However even if that is the case, in such a situation either:

- Heft should recover from the crash and automatically relaunch the compiler, **- OR -**
- If recovery is impossible, Heft should at least notify the engineer as conspicuously as possible that the watch experience has broken

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.63.2 |
| Operating system? |  Windows   |
| Would you consider contributing a PR? |  Yes   |
| Node.js version (`node -v`)? |v16.20.2 |

### PR DESCRIPTION
**Pull request by dmichon-msft**
## Summary
Fixes #4224
Fixes #4470 

## Details
`Program#emit` contains an additional parameter `forceDtsEmit` that is not in the published types, and is passed during shape signature computation. Heft was not forwarding this parameter when overriding the program, resulting in behavior changes.

## How it was tested
Local repro of the issue in #4224. Running `heft-webpack5-everything-test` in watch mode and changing `class ChunkClass` in `ChunkClass.ts` to `class Chunk Class`.

## Impacted documentation
None

### CODE REVIEW

File: heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts [hunk 1]
```diff
@@ -51,7 +51,9 @@ export function configureProgramForMultiEmit(
     // Attach the originals to the Program instance to avoid modifying the same Program twice.
     // Don't use WeakMap because this Program could theoretically get a { ... } applied to it.
     [INNER_GET_COMPILER_OPTIONS_SYMBOL]?: TTypescript.Program['getCompilerOptions'];
-    [INNER_EMIT_SYMBOL]?: TTypescript.Program['emit'];
+    [INNER_EMIT_SYMBOL]?: // https://github.com/microsoft/TypeScript/blob/88cb76d314a93937ce8d9543114ccbad993be6d1/src/compiler/program.ts#L2697-L2698
+    // There is a "forceDtsEmit" parameter that is not on the published types.
+    (...args: [...Parameters<TTypescript.Program['emit']>, boolean | undefined]) => TTypescript.EmitResult;
```
Comment (D4N14L) [inline heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts:56]: Could this be updated to include the optional param and avoid the tsignores?

**Review by D4N14L — APPROVED** [review]

File: heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts (hunk 1 above)
Comment (dmichon-msft) [reply heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts:56]: Done.

**Comment by octogonz** [comment]
🚀  Released with `@rushstack/heft-typescript-plugin` `0.2.16`
