### PR TITLE
[heft-jest-plugin] Allow use of `preset` Jest configuration value when using module resolution

### LINKED ISSUE #2794: [heft] Jest presets such as "react-native" can't be loaded by a rig
Hello! I'm trying to use a rig package to centralize jest configurations file following this [docs](https://rushstack.io/pages/heft_tasks/jest/) 

I created a `jest.config.js file` in the rig package  
```
{
  "extends": "react-native",
  "silent": false,
  "verbose": false,
  "rootDir": "../",
  "roots": ["<rootDir>", "<rootDir>/src"],
  "testURL": "http://localhost/",
  "testMatch": ["<rootDir>/src/**/*.test.{ts,tsx}"],
  "testPathIgnorePatterns": ["/node_modules/"],
  "collectCoverage": false,
  "coverageDirectory": "<rootDir>/temp/coverage",
  "collectCoverageFrom": [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/test/**",
    "!src/**/__tests__/**",
    "!src/**/__fixtures__/**",
    "!src/**/__mocks__/**"
  ],
  "coveragePathIgnorePatterns": ["/node_modules/"],
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
    "\\.(jsx|ts|tsx)$": "babel-jest"
  },
  "transformIgnorePatterns": [],
  "setupFiles": [
    "<rootDir>/jest-setup.js",
    "<rootDir>/node_modules/react-native-gesture-handler/jestSetup.js",
    "@rushstack/heft/lib/exports/jest-global-setup.js"
  ],
  "resolver": "@rushstack/heft/lib/exports/jest-improved-resolver.js",
  "setupFilesAfterEnv": ["@testing-library/jest-native/extend-expect", 
    "<rootDir>/jest-setup.js"]
}
```

 and create a reference for it in the app I'm want to test with: 
` 
{
  "extends": "@myPackage/profiles/app/config/jest.config.json"
}
`
When I run the teste I'm getting the error:  

image

The tests are ok with I let the jest config at the app i'm want to test. 

I added the `heft-jest-plugin` at `heft.json`. 

| Question | Answer |
| -------- | -------- |
|`react-native`version? | 0.64.1 |
| `@rushstack/heft` version? |   0.34.3 |
| Operating system? | Windows  |
| `Node.js` version ? |  v14.17.0 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Allow the use of the `preset` Jest configuration value when using module resolution. Fixes #2794

## Details

The `preset` property was originally blocked when using module resolution, since module resolution also enabled the `extends` property to be used. The reasoning behind this was that the `preset` and `extends` properties were largely attempting to accomplish the same task (extending from a base configuration).

However, #2794 brings up a good point about presets, in that they can allow for more complicated/dynamic configuration options to be provided (since `preset` can be JSON or JS). These methods of configuring Jest would not otherwise be possible via a simple `extends` field. Instead, `preset` can still be resolved and used in a configuration, with the understanding that the preset will be the true "base" configuration upon which all properties in configuration files up the `extends` tree are placed. This means that `preset` is treated like any other property and can be overwritten, and that Jest will resolve the `preset` configuration and place the remaining configuration values on-top of that when performing a run.

### CODE REVIEW

**Review by octogonz — DISMISSED** [review]
The code looks fine, but @D4N14L and I discussed this PR and decided to make some design changes.

The details are posted in https://github.com/microsoft/rushstack/issues/2794#issuecomment-912119687

**Comment by iclanton** [comment]
Note: PR #3337 has renamed our GitHub `master` branch to `main`. This should not affect your pull request, but we recommend to redo your `git clone` to avoid confusion with the old branch name.

**Comment by iclanton** [comment]
@D4N14L - is this good to go in?

**Comment by D4N14L** [comment]
@iclanton yep it should be. Just merged main and pushed to re-kick the build

**Comment by D4N14L** [comment]
@iclanton @octogonz this is good to go now. I added:
- Functionality to prevent `preset` being defined in any extending configuration
- Jest-like resolution of the `preset` option

File: libraries/heft-config-file/src/ConfigurationFile.ts [hunk 1]
```diff
@@ -91,17 +91,41 @@ interface IConfigurationFileFieldAnnotation<TField> {
...
+   */
+  propertyValue: string;
+  /**
+   * The path to the configuration file the property was obtained from.
+   */
+  configurationFilePath: string;
+  /**
+   * The configuration file the property was obtained from.
+   */
+  configurationFile: Partial<TConfigurationFile>;
```
Comment (iclanton) [inline libraries/heft-config-file/src/ConfigurationFile.ts:115]: Partial?

File: common/changes/@rushstack/heft-config-file/user-danade-HeftJestPreset_2023-04-24-22-34.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/heft-config-file",
+      "comment": "The custom resolver method now accepts an options parameter. This parameter includes all previously provided information and now includes the partially-resolved configuration file.",
```
Comment (iclanton) [inline common/changes/@rushstack/heft-config-file/user-danade-HeftJestPreset_2023-04-24-22-34.json:5]: This is a breaking API change. Can you note that in the change description?

I wouldn't make this a major bump, given that it's a `@beta` API.

File: heft-plugins/heft-jest-plugin/includes/jest-preset.js [hunk 3]
```diff
@@ -0,0 +1,4 @@
+module.exports = {
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/includes/jest-preset.js:1]: Intentionally included? This doesn't look like it's referenced anywhere.

**Review by iclanton — COMMENTED** [review]
It'd be good to have a `build-tests` project exercise this since its semantics are a little fiddly.

File: heft-plugins/heft-jest-plugin/includes/jest-preset.js (hunk 3 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/includes/jest-preset.js:1]: Oops, was testing with this to make sure the changes worked. Will remove

File: libraries/heft-config-file/src/ConfigurationFile.ts (hunk 1 above)
Comment (D4N14L) [reply libraries/heft-config-file/src/ConfigurationFile.ts:115]: Yeah. Technically, we may not have a full `TConfigurationFile` at this point, since the base configuration may not be valid in the schema. This is also why we only validate the schema after the entire configuration file stack is loaded.

File: build-tests/heft-jest-preset-test/config/rush-project.json [hunk 4]
```diff
@@ -0,0 +1,8 @@
+{
+  "operationSettings": [
+    {
+      "operationName": "build",
+      "outputFolderNames": ["lib", "dist"]
+    }
```
Comment (iclanton) [inline build-tests/heft-jest-preset-test/config/rush-project.json:6]:
```suggestion
    {
      "operationName": "build",
      "outputFolderNames": ["lib", "dist"]
    },
    {
      "operationName": "_phase:build",
      "outputFolderNames": ["lib", "dist"]
    }
```

**Review by iclanton — APPROVED** [review]
