### PR TITLE
[rush-amazon-s3-build-cache-plugin] retry failed S3 requests with the same behavior as the the azure blob storage

### LINKED ISSUE #3198: [rush] transient S3 errors updating build cache causes CI to fail
## Summary

Somewhat frequently we get issues in our CI jobs during the phase that compiles dependencies. We make use of the S3 cloud caching functionality and sometimes (I haven't been able to work out specifically why, it seems to happen sometimes when there is little activity on the bucket) that compile step will fail because one of the packages fails to upload to S3 with the error

```
Error uploading cache entry to S3: Error: Amazon S3 responded with status code 503 (Slow Down)

Unable to set cloud cache entry.
```

Rerunning the job always fixes it. Ideally Rush would try and re-upload the cache entry itself automatically (or with a flag if required), a delay before retrying seems sensible.

Alternatively, a flag to not make this error fail the compile step would be fine too.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.59.2 |
| `rushVersion` from rush.json? | 5.59.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.17.5 |

### PR DESCRIPTION
**Pull request by ricsam**
## Summary

Fixes #3198, transient S3 errors updating build cache causes CI to fail

## How it was tested

Added one unit test with mocks to test that the retries are called.

Added support for starting a proxy server which will return 500 on every second request to test that the build-cache works when running rush build. This is documented in `build-tests/rush-amazon-s3-build-cache-plugin-integration-test/README.md`

## Todo

- [x] Rush change
- [ ] Rush version --bump

### CODE REVIEW

**Comment by dmichon-msft** [comment]
Retry logic should be handled internally by the build cache provider plugin. For example, the Azure SDK has built-in retry logic and defaults to 4 retries:
https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/storageretryoptions?view=azure-node-latest#@azure-storage-blob-storageretryoptions-maxtries
It is only the Amazon S3 plugin that has an issue with single-attempt, which is due to it having been refactored to use `node-fetch` and directly contact the APIs to avoid the enormously heavy Amazon S3 SDK (in terms of both raw dependency count and code size). As such, retry handling needs to be added specifically for that plugin.

**Comment by ricsam** [comment]
Thank you! The smallest PR to solve the issue would be to give the S3 plug-in the same default retry logic as the azure blob package.

I can go for that to begin with.

What do you think about having the retry options configurable? What do you prefer: each plug-in having their own retry options, or one global retry options which both plug-ins consume?

File: rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts [hunk 1]
```diff
@@ -103,27 +124,35 @@ export class AmazonS3Client {
...
-    } else {
-      this._throwS3Error(response, await this._safeReadResponseText(response));
-    }
+    const sendRequest: () => Promise<Buffer | undefined> = async (): Promise<Buffer | undefined> => {
+      const response: fetch.Response = await this._makeRequestAsync('GET', objectName);
+      if (response.ok) {
+        return await response.buffer();
+      } else if (response.status === 404) {
+        return undefined;
+      } else if (response.status === 403 && !this._credentials) {
```
Comment (dmichon-msft) [inline rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:133]: `400` and `401` are not retriable

Comment (ricsam) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:133]: I added 2 tests to verify that 400 and 401 are retriable:

https://github.com/microsoft/rushstack/pull/3248/commits/773aaccc80740fb4cb4fd6509494557b42315a97

Comment (dmichon-msft) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:133]: To clarify, I meant that they should be considered to be not retriable, since missing/incorrect auth is not something that can be corrected by sending the request again, nor is a malformed request payload.

Comment (ricsam) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:133]: Ah that makes sense 😅. I'll update so that the code can either throw error or retry

Comment (ricsam) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:150]: Do you know the rationale behind only throwing 403 errors if credentials are provided? This code: `if (response.status === 403 && !this._credentials) return undefined` 

Should 401 and 400 be handled in the same way?

Comment (ricsam) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:150]: Also, in `uploadObjectAsync` response codes are not handled (it is just `if (!response.ok) throw err`). Do you think response codes in `uploadObjectAsync` should be handled in the same way as in `getObjectAsync`?

Comment (ricsam) [reply rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts]: To answer my question myself:

I'd say 400, 401, 403 should be handled equally.

When no credentials are provided unauth errors should be silenced as the ones potentially running into this issue usually are human users (not CI) that don't have credentials and they should still be able to build without access to the cloud storage.

Usually human users users don't have writeAccess either to cloud storage so the `uploadObjectAsync` can simply throw if invalid response.

**Comment by ricsam** [comment]
I pushed a commit where 400, 401 and 403 are handled the same

File: rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/AmazonS3Client.test.ts [hunk 2]
```diff
@@ -218,21 +222,31 @@ describe(AmazonS3Client.name, () => {
...
+    let realSetTimeout: typeof setTimeout;
     beforeEach(() => {
+      // mock date
       realDate = global.Date;
       global.Date = MockedDate as typeof Date;
+
+      // mock setTimeout
+      realSetTimeout = global.setTimeout;
+      global.setTimeout = ((callback: () => void, time: number) => {
+        return realSetTimeout(callback, 1);
```
Comment (dmichon-msft) [inline rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/AmazonS3Client.test.ts:234]: You could use `process.nextTick(callback)` as an alternative.

**Review by dmichon-msft — APPROVED** [review]

File: rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts [hunk 3]
```diff
@@ -103,27 +134,65 @@ export class AmazonS3Client {
...
+      } else if (
+        (response.status === 400 || response.status === 401 || response.status === 403) &&
+        !this._credentials
+      ) {
+        // unauthorized due to not providing credentials,
+        // silence error for better DX when e.g. running locally without credentials
+        return {
+          hasNetworkError: false,
+          response: undefined
+        };
```
Comment (iclanton) [inline rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts:158]: If there are no credentials and we get a 401, or if we get a 403, we should tell the user that they need to authenticate. This looks the same as a cache miss, so a user with missing, expired, or insufficient credentials will never get entries from cache and will never know that they need to do something about that.

**Review by iclanton — CHANGES_REQUESTED** [review]

**Comment by iclanton** [comment]
You need to run `rush change`.

**Comment by ricsam** [comment]
This is ready for review 😊

File: common/changes/@microsoft/rush/retry-cloud-cache-requests_2022-03-10-22-16.json [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "fix transient errors in the aws s3 cloud cache plugin",
```
Comment (iclanton) [inline common/changes/@microsoft/rush/retry-cloud-cache-requests_2022-03-10-22-16.json:5]:
```suggestion
      "comment": "Improve retry logic in the Amazon S3 cloud cache plugin and improve reporting when the user is not authenticated.",
```

**Review by iclanton — APPROVED** [review]
