### PR TITLE
[api-documenter] Emit HTML tags for tables instead of Markdown code.

### LINKED ISSUE #2950: [api-documenter] Table structure is broken with multiple-line comments
## Summary

When I have a function with [multiple-line comment](https://github.com/issueset/api-documenter-issue/blob/b8ebddd4855c9019cdd099a5e6ae8b7524befc08/src/index.ts#L8-L18), the markdown table generated by `api-documenter` is [broken](https://github.com/issueset/api-documenter-issue/blob/master/docs/api-documenter-issue.md). 

## Repro steps

https://github.com/issueset/api-documenter-issue/ 

Run `pnpm install; pnpm build` to generate the markdown document.

  **Expected result:** The markdown content in `docs/api-documenter-issue.md` is correct.

  **Actual result:** The markdown content in `docs/api-documenter-issue.md` is broken.

## Details

I can fix this manually by adding `@remarks` in the comment. But I'm wondering if there was a way to generate a simpler document without table structure so that we won't have this kind of issues.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | 7.13.60 |
| Operating system? | Mac |
| Documentation target? | Markdown |
| Would you consider contributing a PR? | Yes if someone tells me how to do it |
| TypeScript compiler version? | 4.3 |
| Node.js version (`node -v`)? | v16.9.1 |

### PR DESCRIPTION
**Pull request by phryneas**
## Summary

This would fix #2950.

Currently, tables in generated Markdown do not work with multiline comments.

This PR changes over to HTML tables (which also work in Markdown and are in fact more standardized).

As a result, a lot of "emit different things in tables" code can be removed.

## Details

As an example of a broken generated table, see the end of the "Classes" table [in this markdown file](https://github.com/apollographql/apollo-client-nextjs/blob/1e64d9ba9680d50ac35a1178bef1cf612aa130dd/docs/client-react-streaming.md)

## How it was tested

Generating the code with this PR instead will result in [this diff](https://github.com/apollographql/apollo-client-nextjs/pull/240/commits/247d226a3f7ac58bd72bd2370e1f46b86ba41357) and as you can see [here](https://github.com/apollographql/apollo-client-nextjs/blob/247d226a3f7ac58bd72bd2370e1f46b86ba41357/docs/experimental-nextjs-app-support.md) the tables are not broken anymore.

## Impacted documentation

I believe this does not need any documentation changes.

### CODE REVIEW

File: apps/api-documenter/src/markdown/CustomMarkdownEmitter.ts [hunk 1]
```diff
@@ -102,40 +100,43 @@ export class CustomMarkdownEmitter extends MarkdownEmitter {
...
 
+        writer.write('<tbody>');
         for (const row of docTable.rows) {
-          writer.write('| ');
+          writer.write('<tr>');
           for (const cell of row.cells) {
-            writer.write(' ');
+            writer.write('<td>');
+            writer.writeLine();
+            writer.writeLine();
```
Comment (phryneas) [inline apps/api-documenter/src/markdown/CustomMarkdownEmitter.ts:128]: I'm adding a few extra newlines in here, since the table cells themselves can contain markdown and I know that some markdown parsers need those to switch from "parsing HTML" back to "parsing Markdown" mode.

File: apps/api-documenter/src/markdown/MarkdownEmitter.ts [hunk 2]
```diff
@@ -106,23 +104,9 @@ export class MarkdownEmitter {
...
-          const parts: string[] = code.split(/\r?\n/g);
-          writer.write(parts.join('</code><br/><code>'));
-        } else {
-          writer.write(docCodeSpan.code);
-        }
-        if (context.insideTable) {
-          writer.write('</code>');
-        } else {
-          writer.write('`');
-        }
```
Comment (phryneas) [inline apps/api-documenter/src/markdown/MarkdownEmitter.ts:125]: All of this extra handling code is not necessary anymore, since we can just emit markdown inside the HTML tables.

**Comment by phryneas** [comment]
I believe I did update the test, so I'm not 100% sure why this is still failing.

File: apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap [hunk 3]
```diff
@@ -50,9 +50,34 @@ HTML escape: &amp;quot;
...
+
+
+
+</th></tr></thead>
+<tbody><tr><td>
+
+Cell 1
+
+
+
```
Comment (iclanton) [inline apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap:71]: Can we emit two newlines after the cell contents instead of four?

File: common/changes/@microsoft/api-documenter/main_2024-03-14-17-16.json [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/api-documenter",
+      "comment": "Emit HTML tags for tables instead of Markdown code.",
+      "type": "patch"
```
Comment (iclanton) [inline common/changes/@microsoft/api-documenter/main_2024-03-14-17-16.json:6]:
```suggestion
      "type": "minor"
```

**Review by iclanton — APPROVED** [review]

File: apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap (hunk 3 above)
Comment (phryneas) [reply apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap:71]: I believe only two of them are from this PR, and the other two might come from `writeNode`.

I have to admit I don't know a lot about the `writeNode` implementation and if it always does that, or only in special cases.

I guess I went a bit overboard here and would be open for changes.

Maybe something like

```diff
-        writer.writeLine();
+        writer.ensureNewLine();
        writer.writeLine();
```

in the places where I applied two `writeLine`s?

Generally: I'm already in bed at this point, so I can't do any more changes today, but I would honestly be over the moon if I wake up to see this merged tomorrow (I essentially have a package release that's just waiting for a docs PR that relies on this 😅) - so if that's in any way a realistic expectation, please just go ahead and edit whatever you want here :)

Comment (phryneas) [reply apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap]: Okay, we're down to three newlines, two of which come from the `writeNode` call  - is that acceptable?

**Review by iclanton — APPROVED** [review]

**Comment by Lightning00Blade** [comment]
This PR introduces a regression. Opened https://github.com/microsoft/rushstack/issues/4586.

**Comment by octogonz** [comment]
https://github.com/microsoft/rushstack/issues/4586#issuecomment-2005835172

> ## Some background
> 
> There is a longnstanding issue that API Documenter generates "markdown" when there is no standardized syntax for Markdown. Of course [CommonMark](https://commonmark.org/) is such a standard, but all real world implementations add additional custom syntaxes, and because CommonMark lacks formalized extensibility, such custom syntaxes will always break the ability to parse true CommonMark correctly. As one example, suppose we introduce `:::tip` as mentioned above - consider this case:
> 
> ```
> :::tip
> ```
> [link](http://example.com)
> :::
> ```
> ```
> 
> Is `[link](http://example.com)` a hyperlink or not? Most likely the `:::tip` parser will naively snip out the code and parse it as Markdown, interpreting `` ``` `` as literal backticks because the closing `` ``` `` is now outside the chunk being parsed. As a result `[link](http://example.com)` is a real hyperlink. Whereas CommonMark would interpret `[link](http://example.com)` as being inside a code fence and NOT a hyperlink.
> 
> This is a mild inconvenience for human authors, but a major frustration for automated tools such as API Documenter that need to emit thousands of pages of API docs and have them render correctly. (BTW TSDoc explicitly aims to solve this problem by forbidding custom syntaxes and relying instead on HTML elements for advanced custom syntaxes.)
> ## What it means
> 
> Until now, API Documenter has aimed to produce a balanced dialect of markdown syntax that is likely to get rendered correctly by the most popular engines (Jekyll and GitHub at the time). Where it doesn't work, people have implemented various hacks like [api-documenter-docusaurus-plugin](https://github.com/microsoft/rushstack-websites/tree/main/tools/api-documenter-docusaurus-plugin) that try rewrite the incorrect expressions. That is exactly what @Lightning00Blade did, too.
> 
> PR #4578 will break that delicate equilibrium, so unfortunately we probably shouldn't have merged this PR. The safest move may be to revert it. 😅
> ## A better solution
> 
> But how to solve @phryneas's problem then?
> 
> What we can do instead is introduce **api-documenter.json** settings to control the output dialect. In this way API Documenter can be optimized for a known Markdown engine rather than trying to be a "least common denominator." We've been planning this already, since Docusuarus 3 has finally adopted standard MDX (whose syntax is based on JSX not CommonMark).
> 
> This week I'll see if I can put together a design proposal.

👉 _Reply to issue #4586_
