### PR TITLE
[rush] Support PNPM 6 and Removal of pnpm-lock.yaml Rewriting

### LINKED ISSUE #2601: [rush] Rush reports "Internal Error" after upgrading to PNPM 6
## Summary

Running `rush update` with `"pnpmVersion": "6.0.1"` results in `ERROR: Internal Error: Cannot find installed dependency <pkg>` when linking.

 

## Repro steps

1. Update `rush.json` to use `"pnpmVersion": "6.0.1"`
2. Run `rush purge && rush update`
3. Rush installs dependencies
4. When attempting to link first package encounters `ERROR: Internal Error: Cannot find installed dependency <first-dependency-of-first-local-package>`
 

  **Expected result:** 

A completed `rush update` linking.

  **Actual result:** 
```text
ERROR: Internal Error: Cannot find installed dependency "@rushstack/eslint-config" in
"D:\Dev\<pkg>\common\temp\node_modules\.pnpm\local\D%3A%2FDev%2F<pkg>%2Fcommon%2Ftemp%2Fprojects%2F<local-pkg>.tgz\node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

## Details

The issue is occurring because the directory referenced in the error above is now using `+` as a seperator instead of `%3A`  `:` and `%2F`  `/`

See: https://github.com/pnpm/pnpm/releases/tag/v6.0.1

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.43.0 |
| `rushVersion` from rush.json? | 5.43.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? |  Windows  |
| Would you consider contributing a PR? | Yes, if required |
| Node.js version (`node -v`)? | v14.16.0 |

### LINKED ISSUE #2602: [rush] Inconsistent yaml serialization during rush update
## Summary
Depending on if the lockfile gets modified by the package manager or not, the version of pnpm-lock.yaml that gets copied back to `common/config/rush/pnpm-lock.yaml` will have or not have quotes around `link:` fields.

## Repro steps

1) Enable `usePnpmPreferFrozenLockfileForRushUpdate`
2) Make an unnecessary invocation of `rush update`. Pnpm will see that the lockfile is up-to-date and not modify it, but rush will copy back the version it emitted.

Solution is to have rush always read and reserialize pnpm-lock.yaml when writing back to `common/config/rush/pnpm-lock.yaml` instead of copying.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.42.4 |
| `rushVersion` from rush.json? | 5.42.4 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.22.1 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Adds support for PNPM 6 in Rush!

## Details

- Fixes #2601 by using new path format to exploded tarball for local dependency
- Removes `pnpm-lock.yaml` modification of tarball integrity hashes for local projects in non-workspaces PNPM installs and replaces it with validation prior to running PNPM install
- Removes `pnpm-lock.yaml` shrinkwrap churn optimization in favor of built-in shrinkwrap churn optimization in PNPM
- Fixes #2602 where a bug in Rush caused double-quotes to be added in the `pnpm-lock.yaml` in some scenarios
- Only attempts to delete `pnpm-workspace.yaml` once instead of for each local package

`pnpm-lock.yaml` modification by Rush has been something that we have been attempting to remove for some time. With PNPM 6 using a new `pnpm-lock.yaml` format, this felt like a good time to remove this functionality instead of updating and special-casing writing of the file even further. There were two things that were being done with this manual modification:

1. Shrinkwrap churn optimization on behalf of PNPM prior to running install in order to reduce the amount of churn in the `pnpm-lock.yaml` file when adding a dependency that may be satisfied by an existing instance of that package elsewhere in the monorepo. This optimization was confusing for devs (#1142), and the PNPM-side resolution strategy `fewer-dependencies` has been the default since v3 and is the only option as of [v5](https://github.com/pnpm/pnpm/releases/tag/v5.0.1). Additionally, this churn optimization would happen during normal `rush install`, which means that this feature was breaking the expectation that "install" would perform install with the lockfile in it's current state. We even had to disable this feature specifically when using the PNPM `frozen-lockfile` feature, even though this is _not_ documented anywhere. In my opinion, PNPM has gotten much better at this, to the point that it doesn't make sense to keep maintaining the feature within Rush.
2. Manual tarball integrity hash updates for local packages. These were performed in a narrow use-case of non-workspace installs using PNPM, with the `usePnpmFrozenLockfileForRushInstall` experiment set to `true`. This was implemented in order to smooth over issues with using the `frozen-lockfile` feature in PNPM that were found when monorepo packages had versions bumped. When this happens (or when the contents of a `package.json` is changed at all in a way that affects the temp `package.json` in `common/temp`, really), the lockfile integrity hash would become out of date, causing the install to fail. This is an artifact of how Rush uses tarballs for local package installs in non-workspace monorepos. I've replaced this with a validation check prior to running install that should clearly describe to the developer how to resolve the out-of-date hash (running `rush update`). Removing this will mean that people in this narrow use-case will need to run `rush update` more frequently.

The net result of these changes is that we no longer have any need to directly modify the `pnpm-lock.yaml` file, and can instead leave that entirely up to PNPM to handle. This goes hand-in-hand with the goal of decoupling Rush from specific package managers.

## How it was tested

Ran installs against legacy Rush repo (tsdoc) as well as more recent Rush repo. Validated that install completed successfully and that builds could run as expected. Validated that changes to package versions in non-workspace monorepos with `usePnpmFrozenLockfileForRushInstall` set to `true` would result in integrity hash differences that require `rush update` to be run. Validated that `rush update` resolved the issue.

### CODE REVIEW

File: apps/rush-lib/src/logic/installManager/RushInstallManager.ts [hunk 1]
```diff
@@ -366,6 +340,17 @@ export class RushInstallManager extends BaseInstallManager {
       }
     }
 
+    // Remove the workspace file if it exists
+    if (this.rushConfiguration.packageManager === 'pnpm') {
+      const workspaceFilePath: string = path.join(
+        this.rushConfiguration.commonTempFolder,
+        'pnpm-workspace.yaml'
+      );
+      if (FileSystem.exists(workspaceFilePath)) {
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/installManager/RushInstallManager.ts:349]: Can we just delete and catch the exception? It's a cleaner pattern.

File: apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts [hunk 2]
```diff
@@ -222,11 +222,17 @@ export class PnpmLinkManager extends BaseLinkManager {
     //   C%3A%2Fwbt%2Fcommon%2Ftemp%2Fprojects%2Fapi-documenter.tgz
     //   C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fpresentation-integration-tests.tgz_jsdom@11.12.0
     //   C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fbuild-tools.tgz_2a665c89609864b4e75bc5365d7f8f56
-    const folderNameInLocalInstallationRoot: string =
+    let folderNameInLocalInstallationRoot: string =
       uriEncode(Text.replaceAll(absolutePathToTgzFile, path.sep, '/')) + folderNameSuffix;
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts:226]:
```suggestion
Path.convertToSlashes(absolutePathToTgzFile)
```
Mind, that function itself needs to be changed to `.replace(/\\/g, '/')` instead of using `String.prototype.split()`, but that's out of scope.

**Review by dmichon-msft — APPROVED** [review]
Couple nits, but looks good.

**Comment by dmichon-msft** [comment]
Does this fix #2602 as well?

**Comment by D4N14L** [comment]
> Does this fix #2602 as well?

Yes it does. By removing all manual modification of the lockfile it should be consistently serialized by PNPM

File: apps/rush-lib/src/logic/installManager/RushInstallManager.ts [hunk 3]
```diff
@@ -366,6 +340,17 @@ export class RushInstallManager extends BaseInstallManager {
...
+        FileSystem.deleteFile(workspaceFilePath);
+      }
```
Comment (iclanton) [inline apps/rush-lib/src/logic/installManager/RushInstallManager.ts:351]:
```suggestion
      try {
        await FileSystem.deleteFileAsync(workspaceFilePath);
      } catch (e) {
        if (!FileSystem.isNotExistError(e)) {
          throw e;
        }
      }
```

**Comment by wbern** [comment]
It's really impressive that you're polishing rush to the point of maintaining separation of concerns regarding things like this. Keep up the good work!

**Review by sachinjoseph — APPROVED** [review]

File: apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts [hunk 4]
```diff
@@ -222,11 +222,17 @@ export class PnpmLinkManager extends BaseLinkManager {
...
+      uriEncode(Path.convertToSlashes(absolutePathToTgzFile)) + folderNameSuffix;
+
+    // PNPM 6 changed formatting to replace all special chars with '+'
+    // e.g.: C++dev+imodeljs+imodeljs+common+temp+projects+presentation-integration-tests.tgz_jsdom@11.12.0
+    if (this._pnpmVersion.major >= 6) {
+      const specialCharRegex: RegExp = /%[a-fA-FA-F0-9]{2}/g;
+      folderNameInLocalInstallationRoot = folderNameInLocalInstallationRoot.replace(specialCharRegex, '+');
+    }
 
     // e.g.: C:\wbt\common\temp\node_modules\.local\C%3A%2Fwbt%2Fcommon%2Ftemp%2Fprojects%2Fapi-documenter.tgz\node_modules
```
Comment (octogonz) [inline apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts:235]: @D4N14L When checking out your branch, I encountered an error since your GitHub fork is still called `web-build-tools`.  Might be time to update that.  :-)

File: apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts [hunk 5]
```diff
@@ -222,11 +222,17 @@ export class PnpmLinkManager extends BaseLinkManager {
     //   C%3A%2Fwbt%2Fcommon%2Ftemp%2Fprojects%2Fapi-documenter.tgz
     //   C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fpresentation-integration-tests.tgz_jsdom@11.12.0
     //   C%3A%2Fdev%2Fimodeljs%2Fimodeljs%2Fcommon%2Ftemp%2Fprojects%2Fbuild-tools.tgz_2a665c89609864b4e75bc5365d7f8f56
-    const folderNameInLocalInstallationRoot: string =
-      uriEncode(Text.replaceAll(absolutePathToTgzFile, path.sep, '/')) + folderNameSuffix;
+    let folderNameInLocalInstallationRoot: string =
+      uriEncode(Path.convertToSlashes(absolutePathToTgzFile)) + folderNameSuffix;
+
+    // PNPM 6 changed formatting to replace all special chars with '+'
```
Comment (octogonz) [inline apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts:228]: Can you cite a source for this?  Looks like maybe it is performed by [dependency-path/src/index.ts](https://github.com/pnpm/pnpm/blob/9ceab68f06eeac185b8b2712a3c8ec0fb26a74ef/packages/dependency-path/src/index.ts#L134).

If so, that code seems to be only replacing `:` and `/` -- not "all special chars".  (?)

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 6]
```diff
@@ -649,9 +644,14 @@ export abstract class BaseInstallManager {
...
-      shrinkwrapFile.save(this.rushConfiguration.tempShrinkwrapFilename);
-      shrinkwrapFile.save(this.rushConfiguration.tempShrinkwrapPreinstallFilename);
+      Utilities.syncFile(
+        this._rushConfiguration.getCommittedShrinkwrapFilename(this.options.variant),
+        this.rushConfiguration.tempShrinkwrapFilename
+      );
+      Utilities.syncFile(
+        this._rushConfiguration.getCommittedShrinkwrapFilename(this.options.variant),
+        this.rushConfiguration.tempShrinkwrapPreinstallFilename
+      );
```
Comment (octogonz) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:654]: When I invoke `rush install` using this PR, for the already-up-to-date state (where `pnpm install` is skipped), the console output looks like this:

```
Found files in the "common/git-hooks" folder.
Successfully installed these Git hook scripts: pre-commit

Trying to acquire lock for pnpm-5.18.9
Acquired lock for pnpm-5.18.9
Found pnpm version 5.18.9 in C:\Users\Owner\.rush\node-v12.20.1\pnpm-5.18.9

Symlinking "C:\Git\MyRepo\common\temp\pnpm-local"
  --> "C:\Users\Owner\.rush\node-v12.20.1\pnpm-5.18.9"
Copying C:\Git\MyRepo\common\config\rush\.npmrc --> C:\Git\MyRepo\common\temp\.npmrc
Updating C:\Git\MyRepo\common\temp\pnpmfile.js

Updating workspace files in C:\Git\MyRepo\common\temp
Finished creating workspace (0.16 seconds)
Updating C:\Git\MyRepo\common\temp\pnpm-lock.yaml
Updating C:\Git\MyRepo\common\temp\pnpm-lock-preinstall.yaml

Checking node_modules in C:\Git\MyRepo\common\temp


Rush install finished successfully. (0.58 seconds)
```

(The messages about `pnpm-lock.yaml` and `pnpm-lock-preinstall.yaml` are new in this PR.)

Some observations:
- `Symlinking` shows the destination on a separate line from the source
- `Copying` shows the destination on the same line as the source.  (When I looked at the code, it seems that actually `Utilities.copyAndTrimNpmrcFile()` is not actually a simple "copy" operation, but rather transforms the file based on environment variables.)
- `Updating` shows ONLY the destination.  If the source file does not exist, then `Utilities.syncFile()` will instead say `Deleting ${destinationPath}`.  (But this code path seems to be impossible for  `pnpm-lock.yaml`.)
- Some other common/temp files don't get mentioned at all: `clientPnpmfile.js`, `current-variant.json`, `pnpmfileSettings.json`, `pnpm-workspace.yaml`
- The `Checking node_modules in` message is actually testing whether we can skip `pnpm install` or not.

🤔 Maybe this is fine?  Some possible improvements:

1. Change `Utilities.copyAndTrimNpmrcFile()` to say "Transforming" and print the `-->` on a separate line (like how  "Symlinking" does)
2. Change `Utilities.syncFile()` to say "Copying" since it is an actual file copy.  The source is unimportant.
3. If `Checking node_modules in` determines to skip `pnpm install`,  maybe we should print a message like `Installation is already up to date.`

File: apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts (hunk 5 above)
Comment (D4N14L) [reply apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts:228]: Looks like this is correct, good catch! I'll update

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts (hunk 6 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/base/BaseInstallManager.ts:654]: > 3\. We should print a newline before `Updating C:\Git\MyRepo\common\temp\pnpm-lock.yaml` since it is unrelated to `Finished creating workspace (0.16 seconds)`

(Alternatively, maybe we should eliminate the message `Finished creating workspace (0.16 seconds)` -- is it important to measure this?  Have you ever seen it take a nontrivial amount of time?)

Comment (D4N14L) [reply apps/rush-lib/src/logic/base/BaseInstallManager.ts:660]: I think I got all of these but you may want to try it out locally to see how it feels to you (but heads up my remote URL changed),
