### PR TITLE
[rush] Remove Rush's own validation of the PNPM lockfile

### LINKED ISSUE #2227: [rush] shrinkwrap-deps is not updated on full update with pnpm >= 5.5.8
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

With `pnpm > 5.5.5`, while running `rush update --full`, rush stops at linking step with
```
ERROR: Internal Error: Unable to find dependency webpack with version /webpack/4.44.2 in shrinkwrap.
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

In this case ,`webpack@4.44.2` is a dependency of storybook, and is being updated from `4.44.1`. However `shrinkwrap-deps.json`s for both packages with storybook still contain `webpack/4.44.1` entry.

Dependencies:
package in monorepo
```
"devDependencies": {
  ...
  "@storybook/react": "6.0.21",
  ...
}
```

`@storybook/react`
```
"dependencies": {
  ...
  "webpack": "^4.43.0"
}
```

With pnpm <= `5.5.5` everything works as exepcted.

Note: I experienced this issue with `pnpm >= 5.5.7`. With `5.5.6`, I got `boolean false is not iterable (cannot read property Symbol(Symbol.iterator))` at install step, so not sure if it was affected.

**What is the expected behavior?**

rush is able to perform full dependencies update with `pnpm > 5.5.5`, correctly updating `shrinkwrap-deps.json` for each package

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** 5.34.2
* **Node Version:** 12.16.1
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** macOS Catalina 10.15.6

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Fixes #2227 

After looking at the issue specified above, as well as the repro produced by @chengcyber (thank you!!), I determined that the bug was being caused by a chained peer dependency within Jest, eventually resulting in a dependency on ts-node 8.10.2 as specified on the Rush project that was attempting to be installed. The per project manifest generator (that produces `shrinkwrap-deps.json`) was crawling through peer dependencies to determine the version of the package actually consumed, so as to add the integrity hash to the shrinkwrap, however it couldn't find the required dependency because it was aquired through a chained peer dependency, which the generator did not expect, causing generation and thus linking to fail.

## Details

After thinking on it, I came to the conclusion that Rush really has no business in validating that the PNPM shrinkwrap is valid/the install is valid (that determination belongs to the package manager) while crawling for dependencies. All we are trying to do is figure out which packages are actually used throughout the dependency stack. Given this understanding, we can remove the validation logic and boil it down to some base assumptions:
- is the peer dependency satisfied by the package itself? If yes, it should already be in the dependency tree. If not...
- is the peer dependency satisfied by the parent package (or any other parent package reachable via peer dependency chaining for that matter)? If yes, it should already be in the dependency tree. If not...
- is the peer dependency hoisted up to the root level? If yes, then add the dependency to the dependency tree. If not...
- assume that the package manager knows what it's doing, that the install is valid, and that the dependency must already be included somewhere up the dependency tree

When taking this all into account, it means that we can write the manifest generation logic in such a way that, even when we can't find what we're looking for (likely due to a chained peer dependency), we can assume the package manager already did for us, and that package should be recorded in the dependency stack.

## How it was tested

Ran solution against the provided repro and confirmed that the required peer dependency was specified in the shrinkwrap-deps.json file (the per-project manifest that is generated)

### CODE REVIEW

File: apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts [hunk 1]
```diff
@@ -168,141 +163,48 @@ export class PnpmProjectDependencyManifest {
...
-      // When using workspaces, hoisting of dependencies is not possible. Therefore, all packages that are consumed
-      // should be specified as direct dependencies in the shrinkwrap. Given this, there is no need to look for peer
-      // dependencies, since it is simply a constraint to be validated by the package manager.
       return;
     }
 
-    for (const [peerDependencyName, peerDependencyVersion] of Object.entries(
-      shrinkwrapEntry.peerDependencies || {}
-    )) {
+    for (const [peerDependencyName] of Object.entries(shrinkwrapEntry.peerDependencies)) {
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts:178]:
```suggestion
    for (const peerDependencyName of Object.keys(shrinkwrapEntry.peerDependencies)) {
```

**Review by dmichon-msft — APPROVED** [review]
Looks good, with one minor note.

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
This was published with Rush 5.40.4
