### PR TITLE
[rush] Install optional dependencies, except when using npm<5.0.0

### LINKED ISSUE #761: [rush] rush update doesn't work with optional dependencies
When I try to use `rush` on a package that depends on webpack on a laptop that runs Linux I get the following error:

```sh
alexghr@alexghr-XPS-15-9560:~/Work/rushtest$ rush update


Rush Multi-Project Build Tool 5.0.0 - https://rushjs.io


Creating folder: /home/alexghr/Work/rushtest/common/config/rush
Starting "rush update"

Script is out of date; updating "/home/alexghr/Work/rushtest/common/scripts/install-run.js"
Script is out of date; updating "/home/alexghr/Work/rushtest/common/scripts/install-run-rush.js"

Trying to acquire lock for npm-6.2.0
Acquired lock for npm-6.2.0
Found npm version 6.2.0 in /home/alexghr/.rush/npm-6.2.0

Symlinking "/home/alexghr/Work/rushtest/common/temp/npm-local"
  --> "/home/alexghr/.rush/npm-6.2.0"

Updating temp projects in /home/alexghr/Work/rushtest/common/temp/projects
Updating /home/alexghr/Work/rushtest/common/temp/projects/foo.tgz
Finished creating temporary modules (0.01 seconds)

Checking node_modules in /home/alexghr/Work/rushtest/common/temp

Deleting the "npm-cache" folder
Deleting the "npm-tmp" folder

Running "npm install" in /home/alexghr/Work/rushtest/common/temp

npm notice created a lockfile as package-lock.json. You should commit this file.
added 339 packages from 277 contributors and audited 6807 packages in 7.946s
found 0 vulnerabilities


Running "npm shrinkwrap"...
npm notice package-lock.json has been renamed to npm-shrinkwrap.json. npm-shrinkwrap.json will be used for future installations.
"npm shrinkwrap" completed


Applied workaround for NPM 5 bug

Updating /home/alexghr/Work/rushtest/common/config/rush/npm-shrinkwrap.json

Linking projects together...

ERROR: Failed to parse package.json for fsevents: ENOENT: no such file or directory, open '/home/alexghr/Work/rushtest/common/temp/node_modules/fsevents/package.json'
```

The project depends (transitively, through webpack) on `fsevents` which is a package that can only be installed on a Mac.
The shrinkwrap file at `common/config/rush/npm-shrinkwrap.json` correctly marks `fsevents` as optional.

My minimal test case:

```sh
alexghr@alexghr-XPS-15-9560:~/Work/rushtest$ tree
.
|-- foo
|   `-- package.json
`-- rush.json

1 directory, 2 files

alexghr@alexghr-XPS-15-9560:~/Work/rushtest$ cat rush.json 
{
  "rushVersion": "5.0.0",
  "npmVersion": "6.2.0",
  "nodeSupportedVersionRange": ">=8.11.1 <9.0.0",

  "projects": [
    {
      "packageName": "foo",
      "projectFolder": "foo"
    }
  ]
}

alexghr@alexghr-XPS-15-9560:~/Work/rushtest$ cat foo/package.json 
{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
          "webpack": "*"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### PR DESCRIPTION
**Pull request by elliottsj**
Resolves #761

With this change, optional dependencies are no longer ignored, and instead are written to the package manager's (npm/pnpm/yarn) respective lockfile. This allows optional dependencies such as fsevents to be installed on supported systems (e.g. macOS), but remain uninstalled on unsupported systems (e.g. Windows).

For more info about this change, see https://github.com/Microsoft/web-build-tools/issues/761#issuecomment-428694443

### CODE REVIEW

**Comment by elliottsj** [comment]
I've tested this change on macOS, using npm@4.6.1, npm@6.4.1, pnpm@2.16.3, and yarn@1.12.0. Haven't tested on Windows (and don't currently have a Windows machine set up for Node.js development), so any help there is appreciated.

File: apps/rush-lib/src/logic/InstallManager.ts [hunk 1]
```diff
@@ -975,15 +958,34 @@ export class InstallManager {
    */
   private _pushConfigurationArgs(args: string[], options: IInstallManagerOptions): void {
     if (this._rushConfiguration.packageManager === 'npm') {
-      args.push('--no-optional');
+      if (semver.lt(this._rushConfiguration.packageManagerToolVersion, '5.0.0')) {
+        // NOTE:
```
Comment (elliottsj) [inline apps/rush-lib/src/logic/InstallManager.ts]: I kept this comment (which was originally added in https://github.com/Microsoft/web-build-tools/pull/175), reworded it a bit, and added a couple useful links. lmk if I should change anything else here.

**Comment by pgonzal** [comment]
This fix was released with Rush 5.3.4
