### PR TITLE
[rush] Use PnpmfileConfiguration for installation and 'up-to-date' checks

### LINKED ISSUE #2656: [rush] rush install always complain shrinkwrap is not up to date
## Summary

rush install always complain `The shrinkwrap file is out of date. You need to run "rush update".` even after rush update

## Repro steps

1. add a `.pnpmfile.cjs` (pnpm v6, i think pnpm v5 should be same)
2. rush update, pnpm-lock.yaml is updated
3. rush install, failed with error

## Details

in `.pnpmfile.cjs`, some dependencies' version are settled down to specified version.

such as `typescript` stick into `4.2.3` version

After a little dig in codebase, I see this commit https://github.com/microsoft/rushstack/commit/18d9a27a3abfe8f96ed9fbac1fa29088e270bb82 change the validation logic.

Currently, `!foundDependency || foundDependency.version !== importerVersionSpecifier` will always be false if a version changed via `pnpmfile`.

e.g.

a package declare in package.json

```
"dependencies": {
  "typescript": "~4.2.3"
}
```

then `foundDependency.version` should be equal to `~4.2.3`, it comes from rushProject.packageJsonEditor, which comes from `package.json`

while, `importerVersionSpecifier` should be equal to `4.2.3`, it comes from pnpm, and pnpmfile set the typescript version to `4.2.3`

So, this kind of situation leads to `~4.2.3` will never equals to `4.2.3`

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.45.5 |
| `rushVersion` from rush.json? | 5.45.5  |
| `useWorkspaces` from rush.json? |  true  |
| Operating system? | Mac   |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? | 14.15.4 |

### LINKED ISSUE #2657: [rush] deploy with useWorkspaces on complains a deleted module is missing
## Summary

rush deploy throw error `Could not find module xxx'

## Repro steps

Assuming package.json:

```
// package.json
{
  "dependencies": {
    "foo": "1.0.0",
  }
}
```

setup `pnpmfile` to **DELETE** this foo dep in pnpmfile.

## Details

https://github.com/microsoft/rushstack/commit/e84113622e3f55af6308360aa0a693aeb975e49c avoid load pnpmfile config when `useWorkspace` is on.

The deleted `foo` will be added to `dependencyNamesToProcess`, since https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/logic/deploy/DeployManager.ts#L161 called but skipped. So, rush complain foo is missing, but foo is indeed removed via pnpmfile.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.45.5 |
| `rushVersion` from rush.json? | 5.45.5 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac  |
| Would you consider contributing a PR? | Yes  |
| Node.js version (`node -v`)? | 14  |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Adds `PnpmfileConfiguration` support to the `rush install` action, and implements optional pnpmfile shimming support for workspaces mode.

Fixes #2656
Fixes #2657

## Details

It was determined that the new Rush up-to-date check method that was added in PR #2649 introduced a bug due to not considering pnpmfile modifications to the package.json. The main goal of this PR is to refactor and generalize use of `PnpmfileConfiguration` to be used in both `rush install` and `rush deploy` commands in order to transform the package.json prior to being checked for up-to-dateness.

Additionally, this PR adds pnpmfile shimming support to `PnpmfileConfiguration`, which is used in workspaces to add common versions support. This will allow transforming the pnpmfile using the shim prior to running the client-provided pnpmfile.

Lastly, this PR changes legacy installs to also use the pnpmfile shim that was introduced in workspaces. In legacy installs, the shim will be a no-op and will simply forward the call to the client-provided pnpmfile. This has the benefit of not needing the pnpmfile to be copied into the `common/temp` directory, while allowing a common code path for both legacy and workspace installs.

## How it was tested

- Tested against a large workspaces monorepo to validate no performance regressions or errors in transformation or install logic. Confirmed that changes to pnpmfile will reflect in the up-to-date checks prior to install.
- Tested against a legacy Rush monorepo to validate no performance regressions or errors in transformation or install logic. Validated that pnpmfile still functions as it used to in this scenario.

### CODE REVIEW

File: apps/rush-lib/src/api/PackageJsonEditor.ts [hunk 1]
```diff
@@ -155,6 +155,10 @@ export class PackageJsonEditor {
     return new PackageJsonEditor(filename, object);
   }
 
+  public toObject(): IPackageJson {
```
Comment (octogonz) [inline apps/rush-lib/src/api/PackageJsonEditor.ts:158]: This is exposing a private data structure.  And because it is a shallow copy, it enables the caller to modify the data structure.

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 2]
```diff
@@ -1660,6 +1736,59 @@ export class RushConfiguration {
...
+          }
+        }
+
+        if (!ignoreVersion) {
+          let versionForDependency: Set<string> | undefined = versionsForDependencies.get(dependency.name);
+          if (!versionForDependency) {
+            versionForDependency = new Set<string>();
+            versionsForDependencies.set(dependency.name, versionForDependency);
+          }
+          versionForDependency!.add(dependency.version);
```
Comment (dmichon-msft) [inline apps/rush-lib/src/api/RushConfiguration.ts:1786]: You shouldn't need an assertion here

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 3]
```diff
@@ -263,12 +264,39 @@ export abstract class BaseInstallManager {
...
+    );
+
+    // Additionally, if they pulled an updated npm-shrinkwrap.json file from Git,
+    // then we can't skip this install
+    potentiallyChangedFiles.push(this.rushConfiguration.getCommittedShrinkwrapFilename(this.options.variant));
+
+    // Add common-versions.json file to the potentially changed files list.
+    potentiallyChangedFiles.push(this.rushConfiguration.getCommonVersionsFilePath(this.options.variant));
+
+    if (this.rushConfiguration.packageManager === 'pnpm') {
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:288]: Might also be worth doing a quick comparison of the lockfile in common/temp against the committed one, and if they are different, needs an install. Only works if --frozen-lockfile is used, though.

File: apps/rush-lib/src/logic/installManager/RushInstallManager.ts [hunk 4]
```diff
@@ -152,12 +153,11 @@ export class RushInstallManager extends BaseInstallManager {
     }
 
     // dependency name --> version specifier
-    const commonDependencies: Map<string, string> = InstallHelpers.collectPreferredVersions(
-      this.rushConfiguration,
-      {
-        explicitPreferredVersions: allExplicitPreferredVersions,
-        variant: this.options.variant
-      }
+    const commonDependencies: Map<string, string> = new Map();
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/installManager/RushInstallManager.ts:156]:
```suggestion
    const commonDependencies: Map<string, string. = new Map([...allExplicitPreferredVersions, ...this.rushConfiguration.getImplicitlyPreferredVersions(this.options.variant)]);
```

File: apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts [hunk 5]
```diff
@@ -1,53 +1,72 @@
...
-
 // Set the preferred versions on the dependency map. If the version on the map is an allowedAlternativeVersion
 // then skip it. Otherwise, check to ensure that the common version is a subset of the specified version. If
 // it is, then replace the specified version with the preferredVersion
-function setPreferredVersions(dependencies?: { [dependencyName: string]: string }): void {
+function setPreferredVersions(dependencies: { [dependencyName: string]: string } | undefined): void {
   for (const name of Object.keys(dependencies || {})) {
-    if (pnpmfileSettings.allPreferredVersions.hasOwnProperty(name)) {
-      const preferredVersion: string = pnpmfileSettings.allPreferredVersions[name];
+    if (settings.allPreferredVersions?.hasOwnProperty(name)) {
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts:53]: Can we convert this to a `Map<string, string>`? `new Map(Object.entries(obj))` will do the job.

File: apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts [hunk 6]
```diff
@@ -1,53 +1,72 @@
...
+      const preferredVersion: string = settings.allPreferredVersions[name];
       const version: string = dependencies![name];
-      if (pnpmfileSettings.allowedAlternativeVersions.hasOwnProperty(name)) {
+      if (settings.allowedAlternativeVersions?.hasOwnProperty(name)) {
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts:56]: Can we convert this to `Map<string, Set<string>>`?
e.g.
`new Map(Object.entries(allowedAlternativeVersions).map(([packageName, versions]) => [packageName, new Set(versions)]))`

File: apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts [hunk 7]
```diff
@@ -1,53 +1,72 @@
...
-          pnpmfileSettings.allowedAlternativeVersions[name];
+          settings.allowedAlternativeVersions[name];
         if (allowedAlternatives && allowedAlternatives.indexOf(version) > -1) {
           continue;
         }
       }
       let isValidRange: boolean = false;
       try {
-        isValidRange = !!semver.validRange(preferredVersion) && !!semver.validRange(version);
+        isValidRange = !!semver!.validRange(preferredVersion) && !!semver!.validRange(version);
```
Comment (dmichon-msft) [inline apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts:65]: Might make sense to compute this by constructing the semver.Range objects, since they'll get used again by subset and that way we don't construct them twice.

**Review by dmichon-msft — COMMENTED** [review]
Few opportunities to leverage constructs with more appropriate semantics

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts (hunk 3 above)
Comment (D4N14L) [reply apps/rush-lib/src/logic/base/BaseInstallManager.ts:288]: We write that prior to every install (meaning the last modify datetime will always be recent), and it's also intended to be hidden from the dev. Considering these two, I _think_ we should be good leaving this as-is.

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 8]
```diff
@@ -498,6 +499,9 @@ export class RushConfiguration {
   // Lazily loaded when the projectsByName() getter is called.
   private _projectsByName: Map<string, RushConfigurationProject> | undefined;
 
+  private _commonVersionsConfigurations: Map<string, CommonVersionsConfiguration> | undefined;
+  private _implicitlyPreferredVersions: Map<string, Map<string, string>> | undefined;
```
Comment (octogonz) [inline apps/rush-lib/src/api/RushConfiguration.ts:503]: `Map<string, Map<string, string>>` is a bit vague about what all the key/values are.

Comment (octogonz) [reply apps/rush-lib/src/api/RushConfiguration.ts:503]: Maybe we could call it `_implicitlyPreferredVersionsByVariant`?

But there should at least be a comment saying something like:
```js
// A map from a variant name to an implicitlyPreferredVersions table.  The key is an empty
// string for the default variant.  The implicitlyPreferredVersions table is map from a 
// package name to a SemVer range.
```

File: apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts [hunk 9]
```diff
@@ -1,53 +1,72 @@
 // Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 // See LICENSE in the project root for license information.
 
+import type { IPnpmShrinkwrapYaml } from './PnpmShrinkwrapFile';
```
Comment (octogonz) [inline apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts:4]: Add a comment explaining the weirdness about this file, which was not obvious to me:

```js
// The "rush install" command will copy this template to "common/temp/pnpmfile.js"
// so that it can implement Rush-specific features such as implicitly preferred versions.
// It reads its input data from "common/temp/pnpmfileSettings.json".
// The user's "common/config/rush/pnpmfile.js" gets copied to "common/temp/clientPnpmfile.js"
// and is called by the shim after Rush's transformations are applied.
//
// This file can use "import type" but otherwise should not reference any other modules.
```

File: apps/rush-lib/src/api/PackageJsonEditor.ts (hunk 1 above)
Comment (octogonz) [reply apps/rush-lib/src/api/PackageJsonEditor.ts:158]: Constructive suggestions:
- rename this to `saveToObject()` to clarify that nontrivial work is happening
- Call `_normalize()` to ensure the output is consistent with the editor state
- Deep clone the return value, so that modifications won't corrupt the `PackageJsonEditor`
- If possible, try to optimize the implementation in the common case where `PackageJsonEditor` is read but never modified (for example, maybe we can skip `_normalize()` entirely?)
- Write `/** */` docs that explain what this thing does

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 10]
```diff
@@ -1501,8 +1507,80 @@ export class RushConfiguration {
    * @param variant - The name of the current variant in use by the active command.
    */
   public getCommonVersions(variant?: string | undefined): CommonVersionsConfiguration {
-    const commonVersionsFilename: string = this.getCommonVersionsFilePath(variant);
-    return CommonVersionsConfiguration.loadFromFile(commonVersionsFilename);
+    if (!this._commonVersionsConfigurations) {
+      this._commonVersionsConfigurations = new Map();
+    }
+
+    const variantKey: string = variant || '';
```
Comment (iclanton) [inline apps/rush-lib/src/api/RushConfiguration.ts:1514]: Isn't the default variant called `default` (from the comments on `_commonVersionsConfigurations` and `_implicitlyPreferredVersions`)?

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 11]
```diff
@@ -1660,6 +1738,59 @@ export class RushConfiguration {
...
+        const localProject: RushConfigurationProject | undefined = this.getProjectByName(dependency.name);
+        if (localProject) {
+          // 2. If it's a symlinked local project, then it's not a candidate, because the package manager will
+          //    never even see it.
+          // However there are two ways that a local project can NOT be symlinked:
+          // - if the local project doesn't satisfy the referenced semver specifier; OR
+          // - if the local project was specified in "cyclicDependencyProjects" in rush.json
+          if (
+            semver.satisfies(localProject.packageJsonEditor.version, dependency.version) &&
+            !cyclicDependencies.has(dependency.name)
```
Comment (iclanton) [inline apps/rush-lib/src/api/RushConfiguration.ts:1776]:
```suggestion
            !cyclicDependencies.has(dependency.name) &&
            semver.satisfies(localProject.packageJsonEditor.version, dependency.version)
```

I'm sure `cyclicDependencies.has` is a cheaper call than `semver.satisfies`.

File: apps/rush-lib/src/logic/PackageJsonUpdater.ts [hunk 12]
```diff
@@ -124,13 +124,9 @@ export class PackageJsonUpdater {
...
     } = options;
 
-    const implicitlyPinned: Map<string, string> = InstallHelpers.collectImplicitlyPreferredVersions(
-      this._rushConfiguration,
-      {
-        variant
-      }
+    const implicitlyPinned: Map<string, string> = this._rushConfiguration.getImplicitlyPreferredVersions(
+      variant
     );
```
Comment (iclanton) [inline apps/rush-lib/src/logic/PackageJsonUpdater.ts:129]: This looks like a breaking API change.

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 13]
```diff
@@ -263,12 +264,39 @@ export abstract class BaseInstallManager {
...
+    // Based on timestamps, can we skip this install entirely?
+    const potentiallyChangedFiles: string[] = [];
+
+    // Consider the timestamp on the node_modules folder; if someone tampered with it
+    // or deleted it entirely, then we can't skip this install
+    potentiallyChangedFiles.push(
+      path.join(this.rushConfiguration.commonTempFolder, RushConstants.nodeModulesFolderName)
+    );
+
+    // Additionally, if they pulled an updated npm-shrinkwrap.json file from Git,
```
Comment (iclanton) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:281]:
```suggestion
    // Additionally, if they pulled an updated shrinkwrap file from Git,
```

Comment (iclanton) [reply apps/rush-lib/src/logic/base/BaseInstallManager.ts:281]: Unless this specifically refers to the NPM shrinkwrap.

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 14]
```diff
@@ -263,12 +264,39 @@ export abstract class BaseInstallManager {
...
+    potentiallyChangedFiles.push(this.rushConfiguration.getCommittedShrinkwrapFilename(this.options.variant));
+
+    // Add common-versions.json file to the potentially changed files list.
+    potentiallyChangedFiles.push(this.rushConfiguration.getCommonVersionsFilePath(this.options.variant));
+
+    if (this.rushConfiguration.packageManager === 'pnpm') {
+      // If the repo is using pnpmfile.js, consider that also
+      const pnpmFileFilename: string = this.rushConfiguration.getPnpmfilePath(this.options.variant);
+
+      if (FileSystem.exists(pnpmFileFilename)) {
```
Comment (iclanton) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:292]: What if the pnpmfile was deleted? Shouldn't that case be considered a change?

File: apps/rush-lib/src/logic/pnpm/PnpmfileConfiguration.ts [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+
+/**
+ * Loads PNPM's pnpmfile.js configuration, and invokes it to preprocess package.json files,
+ * optionally utilizing a pnpmfile shim to inject preferred versions.
+ */
+export class PnpmfileConfiguration {
+  private _context: IPnpmfileContext | undefined;
+
+  public constructor(rushConfiguration: RushConfiguration, pnpmfileShimOptions?: IPnpmfileShimOptions) {
+    if (rushConfiguration.packageManager === 'pnpm') {
```
Comment (iclanton) [inline apps/rush-lib/src/logic/pnpm/PnpmfileConfiguration.ts:32]: Should this throw if the package manager isn't PNPM?

File: apps/rush-lib/src/logic/PackageJsonUpdater.ts (hunk 12 above)
Comment (D4N14L) [reply apps/rush-lib/src/logic/PackageJsonUpdater.ts:129]: Only breaking in the sense that our `InstallHelpers` class doesn't have this method anymore. This class was used only by `PackageJsonUpdater` and the `InstallManager` for the package manager you're using, and this just shunts it into the RushConfiguration. If any 3rd parties too a dependency on `InstallHelpers`, access to `RushConfiguration` to call this method would have already been required. The options never supported anything other than `variant`

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts (hunk 14 above)
Comment (D4N14L) [reply apps/rush-lib/src/logic/base/BaseInstallManager.ts:292]: It would be considered a change. However, there's no way for us to know how to handle that without calling back to `git` unless we kept a list of files that "potentially changed" from the last time and diffed against it. Which is a good solution, but out of scope for this PR (all this change did was move the existing implementation)

File: apps/rush-lib/src/api/RushConfiguration.ts (hunk 10 above)
Comment (D4N14L) [reply apps/rush-lib/src/api/RushConfiguration.ts:1514]: Good catch, this is an out-of-date comment. Will update

**Comment by D4N14L** [comment]
@chengcyber could you try this fix for the mentioned issues and confirm it works as expected?

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 16]
```diff
@@ -1511,7 +1511,7 @@ export class RushConfiguration {
       this._commonVersionsConfigurations = new Map();
     }
 
-    const variantKey: string = variant || '';
+    const variantKey: string = variant || 'default';
```
Comment (iclanton) [inline apps/rush-lib/src/api/RushConfiguration.ts:1514]: Should this go in `RushConstants`?

**Review by iclanton — APPROVED** [review]

**Comment by iclanton** [comment]
Overall looks good to me, but admittedly I don't have a ton of background on this part of Rush.

File: apps/rush-lib/src/api/RushConfiguration.ts (hunk 16 above)
Comment (D4N14L) [reply apps/rush-lib/src/api/RushConfiguration.ts:1514]: Changed my mind on this. Going to use an empty string and update the comment. It's possible for us to conflict with a variant named `default` but not with an empty string, since you can't create a variant with that name.
