### PR TITLE
Fix #2868: Enable eslint config filename .eslintrc.cjs

### LINKED ISSUE #2868: [heft] Fails to run eslint when configured with ESM modules
## Summary

When a project is configured to use ESM modules (as opposed to CommonJS modules), ESLint won't be able to access the config file from `.eslintrc.js`, it has to have a `.cjs` extension. But when renaming the file to `.eslintrc.cjs` Heft doesn't detect that the user wants to use eslint (since it only checks for `.elintrc.js`)

## Repro steps

* Add `"type": "module"` to `package.json` in a project with Heft/ESLint configured
* Run `heft build`, receive an error from ESLint that requires the file to be called `.eslintrc.cjs`
* Rename the file to `.eslintrc.cjs`
* Run `heft build --verbose`, check that `[eslint]` is no longer run

## Details

Error when file is called `.eslintrc.js`:

```
[eslint] Using ESLint version 7.32.0
[typescript] I/O Write: 4.860208988189697ms (26 files)
 ---- Compile encountered an error (1515ms) ----
-------------------- Finished (1.673s) --------------------
Project: malmorestauranger-importer@0.1.0
Heft version: 0.36.3
Node version: v16.1.0
Error: Cannot read config file: /my-proj/.eslintrc.js
Error: Must use import to load ES Module: /my-proj/.eslintrc.js
require() of ES modules is not supported.
require() of /my-proj/.eslintrc.js from /my-proj/../..//common/temp/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .eslintrc.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /my-proj/package.json.

```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.36.3 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v16.1.0 |

### PR DESCRIPTION
**Pull request by jonasb**
## Summary

Fixes #2868 by adding support for `.eslintrc.cjs` in addition to `.eslint.js`. This is needed for projects configured with ESM modules (as opposed to CommonJS modules), i.e. `"type": "module"`. The filename is a limitation in Node/ESLint.

## Details

The Typescript plugin now checks for the existence of a `.eslintrc.cjs` file in addition to `.eslintrc.js`. AFAIK this doesn't affect any backwards compatibility. However, the website documentation could do with being updated.

## How it was tested

* Created new build-test `heft-node-everything-esm-module-test` which is a copy of `heft-node-everything` but configured with `"type": "module"`
* `rush build`
* `rush build --verbose -o heft-node-everything-esm-module-test` and check that `[eslint]` is included in the logs

### CODE REVIEW

File: apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts [hunk 1]
```diff
@@ -207,16 +207,26 @@ export class TypeScriptBuilder extends SubprocessRunnerBase<ITypeScriptBuilderCo
...
     this._tslintConfigFilePath = path.resolve(this._configuration.buildFolder, 'tslint.json');
-    this._eslintConfigFilePath = path.resolve(this._configuration.buildFolder, '.eslintrc.js');
     this._eslintEnabled = this._tslintEnabled =
       this._configuration.lintingEnabled && !this._configuration.watchMode; // Don't run lint in watch mode
 
     if (this._tslintEnabled) {
       this._tslintEnabled = this._cachedFileSystem.exists(this._tslintConfigFilePath);
     }
 
+    this._eslintConfigFilePath = path.resolve(this._configuration.buildFolder, '.eslintrc.js');
```
Comment (dmichon-msft) [inline apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts:217]: I'd suggest factoring this out into a `findESLintConfig` helper function and not repeatedly assign the value.

Comment (jonasb) [reply apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts]: Good suggestion. Extracted to a `_resolveEslintConfigFilePath()` method.

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
@jonasb thanks for fixing this issue!  I'll update the docs.
