### PR TITLE
[rush] Implement support for selecting a subset of dependencies to deploy

### LINKED ISSUE #1978: [rush] Give rush deploy the ability to select a subset of dependencies to copy over
search terms: docker, dockerfile, development only

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Possibly related to #1943 and builds on the same [reproduction repo](https://github.com/willsoto/rush-dep-repro). You can see the changes via [this commit.](https://github.com/willsoto/rush-dep-repro/commit/0489288b1bf6c32235e319ea3c875eff156812bf)

After our discussion on gitter @octogonz, I decided to follow your advice and copy over the entire topology into an image to see how far I could get understanding that things were still "broken" until #1942 and #1943 is resolved.

Here are the steps to reproduce:

1. `rush update`
2. `rush build`
3. `rush deploy`
4. `docker build . --tag rush-dep-repro:latest`
5. `docker run -it --rm rush-dep-repro:latest sh`

The expectation is that the following lines in the `Dockerfile` would copy over all the required files in order to symlink in the image correctly:

```Dockerfile
COPY ./common/deploy/common .
COPY ./common/deploy/deploy-metadata.json .
COPY ./common/deploy/create-links.js .
```

When you get into the container via `docker run`, you can `ls -lah node_modules` and notice that all of the symlinks are broken. 

This behavior is confirmed when you attempt to run `npm run start:prod` - it fails to run because it cannot find the first module it attempts to load.

**What is the expected behavior?**

I should be able to symlink `node_modules` in the image or have some other mechanism for deploying the app via docker using the `rush deploy` feature.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** pnpm
* **Tool Version:** 5.2.6
* **Node Version:** 12.x
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** MacOS (in the image Alpine)

### PR DESCRIPTION
**Pull request by willsoto**
- [x] Add new settings to template
- [x] Document new settings in `deploy-scenario.schema.json`
- [x] Implement `dependenciesToExclude`
- [x] Implement `additionalDependenciesToInclude`

Closes #1978

### CODE REVIEW

**Comment by willsoto** [comment]
@octogonz Here is a first pass at this. I've added some comments where I have questions

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 1]
```diff
@@ -133,85 +136,131 @@ export class DeployManager {
   private _collectFoldersRecursive(packageJsonFolderPath: string, deployState: IDeployState): void {
     const packageJsonRealFolderPath: string = FileSystem.getRealPath(packageJsonFolderPath);
 
-    if (!deployState.foldersToCopy.has(packageJsonRealFolderPath)) {
-      deployState.foldersToCopy.add(packageJsonRealFolderPath);
+    if (deployState.foldersToCopy.has(packageJsonRealFolderPath)) {
+      // we've already seen this folder
+      return;
+    }
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:142]: I de-dendeted this since the entire function was inside of this `if` block. I believe this change is functionally equivalent but if it isn't or you prefer to keep everything in this `if` block, I can revert this.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 2]
```diff
@@ -133,85 +136,131 @@ export class DeployManager {
...
+      optionalDependencyNames.add(name);
+    }
+
+    if (sourceFolderInfo && sourceFolderInfo.isRushProject) {
+      const projectSettings: IDeployScenarioProjectJson | undefined =
+        sourceFolderInfo && sourceFolderInfo.projectSettings;
+      const additionalDependenciesToInclude: string[] | undefined =
+        projectSettings && projectSettings.additionalDependenciesToInclude;
+      const dependenciesToExclude: string[] | undefined =
+        projectSettings && projectSettings.dependenciesToExclude;
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:187]: The typescript version for this app does not support nullish coalescing or optional chaining, hence all the `&&`. I am not sure how much of an undertaking it is to upgrade the TS version

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 3]
```diff
@@ -133,85 +136,131 @@ export class DeployManager {
...
+
+      this._applyDependencyFilters(
+        allDependencyNames,
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:190]: I end up mutating `allDependencyNames`, I hope that is okay

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 4]
```diff
@@ -540,9 +589,14 @@ export class DeployManager {
...
       const projectFolder: string = FileSystem.getRealPath(rushProject.projectFolder);
+      const projectSettings:
+        | IDeployScenarioProjectJson
+        | undefined = deployState.scenarioConfiguration.projectJsonsByName.get(rushProject.packageName);
+
       deployState.folderInfosByPath.set(projectFolder, {
         folderPath: projectFolder,
-        isRushProject: true
+        isRushProject: true,
+        projectSettings
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:599]: Thanks for the suggestion here. This was great 👍

File: apps/rush-lib/src/logic/deploy/Utils.ts [hunk 5]
```diff
@@ -0,0 +1,16 @@
+function escapeRegExp(literal: string): string {
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/Utils.ts:1]: I just put this all into a `Utils` file since I wasn't sure what the preference is for organizing these kinds of functions. Happy to move wherever you think is best.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 6]
```diff
@@ -133,85 +136,131 @@ export class DeployManager {
...
+          allDependencyNames.delete(dependency);
         }
-      }
-    }
+      });
+    });
+
+    additionalDependenciesToInclude.forEach((dependencyToInclude) => {
+      allDependencyNames.add(dependencyToInclude);
+    });
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:261]: I'm not sure if the logic needs to be more complicated than this. I assume we are going to leave it up to the individual to ensure that whatever additional packages they want are actually installed?

File: apps/rush-lib/src/logic/deploy/DeployManager.ts [hunk 7]
```diff
@@ -133,85 +136,131 @@ export class DeployManager {
...
-            }
-          }
+  private _applyDependencyFilters(
+    allDependencyNames: Set<string>,
+    additionalDependenciesToInclude: string[] = [],
+    dependenciesToExclude: string[] = []
+  ): Set<string> {
+    console.log();
+    console.log('Additional dependencies to include:', additionalDependenciesToInclude);
+    console.log('Dependencies to exclude:', dependenciesToExclude);
```
Comment (willsoto) [inline apps/rush-lib/src/logic/deploy/DeployManager.ts:249]: Not sure where/when it makes sense to log stuff. I added this for my local testing. Let me know if you'd like them removed or you'd like logging elsewhere.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 1 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts:142]: I like it -- it's more readable

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 2 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts:187]: We can't upgrade until we first integrate `downlevel-dts` into our toolchain.  (See https://github.com/microsoft/TypeScript/issues/36207 for details.)

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 3 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts:190]: I renamed it to `dependencyNamesToProcess` to clarify that it's no longer "all" dependencies

Comment (willsoto) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts]: I like that change. I considered making a new variable as well but couldn't decide on a name I liked 😂

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 2 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts]: I simplified the expression a bit also.

File: apps/rush-lib/src/logic/deploy/Utils.ts (hunk 5 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/Utils.ts:1]: I thought about some ways to make this code more reusable, but it seems better to make it a glob.  I'll come back and deal with it later in a different PR that is all about globs.  It shouldn't hold up your deployment feature.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 6 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts:263]: I tested this case, and the error message is pretty understandable, especially since you are reporting the extra included packages.

File: apps/rush-lib/src/logic/deploy/DeployManager.ts (hunk 7 above)
Comment (octogonz) [reply apps/rush-lib/src/logic/deploy/DeployManager.ts]: I agree this information is useful. I tuned up the logging so that nothing is logged when the list is empty.

**Comment by octogonz** [comment]
This was released with Rush 5.29.0

**Comment by willsoto** [comment]
@octogonz thanks for the review and quick turnaround!
