### PR TITLE
[rush] Allow skip if cache configured but disabled

### LINKED ISSUE #4394: [rush] v5.104.0 Breaks Incremental Build
## Summary

Rush v5.104.0 breaks incremental building, at least in our project setup. On and above that version, every rush build rebuilds all packages, regardless of changes on the filesystem. On v5.103.0 and below, incremental builds work as expected.

## Repro steps

- Install version 5.103.0
- Run `rush update && rush build && rush build`, builds are cached
- Update rush.json to 5.104.0
- Run `rush update && rush build && rush build`, all packages rebuilt

## Details

We use the build caching feature, but it's only enabled on CI. That means each package has a `rush-project.json` file with settings for the build command. I tested deleting these files, but it's not a fix.

Not sure what other information is relevant, happy to share more details.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.99.0 |
| `rushVersion` from rush.json? | 5.104.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | mac |
| Would you consider contributing a PR? | yes |
| Node.js version (`node -v`)? | v18.16.0 |

### PR DESCRIPTION
**Pull request by dmichon-msft**
## Summary
Ensure that if the build cache is configured, but the `buildCacheEnabled` flag is set to `false`, that the legacy skip detection logic is allowed to occur.

Fixes #4394 

## Details
The build cache (and thereby cobuilds) plugin will now only be applied if the build cache is both configured and enabled.

## How it was tested
Temporarily changed `buildCacheEnabled` to `false` in `common/config/rush/build-cache.json` and verified that skip detection occurred when running `rush build`.

## Impacted documentation
Any docs on build cache vs. skip.

### CODE REVIEW

File: libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts [hunk 1]
```diff
@@ -351,7 +351,8 @@ export class PhasedScriptAction extends BaseScriptAction<IPhasedCommandConfig> {
         customParametersByName.set(configParameter.longName, parserParameter);
       }
 
-      if (buildCacheConfiguration) {
+      if (buildCacheConfiguration?.buildCacheEnabled) {
```
Comment (D4N14L) [inline libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts:354]: We should probably have some test to ensure that this doesn't happen again, given the recent movement in the area

**Review by D4N14L — APPROVED** [review]

File: common/changes/@microsoft/rush/allow-skip-if-cache-disabled_2023-10-18-21-58.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Allow legacy skip behavior if build cache is configured but disabled. When running in verbose mode, log the type of incremental logic in use.",
```
Comment (octogonz) [inline common/changes/@microsoft/rush/allow-skip-if-cache-disabled_2023-10-18-21-58.json:5]: https://github.com/microsoft/rushstack-websites/pull/208 clarifies the "legacy skip" vs new behavior.

Comment (octogonz) [reply common/changes/@microsoft/rush/allow-skip-if-cache-disabled_2023-10-18-21-58.json:5]:
```suggestion
      "comment": "Allow the output preservation incremental strategy if the build cache is configured but disabled. When running in verbose mode, log the incremental strategy that is being used.",
```

File: libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts [hunk 3]
```diff
@@ -351,7 +351,8 @@ export class PhasedScriptAction extends BaseScriptAction<IPhasedCommandConfig> {
...
+        terminal.writeVerboseLine(`Incremental mode: build cache`);
```
Comment (octogonz) [inline libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts:355]:
```suggestion
        terminal.writeVerboseLine(`Incremental strategy: cache restoration`);
```

File: libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts [hunk 4]
```diff
@@ -361,12 +362,15 @@ export class PhasedScriptAction extends BaseScriptAction<IPhasedCommandConfig> {
           terminal
         }).apply(this.hooks);
       } else if (!this._disableBuildCache) {
+        terminal.writeVerboseLine(`Incremental mode: legacy skip detection`);
```
Comment (octogonz) [inline libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts:365]:
```suggestion
        terminal.writeVerboseLine(`Incremental strategy: output preservation`);
```

File: libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts [hunk 5]
```diff
@@ -361,12 +362,15 @@ export class PhasedScriptAction extends BaseScriptAction<IPhasedCommandConfig> {
...
         // Explicitly disabling the build cache also disables legacy skip detection.
         new LegacySkipPlugin({
           terminal,
           changedProjectsOnly,
           isIncrementalBuildAllowed: this._isIncrementalBuildAllowed
         }).apply(this.hooks);
+      } else {
+        terminal.writeVerboseLine(`Incremental mode: disabled`);
```
Comment (octogonz) [inline libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts:373]:
```suggestion
        terminal.writeVerboseLine(`Incremental strategy: none (full rebuild)`);
```

**Review by octogonz — APPROVED** [review]

File: libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts (hunk 1 above)
Comment (octogonz) [reply libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts:354]: I'm okay with doing that in a separate PR, if it enables us to get this fix released more quickly.

**Comment by octogonz** [comment]
🚀 Released with Rush 5.109.2
