### PR TITLE
[eslint-patch] add check for invalid module path to fallback to relative path when loading eslint modules for nextjs

### LINKED ISSUE #4172: prettier-eslint fails to load nextjs eslint module with: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
https://github.com/microsoft/rushstack/blame/9839839f35ff5239edfd134665b47e9b8083b722/eslint/eslint-patch/src/modern-module-resolution.ts#L234

this is the source of the issue. 

the error being thrown is `TypeError [ERR_INVALID_ARG_VALUE]` so in the catch where `isModuleResolutionError` is checked it returns false (different error type) and it never reaches trying to load the module via `relativePath`.

the solution [listed in this issue](https://github.com/prettier/prettier-eslint-cli/issues/434#issuecomment-1207331852) works perfectly. 

proposal to either add an additional check in the catch or to use ` return originalResolve.call(this, moduleName, ctx.filePath || relativePath);` as proposed.

### PR DESCRIPTION
**Pull request by ci-vamp**
## Summary

fixes #4172 

## Details

using `prettier-eslint` with the `nextjs` eslint module fails due to the module path loading. 

the error being thrown is `TypeError [ERR_INVALID_ARG_VALUE]` so in the catch where `isModuleResolutionError` is checked it returns false (different error type) and it never reaches trying to load the module via `relativePath`.

the solution [listed in this issue](https://github.com/prettier/prettier-eslint-cli/issues/434#issuecomment-1207331852) works perfectly. 

this PR fixes the issue by introducing another error checker `isInvalidImporterPath` looking for this type of error. if either `isModuleResolutionError` or `isInvalidImporterPath` are true then it will use the `relativePath`.

fully backwards compatible by simply introducing an additional branch of logic. 

## How it was tested

ran `prettier-eslint` and it was fixed. no effect on any existing logic, just adds an additional branch of logic for this specific issue.

## Impacted documentation

no change. followed code style for introducing fix.

### CODE REVIEW

**Review by dmichon-msft — APPROVED** [review]
I admit I'm curious to know why the importerPath value is an empty string, but this approach looks fine.

File: eslint/eslint-patch/src/modern-module-resolution.ts [hunk 1]
```diff
@@ -13,6 +13,13 @@ const fs = require('fs');
 const isModuleResolutionError: (ex: unknown) => boolean = (ex) =>
   typeof ex === 'object' && !!ex && 'code' in ex && (ex as { code: unknown }).code === 'MODULE_NOT_FOUND';
 
+// error: "The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''"
+const isInvalidImporterPath: (ex: unknown) => boolean = (ex) =>
+  typeof ex === 'object' &&
+  !!ex &&
+  'code' in ex &&
+  (ex as { code: unknown }).code === 'ERR_INVALID_ARG_VALUE';
```
Comment (iclanton) [inline eslint/eslint-patch/src/modern-module-resolution.ts:21]:
```suggestion
  (ex as { code: unknown } | undefined)?.code === 'ERR_INVALID_ARG_VALUE';
```

**Comment by octogonz** [comment]
> hey @dmichon-msft @iclanton i think there was a change made from my PR that i didnt notice before merging. this fix needed to add the check for invalid importer path
> 
> ```ts
> if (isModuleResolutionError(e) || isInvalidImporterPath(e)) {
>                             return originalResolve.call(this, moduleName, relativeToPath);
>                         }
> ```
> 
> in the `ESLint 7.x || 8.x` block. i think during review it was moved to the `ESLint 6.x` block. i dont see any harm in leaving it in 6.x but it doesnt fix the issue unless its added to the other block as well.
> 
> can i open a new PR to add it there?

Fixed in https://github.com/microsoft/rushstack/pull/4205
