### PR TITLE
[rush] Fix Rush to use new .pnpmfile.cjs filename in PNPM 6

### LINKED ISSUE #2629: [rush] pnpm version 6 renames `pnpmfile.js` to `.pnpmfile.cjs` but rush doesn't
## Summary

Since pnpm version 6, the convention for pnpm hooks filename has changed from `pnpmfile.js` to `.pnpmfile.cjs` but rush doesn't output such file inside `common/temp/`, so the hooks never get executed.

## Repro steps

0. Create a Rush project, using `useWorkspaces: true` and `pnpm` version `6.0.2`.
0. Add a hook with a message inside `common/rush/pnpmfile.js`, for example:
  ```js
function readPackage(packageJson, context) {
    context.log('Hook for: ' + packageJson.name)
    return packageJson
}
  ```
2. Execute `rush update --full --recheck`

**Expected result:** The console outputs the `Hook from: XXX` messages

**Actual result:** The console doesn't output our messages (hooks are not executed)

## Details

This issue should be easy to fix:
> If pnpm version is >= 6.0.0 then the automatically generated file should be named `.pnpmfile.cjs` instead of `pnpmfile.js`
In order to support multiple pnpm versions with the same file, it could also output an adapter file as `.pnpmfile.cjs`:
```js
// .pnpmfile.cjs
module.exports = require('./pnpmfile')
```

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.36.2 |
| `rushVersion` from rush.json? | 5.36.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | windows 10 |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.16.1 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

In preparing to use PNPM 6, it was determined that the new `.pnpmfile.cjs` filename is required when copying in the pnpmfile or creating our own shim pnpmfile in workspaces. This change updates Rush to copy `.pnpmfile.cjs` for PNPM 6 and above, and continues to use `pnpmfile.js` for below. Fixes #2629 

## How it was tested

Tested by performing install and validating that `pnpm-lock.yaml` changes are included and correct in PNPM 6-enabled monorepo.

### CODE REVIEW

**Review by dmichon-msft — APPROVED** [review]

File: apps/rush-lib/src/api/RushConfiguration.ts [hunk 1]
```diff
@@ -928,6 +929,15 @@ export class RushConfiguration {
     return tempNamesByProject;
   }
 
+  /**
+   * Returns the pnpmfile filename for the version of PNPM supplied.
+   */
+  private static _getPnpmfileFilename(packageManagerToolVersion: string): string {
```
Comment (iclanton) [inline apps/rush-lib/src/api/RushConfiguration.ts:935]: Seems like this should be in a utility somewhere instead of in `RushConfiguration`

File: apps/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 2]
```diff
@@ -392,7 +393,7 @@ export abstract class BaseInstallManager {
       const committedPnpmFilePath: string = this._rushConfiguration.getPnpmfilePath(this._options.variant);
       const tempPnpmFilePath: string = path.join(
         this._rushConfiguration.commonTempFolder,
-        RushConstants.pnpmfileFilename
+        path.basename(committedPnpmFilePath)
```
Comment (iclanton) [inline apps/rush-lib/src/logic/base/BaseInstallManager.ts:396]: Would it make more sense to refactor `getPnpmfilePath` in `RushConfiguration` to return the filename instead of the whole path so we don't need to peel the path back apart here?

File: apps/rush-lib/src/logic/installManager/RushInstallManager.ts [hunk 3]
```diff
@@ -78,7 +78,8 @@ export class RushInstallManager extends BaseInstallManager {
    * @override
    */
   public async prepareCommonTempAsync(
-    shrinkwrapFile: BaseShrinkwrapFile | undefined
+    shrinkwrapFile: BaseShrinkwrapFile | undefined,
+    variant: string | undefined
```
Comment (iclanton) [inline apps/rush-lib/src/logic/installManager/RushInstallManager.ts:82]: Unused?

File: common/changes/@microsoft/rush/user-danade-FixPnpmfile_2021-04-21-22-03.json [hunk 4]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Fix support for PNPM 6 and use .pnpmfile.cjs",
```
Comment (iclanton) [inline common/changes/@microsoft/rush/user-danade-FixPnpmfile_2021-04-21-22-03.json:5]:
```suggestion
      "comment": "Fix support for pnpmfile in PNPM 6.",
```

File: apps/rush-lib/src/api/RushConfiguration.ts (hunk 1 above)
Comment (D4N14L) [reply apps/rush-lib/src/api/RushConfiguration.ts:935]: The idea of keeping it here is that in general, you should be obtaining the path to the file from `RushConfiguration`, similar to how we get the shrinkwrap path, since you will also need the PNPM version which already comes from `RushConfiguration`.

File: apps/rush-lib/src/logic/installManager/RushInstallManager.ts (hunk 3 above)
Comment (D4N14L) [reply apps/rush-lib/src/logic/installManager/RushInstallManager.ts:82]: Yeah, not necessary

**Review by iclanton — APPROVED** [review]
