### PR TITLE
[package-extractor] Fix `.bin` folder extraction when using the `default` link creation mode

### LINKED ISSUE #4961: [rush] `deploy` command no longer copies the `node_modules/.bin`
## Repro steps

Reproducible repository: https://github.com/koen-dev/rush-deploy-node-modules-bin-issue

### What were you trying to accomplish?

I was trying to use `rush deploy` to set up a deployment for a project, which includes scripts for database migration using the Prisma CLI.

### What action did you perform that ran into trouble?

After running `rush deploy`, I tried executing `rushx migrate` in the `common/deploy/app1` folder.

### What went wrong?

The command errored out with `'prisma' not found`, indicating that the Prisma CLI wasn't available. I noticed that the `common/deploy/app1/node_modules` directory no longer contains the `.bin` folder, which seems to be the root of the problem. This behavior differs from version `5.134.0`, where the `.bin` folder was present after deploying.

  **Expected result:** Running `rushx migrate` in the `common/deploy/app1` folder should successfully execute the Prisma migration script.

  **Actual result:** Running `rushx migrate` results in an error stating `'prisma' not found` due to the missing `.bin` folder in `common/deploy/app1/node_modules`.

## Details

It looks to be introduced in version `5.135.0` and any later version also contains the same issue.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.135.0 |
| `rushVersion` from rush.json? | 5.135.0 |
| `useWorkspaces` from pnpm-config.json? | true |
| Operating system? | Mac & Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 18.20.4 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Fixes #4961 

## Details

The `.bin` links were previously created after the realization of the deployed project `node_modules` folder. Changes in #4924 were made to centralize and simplify the handling of assets in a deployment, but did not take this requirement into account. This meant that the `.bin` links were not created in the deployed project's `node_modules` folder. This change moves creation of the `.bin` links to after the creation of the `node_modules` folder, but before the assets are finalized, which ensures that the `.bin` links are created and included in the generated archive (if one was requested).

## How it was tested

Locally against repro provided in issue.

### CODE REVIEW

File: libraries/package-extractor/src/PackageExtractor.ts [hunk 1]
```diff
@@ -383,7 +384,21 @@ export class PackageExtractor {
...
-    await state.assetHandler.finalizeAsync();
+    await state.assetHandler.finalizeAsync({
+      onAfterExtractSymlinksAsync: async () => {
+        // We need the symlinks to be created before attempting to create the bin links, since it requires
+        // the node_modules folder to be realized. While we're here, we may as well perform some specific
+        // link creation tasks and write the extractor-metadata.json file before the asset handler finalizes.
+        if (linkCreation === 'default') {
+          await this._makeBinLinksAsync(options, state);
+        } else if (linkCreation === 'script') {
+          await this._writeCreateLinksScriptAsync(options, state);
```
Comment (iclanton) [inline libraries/package-extractor/src/PackageExtractor.ts:395]: This scenario handles the `.bin` folders correctly?

**Review by iclanton — APPROVED** [review]

File: libraries/package-extractor/src/PackageExtractor.ts (hunk 1 above)
Comment (D4N14L) [reply libraries/package-extractor/src/PackageExtractor.ts:395]: We don't create bin folders for non-default modes, no. This has to do with having the node_modules folder being required in the deployment output folder, which the other mode (script mode) does not create.
