### PR TITLE
[rush] Fix last install flag not updating autoinstallers

### LINKED ISSUE #2987: [rush] Autoinstaller broken if "node_modules" folder is deleted manually
## Summary

After the  `ua-parser-js` security incident, developers manually deleted the `node_modules` folders in their working folder.  Someone reported that the Prettier autoinstaller was broken afterwards.

## Repro steps

1. Clone `https://github.com/microsoft/rushstack`
2. Invoke `rush prettier` which installs `common/autoinstallers/rush-prettier`
3. Manually delete the folder `common/autoinstallers/rush-prettier/node_modules`
4. Try to use `rush prettier`  -- the command now fails because the `node_modules` folder is not restored.

## Details

The problem is that Rush tracks installation status using the file `common/autoinstallers/rush-prettier/.rush/temp/last-install.flag`; as long as this file appears up to date, Rush will assume that the `node_modules` folder is in good shape.

👉 This conflicts with commonplace intuition that `node_modules` folders are always safe to delete.

Possible solutions:
1. Move `<autoinstaller>/.rush/temp/last-install.flag` to be `<autoinstaller>/node_modules/.rush/last-install.flag` so that it gets deleted if the `node_modules` folder is deleted; OR
2. Improve the [_prepareAutoinstallerName()](https://github.com/microsoft/rushstack/blob/a13865bef9a20dab28c044be3504c7326bfe94b1/apps/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts#L91) logic to validate the `node_modules` folder somehow.  For example, ensuring that the folder exists and is not empty.  Or recording a hash if its `pnpm-lock.yaml` maybe.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | "5.55.0" |
| `rushVersion` from rush.json? |"5.55.0" |

CC @DavidRieman @chengcyber

### PR DESCRIPTION
**Pull request by william2958**
## Summary

Fixes #2987 

(summary from issue)
The problem is that Rush tracks installation status using the file common/autoinstallers/rush-prettier/.rush/temp/last-install.flag; as long as this file appears up to date, Rush will assume that the node_modules folder is in good shape.

👉 This conflicts with commonplace intuition that node_modules folders are always safe to delete.

## Details
We now use a similar outdated check to the install check in [BaseInstallManager.ts](https://github.com/microsoft/rushstack/blob/3516f99350aea88245a9d40fa1e82d3069e92c06/apps/rush-lib/src/logic/base/BaseInstallManager.ts#L285-L289) to detect if the node_modules folder is outdated or missing

## How it was tested
Manually tested with steps provided in the issue

### CODE REVIEW

File: libraries/rush-lib/src/logic/Autoinstaller.ts [hunk 1]
```diff
@@ -109,10 +109,15 @@ export class Autoinstaller {
...
-    if (!lastInstallFlag.isValid() || lock.dirtyWhenAcquired) {
-      // Example: ../common/autoinstallers/my-task/node_modules
-      const nodeModulesFolder: string = path.join(autoinstallerFullPath, 'node_modules');
-
+    // Example: ../common/autoinstallers/my-task/node_modules
+    const nodeModulesFolder: string = path.join(autoinstallerFullPath, RushConstants.nodeModulesFolderName);
+    const isLastInstallFlagDirty: boolean =
+      !lastInstallFlag.isValid() ||
+      !Utilities.isFileTimestampCurrent(FileSystem.getStatistics(lastInstallFlag.path).mtime, [
+        nodeModulesFolder
```
Comment (octogonz) [inline libraries/rush-lib/src/logic/Autoinstaller.ts:117]: Tools sometimes create additional files in the `node_modules` folder after installation completes.  One example is the `node_modules/.cache` folder that is created by some packages.  Creating a new file or folder under `node_modules` may reset its `mtime` (depending on the filesystem).

Maybe it would be safer to test `FileSystem.exists()` instead of `isFileTimestampCurrent()`.

File: common/changes/@microsoft/rush/will-fix-last-install-flag_2022-09-13-21-16.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Autodetect if an autoinstaller's flag is outdated or node_modules folder is missing",
```
Comment (octogonz) [inline common/changes/@microsoft/rush/will-fix-last-install-flag_2022-09-13-21-16.json:5]:
```suggestion
      "comment": "Fix an error that ocurred if an autoinstaller's  \"node_modules\" folder was manually deleted (GitHub #2987)",
```

Change messages should try to describe _what_ was solved rather than _how_ we solved it.  (See [this doc](https://rushjs.io/pages/best_practices/change_logs/) for some guidance.)

File: libraries/rush-lib/src/logic/Autoinstaller.ts (hunk 1 above)
Comment (william2958) [reply libraries/rush-lib/src/logic/Autoinstaller.ts:117]: So would a best general solution that works for most cases just be to check if the node_modules folder exists? Or in the case that it exists and is empty it at least tries to re-install the dependencies?

Comment (octogonz) [reply libraries/rush-lib/src/logic/Autoinstaller.ts:117]: If we wanted to catch the case where someone did `rm -Rf node_modules/*` instead of `rm -Rf node_modules`, maybe a safe/robust approach would be for Rush itself to write a file into that folder.  Generate something like this around line 129 (if the file doesn't already exist):

**node_modules/rush-autoinstaller.log**
```
If this file is deleted, Rush will assume that the node_modules folder has been
cleaned and will reinstall it.
```

Note that the filename cannot be a hidden file (e.g. `.rush-autoinstaller.log` because when executing `rm -Rf *`, the shell does not expand `*` to include hidden files).

@william2958 I'll leave it up to you whether to implement such a feature.  As-is, your PR would already solve the original problem that we encountered, so this is somewhat extra feature creep. 😄

Comment (william2958) [reply libraries/rush-lib/src/logic/Autoinstaller.ts]: Although, re-reading the original issue, this solution may conflict with the node installation issue brought up in this comment: https://github.com/microsoft/rushstack/issues/2987#issuecomment-952020145 , as the log file would still be wiped and cause the re-install of the plugins

Comment (dmichon-msft) [reply libraries/rush-lib/src/logic/Autoinstaller.ts]: I think the safest option is to record the mtime of node_modules in lastinstall.flag, and if they are different, let the package manager sort it out. The package managers have their own internal checks for if node_modules is up to date that will be more comprehensive than anything we could do.

Comment (octogonz) [reply libraries/rush-lib/src/logic/Autoinstaller.ts]: @dmichon-msft In my example above, suppose that the CLI tool writes to the `node_modules/.cache` folder every time it is invoked.  In this case, the package manager would have to be invoked every time the CLI tool is invoked. It's not invalid, but it could be inefficient.

**Review by octogonz — APPROVED** [review]

File: libraries/rush-lib/src/logic/Autoinstaller.ts [hunk 3]
```diff
@@ -109,10 +109,13 @@ export class Autoinstaller {
       rushJsonFolder: this._rushConfiguration.rushJsonFolder
     });
 
-    if (!lastInstallFlag.isValid() || lock.dirtyWhenAcquired) {
-      // Example: ../common/autoinstallers/my-task/node_modules
-      const nodeModulesFolder: string = path.join(autoinstallerFullPath, 'node_modules');
+    // Example: ../common/autoinstallers/my-task/node_modules
+    const nodeModulesFolder: string = path.join(autoinstallerFullPath, RushConstants.nodeModulesFolderName);
```
Comment (iclanton) [inline libraries/rush-lib/src/logic/Autoinstaller.ts:113]:
```suggestion
    const nodeModulesFolder: string = `${autoinstallerFullPath}/${RushConstants.nodeModulesFolderName}`;
```

File: libraries/rush-lib/src/logic/Autoinstaller.ts [hunk 4]
```diff
@@ -109,10 +109,13 @@ export class Autoinstaller {
...
+    const isLastInstallFlagDirty: boolean =
+      !lastInstallFlag.isValid() ||
+      !FileSystem.exists(path.join(nodeModulesFolder, 'rush-autoinstaller.log'));
```
Comment (iclanton) [inline libraries/rush-lib/src/logic/Autoinstaller.ts:116]:
```suggestion
      !FileSystem.exists(`${nodeModulesFolder}/${rush-autoinstaller.log}`);
```

File: libraries/rush-lib/src/logic/Autoinstaller.ts [hunk 5]
```diff
@@ -133,6 +136,14 @@ export class Autoinstaller {
       // Create file: ../common/autoinstallers/my-task/.rush/temp/last-install.flag
       lastInstallFlag.create();
 
+      FileSystem.writeFile(
+        path.join(nodeModulesFolder, 'rush-autoinstaller.log'),
```
Comment (iclanton) [inline libraries/rush-lib/src/logic/Autoinstaller.ts:140]:
```suggestion
        `${nodeModulesFolder}/rush-autoinstaller.flag`,
```

Stick this in a variable as it's used above.

File: libraries/rush-lib/src/logic/Autoinstaller.ts [hunk 6]
```diff
@@ -133,6 +136,14 @@ export class Autoinstaller {
...
+        'If this file is deleted, Rush will assume that the node_modules folder has been cleaned and will reinstall it.',
+        {
+          ensureFolderExists: false
+        }
```
Comment (iclanton) [inline libraries/rush-lib/src/logic/Autoinstaller.ts:144]:
```suggestion
        'If this file is deleted, Rush will assume that the node_modules folder has been cleaned and will reinstall it.'
```

`ensureFolderExists: false` is the default.

**Review by iclanton — APPROVED** [review]

File: libraries/rush-lib/src/logic/Autoinstaller.ts (hunk 4 above)
Comment (iclanton) [reply libraries/rush-lib/src/logic/Autoinstaller.ts:116]: `path.join` is somewhat slow, and Windows doesn't care if you use forward or backslashes, so in cases where the parameters are well-known, it's faster to just concatenate the parts of the path with `/`es
