### PR TITLE
[rush] malformed package.json by explicitly setting jsonSyntax to strict

### LINKED ISSUE #4811: [rush] Rush add causes malformed package.json if the package.json does not have "dependencies" field yet and have >1 entries in "contributors" field
## Summary

If there are >1 contributors in package.json and there is no dependencies yet, running `rush add --package <pkg-name>` will cause the package.json to be malformed.

## Repro steps

https://github.com/kenrick95/rush-repro-rush-add-malformed-package-json

Check `pkg-a/package.json`:

```json
{
  "name": "pkg-a",
  "private": true,
  "version": "0.0.0",
  "contributors": [
    {
      "name": "person-a",
      "email": "example-a@example.org"
    },
    {
      "name": "person-b",
      "email": "example-b@example.org"
    }
  ]
}
```

Repro:

```sh
cd pkg-a
rush add --package meow
```

  **Expected result:** 

- A valid JSON in package.json
- rush add runs successfully

```json
{
  "name": "pkg-a",
  "private": true,
  "version": "0.0.0",
  "contributors": [
    {
      "name": "person-a",
      "email": "example-a@example.org"
    },
    {
      "name": "person-b",
      "email": "example-b@example.org"
    }
  ],
  "dependencies": {
    "meow": "~13.2.0"
  }
}
```

  **Actual result:** 

- Malformed JSON in package.json
- rush add failed

```json
{
  "name": "pkg-a",
  "private": true,
  "version": "0.0.0",
  "contributors": [
    {
      "name": "person-a",
      "email": "example-a@example.org"
    },
    {
      "name": "person-b",
      "email": "example-b@example.org"
    }
  ],
  "dependencies": {
    "meow": "~13.2.0",
  }
}
```

```log
➜  pkg-a git:(master) ✗ rush add --package meow
Found configuration in /path/to/repo/rush-repro-rush-add/rush.json


Rush Multi-Project Build Tool 5.124.6 - https://rushjs.io
Node.js version is 18.20.3 (LTS)

Found configuration in /path/to/repo/rush-repro-rush-add/rush.json

Starting "rush add"


Determining new version for dependency: meow
No version selector was specified, so the version will be determined automatically.

Trying to acquire lock for pnpm-8.15.8
Acquired lock for pnpm-8.15.8
Found pnpm version 8.15.8 in /path/to/user/.rush/node-v18.20.3/pnpm-8.15.8

Symlinking "/path/to/repo/rush-repro-rush-add/common/temp/pnpm-local"
  --> "/path/to/user/.rush/node-v18.20.3/pnpm-8.15.8"
The "ensureConsistentVersions" policy is NOT active, so we will assign the latest version.

Querying NPM registry for latest version of "meow"...

Found latest version: 13.2.0

Assigning version "~13.2.0" for "meow".
Updating projects to use meow@~13.2.0

Wrote/path/to/repo/rush-repro-rush-add/pkg-a/package.json

Running "rush update"

Checking Git policy for this repository.

Trying to acquire lock for pnpm-8.15.8
Acquired lock for pnpm-8.15.8
Found pnpm version 8.15.8 in /path/to/user/.rush/node-v18.20.3/pnpm-8.15.8

Symlinking "/path/to/repo/rush-repro-rush-add/common/temp/pnpm-local"
  --> "/path/to/user/.rush/node-v18.20.3/pnpm-8.15.8"
Transforming /path/to/repo/rush-repro-rush-add/common/config/rush/.npmrc
  --> "/path/to/repo/rush-repro-rush-add/common/temp/.npmrc"

Updating workspace files in /path/to/repo/rush-repro-rush-add/common/temp
Copying "/path/to/repo/rush-repro-rush-add/common/config/rush/pnpm-lock.yaml"
  --> "/path/to/repo/rush-repro-rush-add/common/temp/pnpm-lock.yaml"
Copying "/path/to/repo/rush-repro-rush-add/common/config/rush/pnpm-lock.yaml"
  --> "/path/to/repo/rush-repro-rush-add/common/temp/pnpm-lock-preinstall.yaml"

Checking installation in "/path/to/repo/rush-repro-rush-add/common/temp"

Deleting files from /path/to/repo/rush-repro-rush-add/common/temp/node_modules

Running "pnpm install" in /path/to/repo/rush-repro-rush-add/common/temp

 ERR_PNPM_JSON_PARSE  Unexpected token "}" (0x7D) in JSON at position 287 while parsing near "...meow\": \"~13.2.0\",\n  }\n}\n" in /path/to/repo/rush-repro-rush-add/pkg-a/package.json 

  15 |   "dependencies": {
  16 |     "meow": "~13.2.0",
> 17 |   }
     |   ^
  18 | }
  19 |


The command failed:
 /path/to/repo/rush-repro-rush-add/common/temp/pnpm-local/node_modules/.bin/pnpm install --store /path/to/repo/rush-repro-rush-add/common/temp/pnpm-store --config.cacheDir=/path/to/repo/rush-repro-rush-add/common/temp/pnpm-store --config.stateDir=/path/to/repo/rush-repro-rush-add/common/temp/pnpm-store --no-prefer-frozen-lockfile --no-strict-peer-dependencies --config.auto-install-peers=false --config.resolutionMode=highest --config.ignoreCompatibilityDb --recursive --link-workspace-packages false --reporter default
ERROR: Error: The command failed with exit code 1
Giving up after 1 attempts


ERROR: The command failed with exit code 1
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.117.8 |
| `rushVersion` from rush.json? |  5.129.6 |
| `useWorkspaces` from rush.json? |  Yes |
| Operating system? |  Mac |
| Would you consider contributing a PR? |  Yes |
| Node.js version (`node -v`)? |  18.20.3 |

### PR DESCRIPTION
**Pull request by kenrick95**
## Summary

Attempt to fix #4811

## Details

I investigated and found out that when saving JSON with "jju.update", it always use Json5 mode. This may cause issue when updating things that expect strict JSON like package.json.

So the fix here is to pass a `jsonSyntax` option to let `PackageJsonEditor` use that `JsonSyntax.Strict` mode.

## How it was tested

I build locally and it works on the repro: https://github.com/kenrick95/rush-repro-rush-add-malformed-package-json

Screenshot 2024-06-27 at 10 46 12

## Impacted documentation

- IJsonFileStringifyOptions adds "jsonSyntax" as an option. Is that okay?

### CODE REVIEW

File: libraries/node-core-library/src/JsonFile.ts [hunk 1]
```diff
@@ -345,17 +345,30 @@ export class JsonFile {
...
+        break;
+    }
+
     let stringified: string;
 
     if (previousJson !== '') {
       // NOTE: We don't use mode=json here because comments aren't allowed by strict JSON
       stringified = jju.update(previousJson, newJsonObject, {
-        mode: JsonSyntax.Json5,
+        mode: explicitMode ? explicitMode : JsonSyntax.Json5,
```
Comment (dmichon-msft) [inline libraries/node-core-library/src/JsonFile.ts:366]:
```suggestion
        mode: explicitMode ?? JsonSyntax.Json5,
```

File: libraries/node-core-library/src/JsonFile.ts [hunk 2]
```diff
@@ -345,17 +345,30 @@ export class JsonFile {
...
         indent: 2
       });
     } else if (options.prettyFormatting) {
       stringified = jju.stringify(newJsonObject, {
-        mode: 'json',
+        mode: explicitMode ? explicitMode : 'json',
```
Comment (dmichon-msft) [inline libraries/node-core-library/src/JsonFile.ts:371]:
```suggestion
        mode: explicitMode ?? 'json',
```

File: libraries/rush-lib/src/api/PackageJsonEditor.ts [hunk 3]
```diff
@@ -308,7 +308,10 @@ export class PackageJsonEditor {
     if (this._modified) {
       this._modified = false;
       this._sourceData = this._normalize(this._sourceData);
-      JsonFile.save(this._sourceData, this.filePath, { updateExistingFile: true });
+      JsonFile.save(this._sourceData, this.filePath, {
+        updateExistingFile: true,
+        jsonSyntax: JsonSyntax.Strict
+      });
```
Comment (dmichon-msft) [inline libraries/rush-lib/src/api/PackageJsonEditor.ts:314]: Note that strictly speaking there is minimal benefit to using the `JsonFile` API for saving `package.json` files over using `FileSystem.writeFile()` and `JSON.stringify()` (the latter is faster, in fact), when the output needs to be strict JSON. I guess this allows for cosmetic newlines?

Comment (kenrick95) [reply libraries/rush-lib/src/api/PackageJsonEditor.ts:314]: I think this will try to preserve the formatting, while JSON.stringify will reformat with the format that we specify? Although in the end it might not matter if the user has prettier configured (but that's just my assumption)

Comment (kenrick95) [reply libraries/rush-lib/src/api/PackageJsonEditor.ts:314]: Okay if I changed that block of code to this:

```js
      let stringified = JSON.stringify(this._sourceData, undefined, 2);
      stringified = Text.ensureTrailingNewline(stringified);
      FileSystem.writeFile(this.filePath, stringified);
```

When I tried this, one side effect of this is that when I run `rush add -p <pkg-name>`, it adds the dependencies alphabetically (i.e. actually fixing #2115 and maybe it's the more elegant solution to #2457)

What do you think @dmichon-msft  @chengcyber @iclanton ?

Comment (D4N14L) [reply libraries/rush-lib/src/api/PackageJsonEditor.ts:314]: @kenrick95 we've had the discussion about alphabetizing JSON files a few times in the past, and it's certainly something we would like to introduce at some point as an option (but not mandatory). I would consider it out of the scope of this PR though, and you can probably leave JSON file writing as-is for now.

**Review by D4N14L — APPROVED** [review]

File: common/changes/@microsoft/rush/kenrick-fix-rush-add_2024-06-27-02-39.json [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Fix malformed package.json by explicitly setting jsonSyntax to strict",
```
Comment (iclanton) [inline common/changes/@microsoft/rush/kenrick-fix-rush-add_2024-06-27-02-39.json:5]:
```suggestion
      "comment": "Fix an issue where running `rush add` in a project can generate a `package.json` file that uses JSON5 syntax. Package managers expect strict JSON.",
```

File: common/changes/@rushstack/node-core-library/kenrick-fix-rush-add_2024-06-27-02-39.json [hunk 5]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/node-core-library",
+      "comment": "Accept jsonSyntax option at save method to avoid malformed package.json",
```
Comment (iclanton) [inline common/changes/@rushstack/node-core-library/kenrick-fix-rush-add_2024-06-27-02-39.json:5]:
```suggestion
      "comment": "Add support for the `jsonSyntax` option to the `JsonFile.save`, `JsonFile.saveAsync`, and `JsonFile.stringify` functions.",
```

File: common/changes/@rushstack/node-core-library/kenrick-fix-rush-add_2024-06-27-02-39.json [hunk 6]
```diff
@@ -0,0 +1,10 @@
...
+      "type": "patch"
```
Comment (iclanton) [inline common/changes/@rushstack/node-core-library/kenrick-fix-rush-add_2024-06-27-02-39.json:6]:
```suggestion
      "type": "minor"
```

**Review by iclanton — APPROVED** [review]

**Comment by octogonz** [comment]
🚀 Finally released with Rush 5.129.7 -- thanks for your patience!
