### PR TITLE
[rush-lib] fix: update shrinkwrap when globalPackageExtensions has been changed

### LINKED ISSUE #4901: [rush] Rush update should update shrinkwrap when globalPackageExtension has changed
## Summary

Similar to https://github.com/microsoft/rushstack/issues/4820 

Discovered when doing https://github.com/microsoft/rushstack/pull/4898

## Repro steps

1. In a Rush repo, with PNPM as package manager, add a dependency to a file
2. Do a `rush update`
3. Then change globalPackageExtension
4. Do a `rush update`

  **Expected result:** 

Rush should update the lockfile

  **Actual result:** 

Rush skips the checks and didn't update lockfile

Workaround is that we should run `rush update --recheck`

## Details

When `globalPackageExtension` has been updated and `libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts` needs to mark `shrinkwrapIsUpToDate` as false too.

However, package extension is represented as a checksum in the shrinkwrap file (`packageExtensionsChecksum`). That means we need to calculate the checksum of pnpm-config.json's `globalPackageExtension`  and compare it wit the checksum from the shrinkwrap file.

I checked how pnpm did it ([ref](https://github.com/pnpm/pnpm/blob/ba9409ffcef0c36dc1b167d770a023c87444822d/pkg-manager/core/src/install/index.ts#L821-L824)) and I guess we can copy the part, but what's missing is the `sortKeys` function. In pnpm, it is using [sort-keys@4.2.0](https://github.com/sindresorhus/sort-keys/tree/v4.2.0) but not sure if we should introduce an external dependencies for this case... What do you think?

```
const packageExtensionsChecksum = isEmpty(opts.packageExtensions ?? {}) ? undefined : createObjectChecksum(opts.packageExtensions!)


export function createObjectChecksum (obj: Record<string, unknown>) {
  const s = JSON.stringify(sortKeys(obj, { deep: true }))
  return crypto.createHash('md5').update(s).digest('hex')
}
``` 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.132.0 |
| `rushVersion` from rush.json? | 5.129.7 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  Mac |
| Would you consider contributing a PR? |  Yes |
| Node.js version (`node -v`)? | 18.20.4 |

### PR DESCRIPTION
**Pull request by kenrick95**
## Summary

Fixes #4901

## Details

Add one more condition in WorkspaceInstallManager to compare the values of:

- pnpm-config.json's `globalPackageExtensions` checksum
- shrinkwrap's `packageExtensionsChecksum`

To calculate the checksum, I added the same implementation as per what's used in pnpm ([ref](https://github.com/pnpm/pnpm/blob/ba9409ffcef0c36dc1b167d770a023c87444822d/pkg-manager/core/src/install/index.ts#L821-L824)). The code snippet used in pnpm is as such:

```ts
const packageExtensionsChecksum = isEmpty(opts.packageExtensions ?? {}) ? undefined : createObjectChecksum(opts.packageExtensions!)


export function createObjectChecksum (obj: Record<string, unknown>) {
  const s = JSON.stringify(sortKeys(obj, { deep: true }))
  return crypto.createHash('md5').update(s).digest('hex')
}
```

Since it depends on `sortKeys` (which pnpm uses [sort-keys@4.2.0](https://github.com/sindresorhus/sort-keys/tree/v4.2.0) npm package), I asked in [zulip](https://rushstack.zulipchat.com/#narrow/stream/279883-contributor-helpline/topic/Adding.20external.20dependencies.20or.20vendoring.20them.3F) if it's okay to add a new external dependency or not. The reply I received is to implement it in `node-core-library`, so I added: `Sort.sortKeys` with the tests imported and modified from [sort-keys@4.2.0](https://github.com/sindresorhus/sort-keys/blob/v4.2.0/test.js). 

## How it was tested

1. Run `testrush update` in a Rush repo
2. Change `globalPackageExtensions`
3. Run `testrush update` and expect that it updates the lockfile

```
> testrush update

Rush Multi-Project Build Tool 5.133.3 (unmanaged) - https://rushjs.io
Node.js version is 18.20.4 (LTS)


Starting "rush update"

Checking Git policy for this repository.


Found files in the "common/git-hooks" folder.
Successfully installed these Git hook scripts: commit-msg, owners.json, post-checkout, pre-commit, pre-push

Trying to acquire lock for pnpm-8.15.8
Acquired lock for pnpm-8.15.8
Found pnpm version 8.15.8 in /path/to/user/.rush/node-v18.20.4/pnpm-8.15.8

Symlinking "/path/to/repo/common/temp/pnpm-local"
  --> "/path/to/user/.rush/node-v18.20.4/pnpm-8.15.8"
Transforming /path/to/repo/common/config/rush/.npmrc
  --> "/path/to/repo/common/temp/.npmrc"

Updating workspace files in /path/to/repo/common/temp
Copying "/path/to/repo/common/config/rush/pnpm-lock.yaml"
  --> "/path/to/repo/common/temp/pnpm-lock.yaml"
Copying "/path/to/repo/common/config/rush/pnpm-lock.yaml"
  --> "/path/to/repo/common/temp/pnpm-lock-preinstall.yaml"

The shrinkwrap file (pnpm-lock.yaml) contains the following issues:
  The package extension hash doesn't match the current shrinkwrap.


Checking installation in "/path/to/repo/common/temp"

Running "pnpm install" in /path/to/repo/common/temp
```

## Impacted documentation

Updated the JSON schema of `node-core-library`

### CODE REVIEW

File: libraries/node-core-library/src/Sort.ts [hunk 1]
```diff
@@ -231,4 +231,79 @@ export class Sort {
...
+    }
+  ): T {
+    function isPlainObject(obj: unknown): boolean {
+      return obj !== null && typeof obj === 'object';
+    }
+    if (!isPlainObject(object) && !Array.isArray(object)) {
+      throw new TypeError(`Expected object or array`);
+    }
+
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (octogonz) [inline libraries/node-core-library/src/Sort.ts:259]: Most of these `no-explicit-any` warnings can be eliminated by using `unknown` instead of `any`, since this code mostly does not care about the structure of those values.

File: libraries/node-core-library/src/Sort.ts [hunk 2]
```diff
@@ -231,4 +231,79 @@ export class Sort {
...
+    const cache: WeakMap<T, any> = new WeakMap<T, any>();
```
Comment (octogonz) [inline libraries/node-core-library/src/Sort.ts:260]: It looks like the `WeakMap` value is always either an object or else an array.  If it cannot ever be `undefined`, then the lookup speed will be twice as fast if we replace this:
```ts
      if (cache.has(arr as T)) {
        return cache.get(arr as T)!;
      }
```
...with this:

```ts
      const value: unknown | undefined = cache.get(arr as T)
      if (value !== undefined) {
        return value;
      }
```
... and also the `!` is no longer needed for `get(arr as T)!`.

File: libraries/node-core-library/src/Sort.ts [hunk 3]
```diff
@@ -231,4 +231,92 @@ export class Sort {
...
+   *
+   * @example
+   *
+   * ```ts
+   * console.log(Sort.sortKeys({ c: 3, b: 2, a: 1 })); // { a: 1, b: 2, c: 3}
+   * ```
+   */
+  public static sortKeys<T extends Partial<Record<string, unknown>> | unknown[]>(
+    object: T,
+    { deep, compare }: { deep?: boolean; compare?: (x: string, y: string) => number } = {
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:246]: Make this type into an interface and export it. That way we can document what each parameter does in more detail

File: libraries/node-core-library/src/Sort.ts [hunk 4]
```diff
@@ -231,4 +231,92 @@ export class Sort {
       set.add(item);
     }
   }
+
+  /**
+   * Sort the keys given in an object
+   *
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:237]: Nit: missing @param doc comments for each parameter

File: libraries/node-core-library/src/Sort.ts [hunk 5]
```diff
@@ -231,4 +231,92 @@ export class Sort {
...
+   * console.log(Sort.sortKeys({ c: 3, b: 2, a: 1 })); // { a: 1, b: 2, c: 3}
+   * ```
+   */
+  public static sortKeys<T extends Partial<Record<string, unknown>> | unknown[]>(
+    object: T,
+    { deep, compare }: { deep?: boolean; compare?: (x: string, y: string) => number } = {
+      deep: false,
+      compare: Sort.compareByValue
+    }
+  ): T {
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:250]: This method returns the sorted object, but it looks like it also sorts the object in-place. Is there a reason to return the sorted object then? If we want to return an object, I would think it should be a clone of the original with the keys sorted, ensuring that the passed in object isn't manipulated

File: libraries/node-core-library/src/Sort.ts [hunk 6]
```diff
@@ -231,4 +231,92 @@ export class Sort {
...
+    if (!isPlainObject(object) && !Array.isArray(object)) {
+      throw new TypeError(`Expected object or array`);
+    }
+
+    const cache: WeakMap<
+      Partial<Record<string, unknown>> | unknown[],
+      Partial<Record<string, unknown>> | unknown[]
+    > = new WeakMap();
+
+    function innerSortArray(arr: unknown[]): unknown[] {
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:263]: Nit: move these inline functions out of the class and into the module level. Makes them easier to read and ensures that the function is only defined once, when the module is loaded

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts [hunk 7]
```diff
@@ -388,6 +402,22 @@ export class WorkspaceInstallManager extends BaseInstallManager {
     return { shrinkwrapIsUpToDate, shrinkwrapWarnings };
   }
 
+  private _getPackageExtensionChecksum(
```
Comment (D4N14L) [inline libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:405]: Does an existing method not get exported from the pnpm packages? If we could re-use their code, I think that would be ideal. If not, then this looks good :)

Comment (kenrick95) [reply libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:405]: `createObjectChecksum` is exported by `@pnpm/core`. However if we add that as dependency of Rush, it brings in a whole lots of other unused dependencies.

File: libraries/node-core-library/src/Sort.ts (hunk 5 above)
Comment (kenrick95) [reply libraries/node-core-library/src/Sort.ts:250]: It doesn't sort the object in-place, as it always return a clone. I added test to reflect this

File: libraries/node-core-library/src/Sort.ts (hunk 3 above)
Comment (kenrick95) [reply libraries/node-core-library/src/Sort.ts:246]: Updated

File: libraries/node-core-library/src/Sort.ts (hunk 6 above)
Comment (kenrick95) [reply libraries/node-core-library/src/Sort.ts:263]: Updated

File: libraries/node-core-library/src/Sort.ts (hunk 4 above)
Comment (kenrick95) [reply libraries/node-core-library/src/Sort.ts:237]: Updated

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 7 above)
Comment (D4N14L) [reply libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:405]: Would be a good idea to add a comment that permalinks to the implementation in PNPM source then, just for future reference (should anything ever change... hopefully unlikely, but good to have that reference)

File: libraries/node-core-library/src/Sort.ts [hunk 8]
```diff
@@ -231,4 +263,100 @@ export class Sort {
...
+        return entry;
+      })
+    );
+  } else {
+    result.push(...arr);
+  }
+
+  return result;
+}
+function innerSortKeys(
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:328]:
```suggestion

function innerSortKeys(
```

File: libraries/node-core-library/src/Sort.ts [hunk 9]
```diff
@@ -231,4 +263,100 @@ export class Sort {
...
+      cache,
+      options
+    };
+
+    return Array.isArray(object)
+      ? (innerSortArray(object, context) as T)
+      : (innerSortKeys(object, context) as T);
+  }
+}
+function isPlainObject(obj: unknown): obj is object {
```
Comment (D4N14L) [inline libraries/node-core-library/src/Sort.ts:300]:
```suggestion

function isPlainObject(obj: unknown): obj is object {
```

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts [hunk 10]
```diff
@@ -388,6 +402,22 @@ export class WorkspaceInstallManager extends BaseInstallManager {
...
+    packageExtensions: Record<string, unknown> | undefined
+  ): string | undefined {
+    const packageExtensionsChecksum: string | undefined =
+      Object.keys(packageExtensions ?? {}).length === 0
+        ? undefined
+        : createObjectChecksum(packageExtensions!);
+
+    function createObjectChecksum(obj: Record<string, unknown>): string {
```
Comment (D4N14L) [inline libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:413]: Nit: move to module level

**Review by D4N14L — APPROVED** [review]

File: common/changes/@rushstack/node-core-library/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json [hunk 11]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/node-core-library",
+      "comment": "Add Sort.sortKeys for sorting keys in an object",
```
Comment (iclanton) [inline common/changes/@rushstack/node-core-library/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json:5]:
```suggestion
      "comment": "Add a `Sort.sortKeys` function for sorting keys in an object",
```

File: libraries/node-core-library/src/Sort.ts [hunk 12]
```diff
@@ -1,6 +1,38 @@
...
+ *
+ * @public
+ */
+export interface ISortKeysOptions {
+  /**
+   * Whether or not to recursively sort keys, both in objects and arrays
+   * @defaultValue false
+   */
+  deep?: boolean;
+  /**
```
Comment (iclanton) [inline libraries/node-core-library/src/Sort.ts:15]:
```suggestion
  deep?: boolean;
  
  /**
```

File: libraries/node-core-library/src/Sort.ts (hunk 9 above)
Comment (iclanton) [inline libraries/node-core-library/src/Sort.ts:300]:
```suggestion
}

function isPlainObject(obj: unknown): obj is object {
```

File: libraries/node-core-library/src/Sort.ts (hunk 8 above)
Comment (iclanton) [inline libraries/node-core-library/src/Sort.ts:328]:
```suggestion
}

function innerSortKeys(
```

File: libraries/node-core-library/src/Sort.ts [hunk 13]
```diff
@@ -231,4 +263,100 @@ export class Sort {
...
+function innerSortArray(arr: unknown[], context: ISortKeysContext): unknown[] {
+  const resultFromCache: undefined | Partial<Record<string, unknown>> | unknown[] = context.cache.get(arr);
+  if (resultFromCache !== undefined) {
+    return resultFromCache as unknown[];
+  }
+  const result: unknown[] = [];
+  context.cache.set(arr, result);
+  if (context.options.deep) {
+    result.push(
+      ...arr.map((entry) => {
```
Comment (dmichon-msft) [inline libraries/node-core-library/src/Sort.ts:313]: Using variadic function calls with an unknown number of arguments is not safe, if the input `arr` gets too large (>20k elements or so), this will cause a stack overflow. Need to loop over `arr` and make individual `push` calls instead, at which point you can also flatten this into a single loop with the function body inlined.

File: libraries/node-core-library/src/Sort.ts [hunk 14]
```diff
@@ -231,4 +263,100 @@ export class Sort {
...
+        if (Array.isArray(entry)) {
+          return innerSortArray(entry, context);
+        } else if (isPlainObject(entry)) {
+          return innerSortKeys(entry, context);
+        }
+        return entry;
+      })
+    );
+  } else {
+    result.push(...arr);
```
Comment (dmichon-msft) [inline libraries/node-core-library/src/Sort.ts:323]: Not safe to pass `...arr` in a function argument position due to stack overflow if `arr` gets large. Use a loop over `arr` with per-element calls to `push` instead.

File: libraries/node-core-library/src/test/Sort.test.ts [hunk 15]
```diff
@@ -69,3 +69,192 @@ test('Sort.sortSet', () => {
...
+      b: 0,
+      c: { a: 0, b: 0, c: 0 }
+    });
+
+    expect(() => {
+      // eslint-disable-next-line @typescript-eslint/no-explicit-any
+      const object: Partial<Record<string, any>> = { a: 0 };
+      object.circular = object;
+      Sort.sortKeys(object, { deep: true });
+    }).not.toThrow();
```
Comment (iclanton) [inline libraries/node-core-library/src/test/Sort.test.ts:143]: If anything throws, the test will fail, so these assertions are unnecessary.

File: libraries/node-core-library/src/test/Sort.test.ts [hunk 16]
```diff
@@ -69,3 +69,192 @@ test('Sort.sortSet', () => {
   Sort.sortSet(set);
   expect(Array.from(set)).toEqual(['aardvark', 'goose', 'zebra']);
 });
+
+describe('Sort.sortKeys', () => {
+  // Test cases from https://github.com/sindresorhus/sort-keys/blob/v4.2.0/test.js
+  function deepEqualInOrder(
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (iclanton) [inline libraries/node-core-library/src/test/Sort.test.ts:76]: Can you use `unknown`s in these instead?

File: common/changes/@microsoft/rush/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json [hunk 17]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@microsoft/rush",
+      "comment": "Always update shrinkwrap when globalPackageExtensions has been changed",
```
Comment (iclanton) [inline common/changes/@microsoft/rush/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json:5]:
```suggestion
      "comment": "Always update shrinkwrap when `globalPackageExtensions` in `common/config/rush/pnpm-config.json` has been changed.",
```

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts [hunk 18]
```diff
@@ -388,6 +402,22 @@ export class WorkspaceInstallManager extends BaseInstallManager {
...
+      const s: string = JSON.stringify(Sort.sortKeys(obj, { deep: true }));
```
Comment (dmichon-msft) [inline libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:414]: This might be better to do the sorting as the replacer function to `JSON.stringify`. That would result in less memory usage because it would be able to process only one object or array at a time, rather than having to create a full recursive copy.

Comment (kenrick95) [reply libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: That would diverge from the implementation in pnpm and I'm not confident in implementing it that way...

File: libraries/node-core-library/src/test/Sort.test.ts (hunk 16 above)
Comment (kenrick95) [reply libraries/node-core-library/src/test/Sort.test.ts]: Done

File: libraries/node-core-library/src/test/Sort.test.ts (hunk 15 above)
Comment (kenrick95) [reply libraries/node-core-library/src/test/Sort.test.ts]: Removed

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 10 above)
Comment (kenrick95) [reply libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts]: Moved

File: libraries/node-core-library/src/Sort.ts (hunk 13 above)
Comment (kenrick95) [reply libraries/node-core-library/src/Sort.ts]: Modified!

File: libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts (hunk 7 above)
Comment (kenrick95) [reply libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts:405]: Added

**Review by iclanton — APPROVED** [review]
