### PR TITLE
[heft-jest-plugin] Set Jest `displayName` to the package name by default and log test duration

### LINKED ISSUE #2848: [heft] Heft test-jest duration lost
## Summary

When running `heft test` with the jest plugin, the test duration is lost; example:

```
PASS src/test/mv.test.ts (duration: ?, 2 passed, 0 failed)
PASS src/test/cp.test.ts (duration: ?, 2 passed, 0 failed)
PASS src/test/fsu.test.ts (duration: ?, 12 passed, 0 failed)
PASS src/test/spawn-promise.test.ts (duration: ?, 10 passed, 0 failed)
PASS src/test/sh.test.ts (duration: ?, 5 passed, 0 failed)
PASS src/test/cvevwa.test.ts (duration: ?, 4 passed, 0 failed)
```

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Set the Jest `displayName` to the package name that contains the tests being run by default, instead of requiring it to be specified in each `jest.config.json`.

Additionally, this PR adds fallback logic for calculating the test duration in the reporter if the Jest-provided value is not available.

Fixes #2848

## Details

The `displayName` field is intended to help differentiate between projects in Jest. While we use our own reporter instead of the built-in reporter and therefore do not use the displayName, it can be used in other reporters such as `jest-junit` to provide more context.

Additionally, the test duration value is not always available/provided by Jest, so we can perform a lightweight tracking of start and end times to provide our own duration.

## How it was tested

Running a build and outputting the displayName manually in the HeftJestReporter to confirm the value was set correctly.

### CODE REVIEW

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts [hunk 1]
```diff
@@ -47,13 +48,20 @@ export default class HeftJestReporter implements Reporter {
       Colors.whiteBackground(Colors.black('START')),
       ` ${this._getTestPath(test.path)}`
     );
+
+    // Test duration is not always available, so we'll use a map to track the start time
+    // of each test and diff against the end time
+    this._testStartTime.set(test.path, Date.now());
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:54]: `Date.now()` is not meant to be used for performance measurements.  We should be using `performance.now()` or something like 

https://github.com/microsoft/rushstack/blob/276d593379034746da729eb578e117d1497acb49/apps/rush-lib/src/utilities/Utilities.ts#L141-L147

(Maybe this should be exposed via `node-core-library`?)

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts [hunk 2]
```diff
@@ -65,11 +73,10 @@ export default class HeftJestReporter implements Reporter {
       this._terminal.write(Colors.greenBackground(Colors.black('PASS')));
     }
 
-    const duration: string = test.duration ? `${test.duration / 1000}s` : '?';
     this._terminal.writeLine(
-      ` ${this._getTestPath(
-        test.path
-      )} (duration: ${duration}, ${numPassingTests} passed, ${numFailingTests} failed)`
+      ` ${this._getTestPath(test.path)} (duration: ${
+        durationMs / 1000
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:78]: What does this formatting look like?

File: common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json [hunk 3]
```diff
@@ -0,0 +1,11 @@
+{
```
Comment (octogonz) [inline common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json:1]: > Additionally, the test duration value is not always available/provided by Jest,

Why not?

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts (hunk 1 above)
Comment (octogonz) [reply heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:54]: Looks like `performance.now()` is now supported as of Node.js 8.5.0

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts (hunk 2 above)
Comment (octogonz) [reply heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:78]: I wish we could standardize this better across our projects.

I did some work on that a long time ago in https://github.com/microsoft/rushstack/commit/c8b39d46e6e55152e6df247ed63489651edf3d49 but never merged it.

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts (hunk 1 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:54]: As you said offline, seems that `performance.now()` is available and was since Node 8. Will use that.

File: heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts (hunk 2 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts:78]: `PASS src\test\JestPlugin.test.ts (duration: 1.726s, 2 passed, 0 failed)` is how the output appears when running with these changes, though I will make a change to use `toFixed` so that we have a constant number of decimals.

File: common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json (hunk 3 above)
Comment (D4N14L) [reply common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json:1]: Honestly I'm unsure. The type does seem to recognize that it may not be set here, but there's no documentation stating why that is the case, and the `testResult.perfStats` seem to be what other reporters use (see: https://github.com/jest-community/jest-junit/blob/12da1a20217a9b6f30858013175319c1256f5b15/utils/buildJsonResults.js#L112)

My best guess is that it's what some old version of Jest did but no longer does... Either way, I've updated the check to fall back to `perfStats` and left the original `test.duration` check in there, since it doesn't seem to be hurting or helping. I'm okay with removing the original check if you want.

**Review by dmichon-msft — APPROVED** [review]

File: common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json (hunk 3 above)
Comment (octogonz) [reply common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json:1]: I had more questions about this. We chatted about it offline and determined that Jest is perhaps neglecting to populate this field because it is not used in Jest's standard reporter.  Instead Jest displays timings at the very end of the run instead of interactively, and has not calculated the numbers yet at this point in time.  This resolved my concern that Heft might be somehow incorrectly implementing the Jest contract (i.e. _why should Heft need to measure test times, when that is supposed to be a feature of the test runner?_).

**Review by octogonz — APPROVED** [review]
