### PR TITLE
[eslint-config] Upgrade @typescript-eslint/* to 4.28.0

### LINKED ISSUE #2389: [eslint-config] Outdated version of typescript-eslint plugin and parser
## Summary

I would like to use TypeScript 4.1.2 in a project which is using the rushstack config. When running ESLint, I see the following message:
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <3.10.0
YOUR TYPESCRIPT VERSION: 4.1.2
Please only submit bug reports when using the officially supported version.
=============
```

## Details

I don't know whether bumping up to the newest version of `typescript-eslint`'s tools would cause problems, given that these libraries had a major version change, but if it's possible then that would be helpful for me.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-config` version? | 2.1.1 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.1.2 |
| Node.js version (`node -v`)? | 12.8.4 |

### PR DESCRIPTION
**Pull request by relm923**
## Summary

Fixes #2389 by upgrading all `@typescript-eslint/*` dependencies from `3.4.0` to latest (`4.28.0`)

## How it was tested

```sh
rush rebuild
```

### CODE REVIEW

File: apps/heft/src/cli/actions/CustomAction.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ export interface ICustomActionParameterStringList extends ICustomActionParameter
 }
 
 /** @beta */
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
 export interface ICustomActionParameterBase<TParameter extends CustomActionParameterType> {
```
Comment (octogonz) [inline apps/heft/src/cli/actions/CustomAction.ts:35]: @iclanton What's going on here? Why do we have a interface with a generic parameter that is unused?

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
Released with `@rushstack/eslint-config` 2.4.0.  Thanks @relm923 for making this PR!
