### PR TITLE
[webpack5-localization-plugin] Streamline processing

### LINKED ISSUE #5093: [webpack5-localization-plugin] Plugin should only recalculate changed assets
## Summary
Currently, if running in watch mode, all assets that interact with the localization plugin get recomputed on every compilation, even if none of their inputs have changed.

## Repro steps
Run webpack in watch mode with the plugin enabled.
Change a file that is not in a localized asset.

  **Expected result:** 
The localization plugin should replay all unaffected assets from cache.

  **Actual result:** 
Observe that all localized assets get reconstructed.

## Details
The plugin currently has no infrastructure in place for detecting unchanged assets.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| Package name: | @rushstack/webpack5-localization-plugin |
| Package version? | 0.11.24 |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.19.1 |

### PR DESCRIPTION
**Pull request by dmichon-msft**
## Summary
Fixes #5093 

## Details
Leverages webpack's caching layer for the localized asset processing.
Currently does not add caching for trueHash computation, that'll need its own PR since it's a bit more complex.
Splits the placeholder map into two layers: a map of keys to files, then string names to placeholders. This facilitates creating fewer intermediary objects and thereby reducing memory pressure and the amount of data processing needed.
Stops parsing non-localized chunks that aren't known to contain placeholders.

## How it was tested
Unit tests to ensure functionality didn't regress.
Running against an external project to validate performance impact.

## Impacted documentation
API documentation for removed access to internals.

### CODE REVIEW

File: webpack/webpack5-localization-plugin/src/AssetProcessor.ts [hunk 1]
```diff
@@ -209,26 +303,28 @@ function _reconstructLocalized(
...
-          } else {
-            issues.push(
-              `The string "${data.stringName}" in "${data.locFilePath}" is missing in ` +
-                `the locale ${locale}`
-            );
-
-            newValue = '-- MISSING STRING --';
-          }
+          issues.push(
+            `The string "${stringName}" in "${data.locFilePath}" is missing in ` + `the locale ${locale}`
```
Comment (dmichon-msft) [inline webpack/webpack5-localization-plugin/src/AssetProcessor.ts:324]: Thanks prettier...

File: webpack/webpack5-localization-plugin/src/AssetProcessor.ts [hunk 2]
```diff
@@ -148,50 +202,90 @@ export function processLocalizedAsset(options: IProcessLocalizedAssetOptions): R
...
   const locale: string = options.noStringsLocaleName;
-  const { issues: localeIssues, result } = _reconstructNonLocalized(
-    new sources.ReplaceSource(rawSource, locale),
-    parsedAsset.reconstructionSeries,
-    locale
-  );
 
-  for (const issue of localeIssues) {
-    issues.push(issue);
+  if (hasJsonP) {
```
Comment (iclanton) [inline webpack/webpack5-localization-plugin/src/AssetProcessor.ts:247]:
```suggestion
  if (hasUrlGenerator) {
```

**Review by iclanton — APPROVED** [review]

File: webpack/webpack5-localization-plugin/src/AssetProcessor.ts [hunk 3]
```diff
@@ -91,6 +143,8 @@ export function processLocalizedAsset(options: IProcessLocalizedAssetOptions): R
   const localizedFiles: Record<string, string> = {};
   (chunk as ILocalizedWebpackChunk).localizedFiles = localizedFiles;
```
Comment (dmichon-msft) [inline webpack/webpack5-localization-plugin/src/AssetProcessor.ts:144]: This line needs to happen outside of the caching call.
