### PR TITLE
[rush] Fix filtered installs in pnpm@8

### LINKED ISSUE #4285: [rush] installing "to" a workspace project still installs all packages for all projects (using pnpm v8)
## Summary

With rush v5.102.0 and pnpm v8.6.12, using the `--to` or `-t` flag with `rush install` seems to have no effect.

Dependencies for all projects are still installed.

## Repro steps

1. `rush purge`
2. `rush install -t @myscope/myproject` where `@myscope/myproject` is a workspace project

  **Expected result:** only `@myscope/myproject` and its rush project dependencies have a complete `node_modules` folder

  **Actual result:** all rush projects have a complete `node_modules` folder

## Details

I found the (very old) issue #1669 and thought that perhaps this feature wasn't implemented.

However, I ran `rush --debug install -t [my packge]` and saw output that indicated rush is passing a `--filter` option to pnpm.

So, I think this is intended to work?

Specifically, this is the pnpm install command that prints out when I add `--debug`

```
$ rush --debug install -t @myscope/myproject

...

Invoking package manager: /Users/jbrandt/.rush/node-v18.16.0/pnpm-8.6.12/node_modules/pnpm/bin/pnpm.cjs install --store /Users/jbrandt/.pnpmcache --config.cacheDir=/Users/jbrandt/.pnpmcache --config.stateDir=/Users/jbrandt/.pnpmcache --no-prefer-frozen-lockfile --strict-peer-dependencies --config.ignoreCompatibilityDb --recursive --link-workspace-packages false --filter @myscope/myproject...
```

The main reason I want this feature to work is to speed up dependency installation in our CI/CD build steps that only build a portion of our monorepo.

Thank you for all the great work you do on rush! It is a delight to use!

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.101.1 |
| `rushVersion` from rush.json? | 5.102.0 |
| `pnpmVersion` from rush.json? | 8.6.12 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | reproed on Mac and Linux |
| Would you consider contributing a PR? | Yes, but not for this bug (no idea how to fix!) |
| Node.js version (`node -v`)? | 18.16.0 |

### PR DESCRIPTION
**Pull request by dmichon-msft**
## Summary
Fixes #4285 

## Details
Sets the `dedupe-peer-dependents=false` option when passing filter arguments and installing with `--frozen-lockfile`.

## How it was tested
Created a second git worktree and used the modified version of rush to run `rush install --to @rushstack/heft`:
```
Running "pnpm install" in /workspaces/rushstack-2/common/temp

Scope: 14 of 130 workspace projects
Lockfile is up to date, resolution step is skipped
.                                        | +507 +++++++++++++++++++++++++++++++++++++++++++++++++++

Downloading registry.npmjs.org/typescript/5.0.4: 7.05 MB/7.05 MB, done
Progress: resolved 507, reused 0, downloaded 497, added 507, done
Done in 2.8s
```

## Impacted documentation
None.

### CODE REVIEW

File: libraries/rush-lib/src/logic/base/BaseInstallManager.ts [hunk 1]
```diff
@@ -572,6 +572,14 @@ ${gitLfsHookHandling}
 
       if (experiments.usePnpmFrozenLockfileForRushInstall && !options.allowShrinkwrapUpdates) {
         args.push('--frozen-lockfile');
+
+        if (
+          options.pnpmFilterArguments.length > 0 &&
+          semver.satisfies(this.rushConfiguration.packageManagerToolVersion, '^8')
```
Comment (iclanton) [inline libraries/rush-lib/src/logic/base/BaseInstallManager.ts:578]: Feels like we must already have the major version parsed out somewhere.

Comment (dmichon-msft) [reply libraries/rush-lib/src/logic/base/BaseInstallManager.ts:578]: Could just do a `.startsWith('8.')` I guess. I don't see it parsed anywhere here.

**Review by iclanton — APPROVED** [review]
