### PR TITLE
[heft] Provide a more helpful error message when using legacy Heft configurations

### LINKED ISSUE #4175: [heft] Heft fails with "Resolved configuration object does not match schema" error
## Summary

Updated my project to the latest versions of heft (`0.51.0`) but it now fails on any heft command with the message `Resolved configuration object does not match schema`. The project builds and runs as expected with heft version `0.50.6`.

## Repro steps
1. Clone the demo repo https://github.com/pealmeid/heft-test;
2. Run `npm install`;
3. Run `heft build`;

  **Expected result:** 
Project should build as expected and `npm run start` should generate `Hello, World!`

  **Actual result:** 
`heft build` fails with the following message:

`Error: Resolved configuration object does not match schema: Error: JSON validation failed:`
`/Projects/heft-test/config/heft.json`
`Error: #/ (Defines configuration used by core Heft.)`
 `Additional properties not allowed: eventActions`

## Details
Project builds and runs as expected if you change `package.json` to use `@rushstack/heft: ^0.50.6`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? |  0.51.0|
| Operating system? |Mac OS Ventura and Windows 11|
| Would you consider contributing a PR? | no |
| Node.js version (`node -v`)? | 18.16.0 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary
Provides a more useful error message when encountering a Heft configuration that matches the legacy format.

Fixes #4175

```text
PS D:\Work\rushstack3\libraries\rush-lib> node .\node_modules\@rushstack\heft\bin\heft build
Error: This project's Heft configuration appears to be using an outdated schema.

Heft 0.51.0 introduced a major breaking change for Heft configuration files. Your project appears to be using the older file format.  You will need to migrate your project to the new format. Follow these instructions: https://rushstack.io/link/heft-0.51
```

## How it was tested

Locally using a Heft configuration that matched the legacy schema.

## Impacted documentation

Needs link to be updated to be actual documentation.

### CODE REVIEW

**Review by dmichon-msft — APPROVED** [review]

File: apps/heft/src/utilities/CoreConfigFiles.ts [hunk 1]
```diff
@@ -111,12 +111,42 @@ export class CoreConfigFiles {
...
-      await CoreConfigFiles._heftConfigFileLoader.loadConfigurationFileForProjectAsync(
+    let configurationFile: IHeftConfigurationJson;
+    try {
+      configurationFile = await CoreConfigFiles._heftConfigFileLoader.loadConfigurationFileForProjectAsync(
         terminal,
         projectPath,
         rigConfig
       );
+    } catch (e: unknown) {
+      if (!(e as Error).message.startsWith('Resolved configuration object does not match schema')) {
```
Comment (iclanton) [inline apps/heft/src/utilities/CoreConfigFiles.ts:122]: We can't do an `instanceof` check or look for a `.code` property?

File: apps/heft/src/utilities/CoreConfigFiles.ts [hunk 2]
```diff
@@ -111,12 +111,42 @@ export class CoreConfigFiles {
...
+        // It doesn't match the legacy schema either. Throw the original error.
+        throw e;
+      }
+      // Matches the legacy schema, so throw a more helpful error.
+      throw new Error(
+        "This project's Heft configuration appears to be using an outdated schema.\n\n" +
+          'Heft 0.51.0 introduced a major breaking change for Heft configuration files. ' +
+          'Your project appears to be using the older file format. You will need to ' +
+          'migrate your project to the new format. Follow these instructions: ' +
+          'https://rushstack.io/link/heft-0.51'
```
Comment (iclanton) [inline apps/heft/src/utilities/CoreConfigFiles.ts:147]: Maybe stick this in a const?

File: apps/heft/src/schemas/heft-legacy.schema.json [hunk 3]
```diff
@@ -0,0 +1,214 @@
...
+            "type": "string",
+            "pattern": "[^\\\\]"
+          },
+
+          "options": {
+            "type": "object"
+          }
+        }
+      }
+    }
```
Comment (iclanton) [inline apps/heft/src/schemas/heft-legacy.schema.json:212]: Do we actually care that the stuff inside `"heftPlugins"` and `"eventActions"` matches the old schema, or just if it kinda looks like an old config file?

Comment (D4N14L) [reply apps/heft/src/schemas/heft-legacy.schema.json:212]: `heftPlugins` actually exists in the new format, even though the contents of it has changed. That's why I'm validating the entire config instead of just looking for specific properties in the raw file

File: apps/heft/src/utilities/CoreConfigFiles.ts (hunk 2 above)
Comment (D4N14L) [reply apps/heft/src/utilities/CoreConfigFiles.ts:147]: I'm going to leave as-is for now. I like having the block of text inline since it provides me better context of what is going on in the error handling here.

File: apps/heft/src/utilities/CoreConfigFiles.ts (hunk 1 above)
Comment (D4N14L) [reply apps/heft/src/utilities/CoreConfigFiles.ts:122]: No, this error doesn't have a .code property, it's just a normal error. I will however add an instanceof check

**Review by iclanton — APPROVED** [review]

**Comment by D4N14L** [comment]
@octogonz could you live the documentation at that link? Must have slipped through when this change went in.

**Comment by octogonz** [comment]
I'll fix it today

**Comment by octogonz** [comment]
https://github.com/microsoft/rushstack-websites/pull/161
