### PR TITLE
[package-extractor] Ensure that the `folderToCopy` option is included in generated archives

### LINKED ISSUE #4371: [rush] "deploy --create-archive" ignores "folderToCopy" in ^5.98.0
## Summary
Starting with version `5.98.0`, the command `rush deploy --create-archive` ignores the `folderToCopy` specified in `deploy.json`.

If a `deploy.json` specifies `folderToCopy`, the content of the folder **is** correctly copied to `common/deploy`.  However, the content of the folder **is not** added to the generated archive.

## Repro steps
1. Create a `deploy.json` with a `folderToCopy`.
2. Set `rushVersion` to `5.97.1`
3. Run `rush deploy --create-archive`
4. The contents of `folderToCopy` should be under `common/deploy`, and in the zipfile.
5. Upgrade to `rush@5.98.0`.
6. Re-run `rush deploy --create-archive`
7. The contents of `folderToCopy` will be under `common/deploy`, but not in the zipfile.

## Details
I believe the issue is here:

https://github.com/microsoft/rushstack/blob/7d7f84e9358b44a32d248c784a87b85eb1fe100f/libraries/package-extractor/src/PackageExtractor.ts#L446-L453

The folder is copied, but the files are not added to the `ArchiveManager`, so they are not added to the generated zipfile.

Files copied from projects (rather than from `folderToCopy`) are added to the `ArchiveManager` here:

https://github.com/microsoft/rushstack/blob/7d7f84e9358b44a32d248c784a87b85eb1fe100f/libraries/package-extractor/src/PackageExtractor.ts#L795-L802

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.102.0 |
| `rushVersion` from rush.json? | 5.98.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.20.2 |

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

During the refactor to the `@rushstack/package-extractor` a change in behavior was accidentally introduced where the `folderToCopy` field was not included in the generated archive. Fixes #4371 

## Details

The `folderToCopy` field is now treated as if it were just another folder being traversed during extraction. The folder is explicitly mapped to the root of the target output folder/archive, just as previously spec'd.

## How it was tested

Added a test to ensure that the copy operation behaves as it had previously.

### CODE REVIEW

**Review by octogonz — APPROVED** [review]

File: libraries/package-extractor/src/PackageExtractor.ts [hunk 1]
```diff
@@ -409,6 +409,21 @@ export class PackageExtractor {
       }
     );
 
+    if (addditionalFolderToCopy) {
+      // Copy the additional folder directly into the root of the target folder by overriding the
```
Comment (D4N14L) [inline libraries/package-extractor/src/PackageExtractor.ts:413]:
```suggestion
      // Copy the additional folder directly into the root of the target folder by postfixing the
      // folder name to the target folder and setting the sourceRootFolder to the root of the
      // folderToCopy
```
