### PR TITLE
[heft-webpack5-plugin]update WebpackConfigurationLoader to support any valid webpack config file name

### LINKED ISSUE #3988: [heft] WebpackConfigurationLoader lacks support for .cjs file extensions
## Summary
While working to update a rush monorepo to ESM I hit an issue when attempting to update webpack config files to leverage a `.cjs` file extension. For "reasons", we'd prefer to not refactor the entire webpack config system away from require, etc...and instead just append the appropriate file extension.

It seems that [this file](https://github.com/microsoft/rushstack/blob/84ad0baf6f1308549e6ebc031f0cf38a4e46d27b/heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts#L27) has hardcoded strings for valid file names which look specifically for `.js` files.

## Repro steps
I can't share the repository, but initializing the minimum rush repo with support for ESM (module resolution of `nodenext` or `Node16`, file extensions on all import/exports, packages with `"type": "module"`. Configure webpack with a .cjs extension.

## Details
This is currently blocking our migration, so while I think a broader feature for more configuration here might be helpful, ideally this could come in with a quick fix as not being able to use a `.cjs` file extension for webpack is quite prescriptive and "buggy".  

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.78.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | all |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 16.18.0 |

### PR DESCRIPTION
**Pull request by chrisdholt**
## Summary
fixes #3988

## Details
This PR adds a function to gather any valid webpack config file (.js, .mjs, .cjs) rather than using the hardcoded values. I considered integrating this with existing methods but wasn't sure if that would be preferred.

## How it was tested
I have not tested it yet, opening this draft to figure out the best method of ensuring this works without introducing breaking changes.

### CODE REVIEW

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts [hunk 1]
```diff
@@ -92,3 +94,18 @@ export class WebpackConfigurationLoader {
     }
   }
 }
+
+function findWebpackConfig(buildFolder: string, configurationRegExp: RegExp): string {
+  try {
+    const configs = FileSystem.readFolderItemNames(buildFolder).filter((config) =>
```
Comment (iclanton) [inline heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:100]:
```suggestion
async function findWebpackConfigAsync(buildFolder: string, configurationRegExp: RegExp): Promise<string> {
  try {
    const folderItems: FolderItem = await FileSystem.readFolderItemsAsync(buildFolder);
    const configs: string[] = [];
    for (folderItem of folderItems) {
      if (folderItem.isFile() && folderItem.name.match(configurationRegExp)) {
        configs.push(folderItem.name);
      }
    }

```

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts [hunk 2]
```diff
@@ -36,6 +36,8 @@ export class WebpackConfigurationLoader {
     // TODO: Eventually replace this custom logic with a call to this utility in in webpack-cli:
     // https://github.com/webpack/webpack-cli/blob/next/packages/webpack-cli/lib/groups/ConfigGroup.js
 
+    const WEBPACK_CONFIG_FILENAME: string = findWebpackConfig(buildFolder, WEBPACK_CONFIG_FILENAME_REGEX);
+    const WEBPACK_DEV_CONFIG_FILENAME: string = findWebpackConfig(buildFolder, WEBPACK_CONFIG_FILENAME_REGEX);
```
Comment (iclanton) [inline heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:40]:
```suggestion
    const WEBPACK_CONFIG_FILENAME: string = await findWebpackConfigAsync(buildFolder, WEBPACK_CONFIG_FILENAME_REGEX);
    const WEBPACK_DEV_CONFIG_FILENAME: string = await findWebpackConfigAsync(buildFolder, WEBPACK_CONFIG_FILENAME_REGEX);
```

Comment (iclanton) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:40]: This will read the folder items twice. It'd be more efficient for the function to just return both the dev and non-dev filenames.

Comment (chrisdholt) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:40]: All for this and considered it initially. Let me make the changes locally - there's also a couple of tests failing I can look into. Once I get it updated and address any comments, I can move this from draft.

Comment (chrisdholt) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:40]: @iclanton if we want to run this _once_ for both configs, thoughts on returning an object with keys of `dev` and `prod` in this scenario rather than an array?

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts (hunk 1 above)
Comment (chrisdholt) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts]: @iclanton I've incorporated this as well as an adjustment to return an object w/ dev/prod keys respectively. A bit different than the initial approach, but serves fallbacks in the case either is undefined. Let me know your thoughts when you can.

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts (hunk 2 above)
Comment (iclanton) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts]: Yeah that's how I'd do it.

Comment (chrisdholt) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts]: Should be updated with an approach that follows that. Let me know any thoughts/feedback when you get a chance to review. Thanks @iclanton!

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts [hunk 3]
```diff
@@ -92,3 +98,29 @@ export class WebpackConfigurationLoader {
...
+    const folderItems: FolderItem[] = await FileSystem.readFolderItemsAsync(buildFolder);
+    const dev: string[] = [];
+    const prod: string[] = [];
+
+    for (const folderItem of folderItems) {
+      if (folderItem.isFile() && folderItem.name.match(/^webpack.dev.config\.(cjs|js|mjs)$/)) {
+        dev.push(folderItem.name);
+      } else if (folderItem.isFile() && folderItem.name.match(/^webpack.config\.(cjs|js|mjs)$/)) {
+        prod.push(folderItem.name);
+      }
```
Comment (iclanton) [inline heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:113]:
```suggestion
      if (folderItem.isFile()) {
        if (folderItem.name.match(/^webpack.dev.config\.(cjs|js|mjs)$/)) {
          dev.push(folderItem.name);
        } else if (folderItem.name.match(/^webpack.config\.(cjs|js|mjs)$/)) {
          prod.push(folderItem.name);
        }
      }
```

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts [hunk 4]
```diff
@@ -92,3 +98,29 @@ export class WebpackConfigurationLoader {
...
+    }
+
+    if (dev.length > 1 || prod.length > 1) {
+      throw new Error(`Error: Found more than one matching webpack configuration files.`);
+    }
```
Comment (iclanton) [inline heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:118]:
```suggestion
    if (dev.length > 1) {
      throw new Error(`Error: Found more than one dev webpack configuration file.`);
    } else if (prod.length > 1) {
      throw new Error(`Error: Found more than one non-dev webpack configuration file.`);
    }

```

File: common/changes/@rushstack/heft-webpack5-plugin/users-chhol-heft-webpack-check-for-valid-files-types_2023-03-08-18-11.json [hunk 5]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/heft-webpack5-plugin",
+      "comment": "adds support to find any valid webpack config file type",
```
Comment (iclanton) [inline common/changes/@rushstack/heft-webpack5-plugin/users-chhol-heft-webpack-check-for-valid-files-types_2023-03-08-18-11.json:5]:
```suggestion
      "comment": "Add support for `.cjs` and `.mjs` file extensions for webpack config files, in addition to the `.js` file extension.",
```

**Review by iclanton — APPROVED** [review]

**Review by eljefe223 — APPROVED** [review]

File: heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts [hunk 6]
```diff
@@ -92,3 +98,34 @@ export class WebpackConfigurationLoader {
...
+  try {
+    const folderItems: FolderItem[] = await FileSystem.readFolderItemsAsync(buildFolder);
+    const dev: string[] = [];
+    const prod: string[] = [];
+
+    for (const folderItem of folderItems) {
+      if (folderItem.isFile()) {
+        if (folderItem.name.match(/^webpack.dev.config\.(cjs|js|mjs)$/)) {
+          dev.push(folderItem.name);
+        } else if (folderItem.isFile() && folderItem.name.match(/^webpack.config\.(cjs|js|mjs)$/)) {
```
Comment (iclanton) [inline heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:112]:
```suggestion
        } else if (folderItem.name.match(/^webpack.config\.(cjs|js|mjs)$/)) {
```

Comment (chrisdholt) [reply heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts:112]: AH dangit - I missed it. @iclanton mind if we commit here?

**Review by iclanton — APPROVED** [review]
